import type { Question } from '../types';

export const VOCAB_CD: Question[] = [
  {
    id: 'vc-cd-001',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CAPABLE',
    choices: ['unwilling', 'careless', 'able', 'nervous'],
    answer: 2,
    explain: 'Capable means having the skill or strength to do something. A person who is able to do the job is capable of it.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-002',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CAPTURE',
    choices: ['seize', 'release', 'follow', 'repair'],
    answer: 0,
    explain: 'To capture something is to catch it and keep hold of it. Seize means to grab and take hold of.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-003',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CEASE',
    choices: ['begin', 'hurry', 'repeat', 'stop'],
    answer: 3,
    explain: 'Cease means to come to an end. When the rain ceases, it stops falling.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-004',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CHERISH',
    choices: ['forget', 'treasure', 'sell', 'ignore'],
    answer: 1,
    explain: 'To cherish something is to love it and take special care of it. That is what it means to treasure something.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-005',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CLUMSY',
    choices: ['graceful', 'awkward', 'tidy', 'noisy'],
    answer: 1,
    explain: 'Clumsy means moving in an unsteady way and bumping into or dropping things. Awkward movement is clumsy movement.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-006',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CLARIFY',
    choices: ['confuse', 'decide', 'delay', 'explain'],
    answer: 3,
    explain: 'To clarify is to make something easier to understand. Explaining an idea clearly is clarifying it.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-007',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COARSE',
    choices: ['damp', 'shiny', 'rough', 'narrow'],
    answer: 2,
    explain: 'Coarse describes something with a scratchy, uneven texture. Sandpaper and burlap are coarse, not smooth.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-008',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COLLIDE',
    choices: ['crash', 'swerve', 'float', 'bounce'],
    answer: 0,
    explain: 'To collide is to run into something with force. Two carts that collide crash into each other.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-009',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COMFORT',
    choices: ['soothe', 'startle', 'scold', 'obey'],
    answer: 0,
    explain: 'To comfort someone is to help them feel better when they are upset. Soothe means to calm a person that same way.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-010',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COMPETE',
    choices: ['give up', 'work together', 'try to win', 'watch closely'],
    answer: 2,
    explain: 'To compete is to take part in a contest against other people. The goal is to win.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-011',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COMPLEX',
    choices: ['simple', 'complicated', 'tiny', 'honest'],
    answer: 1,
    explain: 'Complex means made of many parts that connect in tricky ways. Something complex is complicated rather than simple.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-012',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONCLUDE',
    choices: ['begin', 'argue', 'delay', 'finish'],
    answer: 3,
    explain: 'To conclude something is to bring it to an end. A speaker who concludes has finished speaking.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-013',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONFIDENT',
    choices: ['worried', 'sleepy', 'polite', 'sure of yourself'],
    answer: 3,
    explain: 'Confident means believing you can do something well. A confident student is sure of himself before a test.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-014',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONFUSE',
    choices: ['clarify', 'bewilder', 'arrange', 'answer'],
    answer: 1,
    explain: 'To confuse someone is to mix them up so they cannot understand. Bewilder means the same thing, while clarify is the opposite.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-015',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONQUER',
    choices: ['defeat', 'obey', 'share', 'discover'],
    answer: 0,
    explain: 'To conquer is to beat an enemy and take control. That is defeating them.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-016',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONSIDER',
    choices: ['ignore', 'refuse', 'think about', 'forget'],
    answer: 2,
    explain: 'To consider something is to think it over carefully before deciding.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-017',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONSTRUCT',
    choices: ['destroy', 'sketch', 'build', 'measure'],
    answer: 2,
    explain: 'To construct something is to put the pieces together and make it. Workers construct, or build, a bridge.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-018',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONTAIN',
    choices: ['spill', 'weigh', 'open', 'hold inside'],
    answer: 3,
    explain: 'To contain is to have something within. A jar that contains marbles holds them inside.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-019',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONTENT',
    choices: ['satisfied', 'angry', 'wealthy', 'curious'],
    answer: 0,
    explain: 'Content means pleased with what you already have and not wanting more. That is being satisfied.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-020',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONVINCE',
    choices: ['doubt', 'persuade', 'forbid', 'confuse'],
    answer: 1,
    explain: 'To convince someone is to get them to believe or agree with you. Persuade means the same thing.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-021',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COURTEOUS',
    choices: ['clever', 'wealthy', 'shy', 'polite'],
    answer: 3,
    explain: 'Courteous means showing good manners and respect for others. A courteous guest is polite.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-022',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CRAMPED',
    choices: ['crowded', 'airy', 'sturdy', 'filthy'],
    answer: 0,
    explain: 'Cramped means squeezed into a space that is too small. A cramped room feels crowded and tight.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-023',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CRUCIAL',
    choices: ['unusual', 'extremely important', 'harmful', 'inexpensive'],
    answer: 1,
    explain: 'Crucial describes something you absolutely must have for a plan to work. Water is crucial to life.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-024',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CUNNING',
    choices: ['friendly', 'honest', 'sly', 'brave'],
    answer: 2,
    explain: 'Cunning means clever in a sneaky way. A cunning fox is sly about getting what it wants.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-025',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CURIOUS',
    choices: ['bored', 'eager to learn', 'frightened', 'careless'],
    answer: 1,
    explain: 'Curious means wanting to know more and asking lots of questions. A curious child is eager to find things out.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-026',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CHALLENGE',
    choices: ['an easy chore', 'a friendly favor', 'a difficult test', 'a lucky break'],
    answer: 2,
    explain: 'A challenge is something hard that tests what you can do. Climbing a tall mountain is a challenge.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-027',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CALM',
    choices: ['noisy', 'chilly', 'rushed', 'peaceful'],
    answer: 3,
    explain: 'Calm means still and quiet, without any storm or upset. A calm lake is peaceful.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-028',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CLEVER',
    choices: ['smart', 'strong', 'lazy', 'careful'],
    answer: 0,
    explain: 'Clever means quick to learn and good at figuring things out. That is being smart.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-029',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CLING',
    choices: ['hold tightly', 'let go', 'toss aside', 'wave about'],
    answer: 0,
    explain: 'To cling is to grip something and refuse to let go. A koala clings to a branch.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-030',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CLASH',
    choices: ['agree', 'disagree strongly', 'whisper', 'wait quietly'],
    answer: 1,
    explain: 'To clash is to run into conflict with someone. Two people who clash argue instead of agreeing.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-031',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CHEERFUL',
    choices: ['gloomy', 'strict', 'merry', 'tired'],
    answer: 2,
    explain: 'Cheerful means full of happy spirits. A cheerful person is merry and bright.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-032',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CHUCKLE',
    choices: ['shout', 'sob', 'sing loudly', 'laugh quietly'],
    answer: 3,
    explain: 'To chuckle is to laugh in a soft, low way rather than out loud.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-033',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COMMENCE',
    choices: ['finish', 'cancel', 'repeat', 'begin'],
    answer: 3,
    explain: 'Commence means to start. The ceremony will commence, or begin, at noon.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-034',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COAX',
    choices: ['order sharply', 'punish quickly', 'gently persuade', 'ignore completely'],
    answer: 2,
    explain: 'To coax is to talk someone into doing something using kind, patient words instead of force.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-035',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COMMON',
    choices: ['rare', 'ordinary', 'costly', 'fragile'],
    answer: 1,
    explain: 'Common means seen or happening very often. Something common is ordinary, not rare.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-036',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COMPASSION',
    choices: ['sympathy', 'anger', 'greed', 'courage'],
    answer: 0,
    explain: 'Compassion is caring about the pain of another person and wanting to help. Sympathy is that same caring feeling.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-037',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONFESS',
    choices: ['deny', 'admit', 'boast', 'question'],
    answer: 1,
    explain: 'To confess is to own up to something you did wrong. Deny is the opposite of admitting it.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-038',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONFLICT',
    choices: ['a disagreement', 'a celebration', 'a solution', 'a journey'],
    answer: 0,
    explain: 'A conflict is a fight or a clash between people who want different things.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-039',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONSTANT',
    choices: ['brief', 'sudden', 'unchanging', 'rare'],
    answer: 2,
    explain: 'Constant means going on the same way without stopping. A constant hum never changes or pauses.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-040',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONTRAST',
    choices: ['a copy', 'a mixture', 'a promise', 'a difference'],
    answer: 3,
    explain: 'A contrast is a clear difference you notice when two things are put side by side.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-041',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONCERN',
    choices: ['worry', 'delight', 'boredom', 'wealth'],
    answer: 0,
    explain: 'Concern is the uneasy feeling you get when you think something may go wrong. It is a kind of worry.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-042',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CORRECT',
    choices: ['ruin', 'copy', 'doubt', 'fix'],
    answer: 3,
    explain: 'To correct something is to make right what was wrong. A teacher who corrects an answer fixes it.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-043',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'COURAGE',
    choices: ['patience', 'bravery', 'honesty', 'kindness'],
    answer: 1,
    explain: 'Courage is the strength to face something frightening. Another word for it is bravery.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-044',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CROOKED',
    choices: ['smooth', 'level', 'bent', 'narrow'],
    answer: 2,
    explain: 'Crooked means not straight. A crooked path is bent and twisted.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-045',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CRUMBLE',
    choices: ['harden', 'stretch', 'fall to pieces', 'swell'],
    answer: 2,
    explain: 'To crumble is to break into little bits. An old stone wall crumbles as it falls apart.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-046',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CRITICIZE',
    choices: ['praise warmly', 'find fault with', 'listen to', 'copy exactly'],
    answer: 1,
    explain: 'To criticize is to point out what is wrong with something or someone.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-047',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CUSTOM',
    choices: ['a mistake', 'a bargain', 'a warning', 'a tradition'],
    answer: 3,
    explain: 'A custom is something a group of people has done the same way for many years, like a holiday tradition.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-048',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CHAOS',
    choices: ['total disorder', 'deep silence', 'strict order', 'slight delay'],
    answer: 0,
    explain: 'Chaos is complete confusion with nothing under control. It is the opposite of order.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-049',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CHILLY',
    choices: ['humid', 'cool', 'sunny', 'windy'],
    answer: 1,
    explain: 'Chilly means cold enough to make you want a jacket. A chilly morning is cool.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-050',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DARING',
    choices: ['fearful', 'gentle', 'clever', 'bold'],
    answer: 3,
    explain: 'Daring means willing to take risks other people would avoid. A daring rescue is a bold one.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-051',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DAWDLE',
    choices: ['move too slowly', 'run quickly', 'shout loudly', 'trip suddenly'],
    answer: 0,
    explain: 'To dawdle is to waste time by going far more slowly than you should.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-052',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DECAY',
    choices: ['grow', 'freeze', 'rot', 'shine'],
    answer: 2,
    explain: 'To decay is to break down and spoil over time. Fruit left out will decay, or rot.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-053',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DECLINE',
    choices: ['accept', 'begin', 'borrow', 'refuse'],
    answer: 3,
    explain: 'To decline an offer is to turn it down politely, which means to refuse it.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-054',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEDICATE',
    choices: ['waste', 'borrow', 'devote', 'hide'],
    answer: 2,
    explain: 'To dedicate your time is to give it fully to one purpose. Devote means the same thing.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-055',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEFEAT',
    choices: ['beat', 'assist', 'follow', 'join'],
    answer: 0,
    explain: 'To defeat someone is to win against them in a game or battle. That is beating them.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-056',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEFEND',
    choices: ['attack', 'protect', 'abandon', 'ignore'],
    answer: 1,
    explain: 'To defend is to keep something safe from harm. A goalie defends, or protects, the net.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-057',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DELAY',
    choices: ['put off until later', 'finish early', 'cancel forever', 'speed up'],
    answer: 0,
    explain: 'To delay something is to make it happen later than planned. Canceling would end it instead.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-058',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DELICATE',
    choices: ['sturdy', 'easily broken', 'heavy', 'plain'],
    answer: 1,
    explain: 'Delicate means so fine or thin that it breaks with little force. A delicate glass ornament must be handled gently.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-059',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEMOLISH',
    choices: ['repair', 'design', 'measure', 'tear down'],
    answer: 3,
    explain: 'To demolish is to knock something down completely. Crews demolish an old building.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-060',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DENSE',
    choices: ['hollow', 'damp', 'thick', 'shiny'],
    answer: 2,
    explain: 'Dense means packed tightly together. A dense forest is thick with trees.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-061',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DENY',
    choices: ['admit freely', 'ask politely', 'say it is untrue', 'forget quickly'],
    answer: 2,
    explain: 'To deny something is to state that it is not true. It is the opposite of admitting it.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-062',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEPART',
    choices: ['leave', 'arrive', 'stay', 'return'],
    answer: 0,
    explain: 'To depart is to go away from a place. A train that departs leaves the station.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-063',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEPOSIT',
    choices: ['remove', 'place', 'spend', 'borrow'],
    answer: 1,
    explain: 'To deposit something is to set it down or put it somewhere for safekeeping.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-064',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DESCRIBE',
    choices: ['ignore', 'erase', 'measure', 'tell about'],
    answer: 3,
    explain: 'To describe something is to use words to say what it is like.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-065',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DESERTED',
    choices: ['crowded', 'abandoned', 'noisy', 'tidy'],
    answer: 1,
    explain: 'Deserted means everyone has gone away and no one is left. A deserted town has been abandoned.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-066',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DETERMINE',
    choices: ['guess wildly', 'forget', 'find out for certain', 'put off'],
    answer: 2,
    explain: 'To determine something is to settle it for sure, often by checking or measuring. A guess is not certain enough.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-067',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEVISE',
    choices: ['copy', 'destroy', 'borrow', 'invent'],
    answer: 3,
    explain: 'To devise is to think up a new plan or method. Someone who devises a scheme invents it.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-068',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DILIGENT',
    choices: ['hardworking', 'careless', 'cheerful', 'clever'],
    answer: 0,
    explain: 'Diligent means working steadily and carefully until a job is done. A diligent student keeps at it.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-069',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DIM',
    choices: ['bright', 'wide', 'loud', 'faint'],
    answer: 3,
    explain: 'Dim means having very little light. A dim lamp gives off only a faint glow.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-070',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISASTER',
    choices: ['a celebration', 'a terrible event', 'a small mistake', 'a long journey'],
    answer: 1,
    explain: 'A disaster is something that causes great damage or harm, like a flood or an earthquake. It is far worse than a small mistake.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-071',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISCARD',
    choices: ['keep', 'repair', 'throw away', 'collect'],
    answer: 2,
    explain: 'To discard something is to get rid of it because you no longer want it.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-072',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISCOVER',
    choices: ['find', 'lose', 'hide', 'build'],
    answer: 0,
    explain: 'To discover something is to come upon it for the first time. You find what you did not know was there.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-073',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISGUISE',
    choices: ['change the look of', 'show plainly', 'announce loudly', 'sell quickly'],
    answer: 0,
    explain: 'To disguise something is to change how it looks so nobody recognizes it.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-074',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISPUTE',
    choices: ['an agreement', 'a favor', 'a lesson', 'an argument'],
    answer: 3,
    explain: 'A dispute happens when people disagree and argue over something. An agreement is the opposite.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-075',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISTANT',
    choices: ['nearby', 'faraway', 'crowded', 'sudden'],
    answer: 1,
    explain: 'Distant means a long way off. A distant mountain is faraway.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-076',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISTINCT',
    choices: ['blurry', 'similar', 'clearly different', 'very tiny'],
    answer: 2,
    explain: 'Distinct means easy to tell apart from everything else. Two distinct colors do not blend together.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-077',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISTRESS',
    choices: ['comfort', 'laughter', 'great worry', 'patience'],
    answer: 2,
    explain: 'Distress is a feeling of deep pain or trouble. A ship in distress is in serious trouble.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-078',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DRAB',
    choices: ['dull and colorless', 'bright and bold', 'sharp and clear', 'sweet and rich'],
    answer: 0,
    explain: 'Drab describes something plain and faded with no lively color. Gray, drab walls look boring.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-079',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DRENCH',
    choices: ['dry off', 'warm gently', 'sprinkle lightly', 'soak completely'],
    answer: 3,
    explain: 'To drench something is to make it thoroughly wet. A downpour drenches you, while a sprinkle barely dampens you.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-080',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DREARY',
    choices: ['cheerful', 'gloomy', 'busy', 'sudden'],
    answer: 1,
    explain: 'Dreary means dull and depressing, like a long gray rainy day.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-081',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DURABLE',
    choices: ['flimsy', 'long-lasting', 'cheap', 'smooth'],
    answer: 1,
    explain: 'Durable means tough enough to be used for a long time without breaking. Durable boots last for years.',
    difficulty: 2,
  },
  {
    id: 'vc-cd-082',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DWELL',
    choices: ['visit', 'travel', 'live', 'build'],
    answer: 2,
    explain: 'To dwell somewhere is to make your home there. Bats dwell in caves.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-083',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DWINDLE',
    choices: ['grow smaller', 'grow larger', 'freeze solid', 'burst open'],
    answer: 0,
    explain: 'To dwindle is to shrink little by little. Supplies dwindle as they are slowly used up.',
    difficulty: 3,
  },
  {
    id: 'vc-cd-084',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DAMAGE',
    choices: ['polish', 'improve', 'carry', 'harm'],
    answer: 3,
    explain: 'To damage something is to break or hurt it so it no longer works as well.',
    difficulty: 1,
  },
  {
    id: 'vc-cd-085',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEBATE',
    choices: ['agree at once', 'ignore fully', 'argue both sides', 'copy exactly'],
    answer: 2,
    explain: 'To debate is to discuss a question by arguing the reasons for and against it.',
    difficulty: 2,
  },
];
