import type { Question } from '../types';

/**
 * ISEE Lower Level vocabulary (synonyms) - target words beginning with E, F, G, or H.
 * 85 questions. Calibrated for a bright 10-11 year old.
 */
export const VOCAB_EH: Question[] = [
  {
    id: 'vc-eh-001',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EXEMPLARY',
    choices: ['extremely lazy', 'outstandingly good', 'deeply confused', 'quietly rude'],
    answer: 1,
    explain: 'Exemplary means so good that it serves as a model for others to follow.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-002',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FASTIDIOUS',
    choices: ['very relaxed and easygoing', 'deeply forgetful', 'extremely particular about details', 'wildly reckless'],
    answer: 2,
    explain: 'A fastidious person is extremely careful about details and hard to satisfy.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-003',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GALLANT',
    choices: ['clumsy', 'wealthy', 'quiet', 'brave'],
    answer: 3,
    explain: 'Gallant describes someone who acts boldly and politely, the way a knight does. Brave is the closest match.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-004',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HAPHAZARD',
    choices: ['extremely careful', 'perfectly planned', 'remarkably neat', 'disorganized and random'],
    answer: 3,
    explain: 'Haphazard means done without any plan or order, left entirely to chance.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-005',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EARNEST',
    choices: ['sincere', 'joking', 'lazy', 'rude'],
    answer: 0,
    explain: 'Earnest means serious and truly meaning what you say. Sincere describes exactly that.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-006',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FORLORN',
    choices: ['sad and abandoned', 'cheerful and busy', 'angry and loud', 'calm and confident'],
    answer: 0,
    explain: 'Forlorn describes someone who feels sad and alone, as if abandoned.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-007',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRANDIOSE',
    choices: ['extremely modest', 'exaggerated and showy', 'quietly practical', 'deeply humble'],
    answer: 1,
    explain: 'Grandiose describes plans or claims that are far bigger or grander than is reasonable.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-008',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HAMPER',
    choices: ['assist', 'ignore', 'repair', 'hinder'],
    answer: 3,
    explain: 'To hamper something is to get in its way and slow it down. Hinder means the same.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-009',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EDIBLE',
    choices: ['safe to eat', 'fully cooked', 'freshly baked', 'sweet tasting'],
    answer: 0,
    explain: 'Edible means something can be eaten without harming you. It does not have to be cooked or taste good.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-010',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FAMINE',
    choices: ['a flood', 'a crowd', 'a harvest', 'a food shortage'],
    answer: 3,
    explain: 'A famine is a long stretch when there is not enough food, so many people go hungry.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-011',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GARRULOUS',
    choices: ['unusually quiet', 'deeply serious', 'excessively talkative', 'extremely shy'],
    answer: 2,
    explain: 'A garrulous person talks constantly, often about unimportant things.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-012',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HARDY',
    choices: ['stubborn', 'clever', 'tough', 'wealthy'],
    answer: 2,
    explain: 'A hardy plant or person can survive rough, harsh conditions. Tough means able to take that punishment.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-013',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ELEGANT',
    choices: ['messy', 'enormous', 'cheerful', 'graceful'],
    answer: 3,
    explain: 'Elegant means stylish in a simple, beautiful way. Graceful describes that same pleasing look.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-014',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FATIGUE',
    choices: ['tiredness', 'hunger', 'anger', 'courage'],
    answer: 0,
    explain: 'Fatigue is the worn-out feeling that comes after hard work. Tiredness is the plain word for it.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-015',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GENUINE',
    choices: ['costly', 'ancient', 'real', 'fragile'],
    answer: 2,
    explain: 'Genuine means truly what it claims to be, not a fake copy. Something can be real without being costly.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-016',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HARSH',
    choices: ['gentle', 'rough', 'quiet', 'damp'],
    answer: 1,
    explain: 'Harsh means unpleasantly rough or severe, like a harsh voice or harsh winter weather.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-017',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ELUDE',
    choices: ['escape', 'follow', 'forget', 'invite'],
    answer: 0,
    explain: 'To elude someone is to slip away so they cannot catch you. Escape is the closest word.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-018',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FUTILE',
    choices: ['wildly successful', 'extremely simple', 'carefully planned', 'completely pointless'],
    answer: 3,
    explain: 'A futile effort has no chance of succeeding, no matter how hard you try.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-019',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GENIAL',
    choices: ['friendly and warm', 'cold and distant', 'nervous and shy', 'loud and rude'],
    answer: 0,
    explain: 'A genial host makes everyone feel warmly welcomed.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-020',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HASTY',
    choices: ['careful', 'hurried', 'tidy', 'angry'],
    answer: 1,
    explain: 'Hasty means done in a rush. Hurried describes that same speed, usually with mistakes.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-021',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ECCENTRIC',
    choices: ['perfectly ordinary', 'unusual and quirky', 'extremely serious', 'deeply organized'],
    answer: 1,
    explain: 'An eccentric person behaves in an unusual, quirky way that sets them apart from others.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-022',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FRUGAL',
    choices: ['wildly wasteful', 'extremely generous', 'careful with money', 'deeply careless'],
    answer: 2,
    explain: 'A frugal shopper is careful not to waste money and avoids spending more than necessary.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-023',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GLEAM',
    choices: ['shine', 'crack', 'float', 'fade'],
    answer: 0,
    explain: 'To gleam is to give off a soft, bright light. Fading is losing light, the opposite.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-024',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HAUGHTY',
    choices: ['nervous', 'friendly', 'arrogant', 'careless'],
    answer: 2,
    explain: 'A haughty person acts as if they are better than everyone else. Arrogant means the same thing.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-025',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EMERGE',
    choices: ['vanish', 'come out', 'settle down', 'break apart'],
    answer: 1,
    explain: 'To emerge is to come out into view from a hidden place, like a bear leaving its cave.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-026',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FLAMBOYANT',
    choices: ['extremely plain', 'deeply shy', 'carefully quiet', 'strikingly showy'],
    answer: 3,
    explain: 'Flamboyant describes a bold, colorful style meant to attract attention.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-027',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GLIMPSE',
    choices: ['a long stare', 'a loud noise', 'a quick look', 'a bright light'],
    answer: 2,
    explain: 'A glimpse is a brief sight of something before it is out of view again.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-028',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HAVEN',
    choices: ['a safe place', 'a tall tower', 'a narrow path', 'a busy market'],
    answer: 0,
    explain: 'A haven is a shelter where you are protected from harm or trouble.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-029',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ELABORATE',
    choices: ['highly detailed and complex', 'extremely plain', 'quickly finished', 'poorly planned'],
    answer: 0,
    explain: 'An elaborate plan has many carefully worked-out details.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-030',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FLEXIBLE',
    choices: ['bendable', 'sticky', 'heavy', 'hollow'],
    answer: 0,
    explain: 'Something flexible can bend without breaking, like a rubber garden hose.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-031',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GLOOMY',
    choices: ['crowded', 'noisy', 'dark and sad', 'spotless'],
    answer: 2,
    explain: 'Gloomy describes dim, shadowy light or a low, unhappy mood.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-032',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HAZARD',
    choices: ['a reward', 'a danger', 'a rumor', 'a habit'],
    answer: 1,
    explain: 'A hazard is something that could hurt you, such as a wet floor or a loose wire.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-033',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ENDURE',
    choices: ['begin', 'avoid', 'forget', 'put up with'],
    answer: 3,
    explain: 'To endure something is to keep going through it even though it is hard. Avoiding it is the opposite.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-034',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FLOURISH',
    choices: ['wither', 'wander', 'thrive', 'wobble'],
    answer: 2,
    explain: 'To flourish is to grow strong and do very well. Wither, meaning dry up, is its opposite.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-035',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GLOSSY',
    choices: ['shiny', 'rough', 'faded', 'sticky'],
    answer: 0,
    explain: 'A glossy surface is smooth and reflects light, like a brand new magazine cover.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-036',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HINDER',
    choices: ['help along quickly', 'get in the way of', 'calmly ignore', 'warmly welcome'],
    answer: 1,
    explain: 'To hinder something is to slow it down or make it harder for it to happen.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-037',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ENERGETIC',
    choices: ['gloomy', 'clumsy', 'lively', 'patient'],
    answer: 2,
    explain: 'Energetic means full of energy and always on the move. Lively describes that same busy spirit.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-038',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FLUENT',
    choices: ['loud', 'truthful', 'careful', 'smooth speaking'],
    answer: 3,
    explain: 'Someone fluent in a language speaks it easily without stopping to hunt for words.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-039',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GNAW',
    choices: ['swallow', 'chew', 'sniff', 'scratch'],
    answer: 1,
    explain: 'To gnaw is to bite at something over and over, the way a mouse works on a cord.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-040',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HEED',
    choices: ['pay attention to', 'argue with', 'laugh at', 'run from'],
    answer: 0,
    explain: 'To heed a warning is to listen to it carefully and act on it.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-041',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ELUSIVE',
    choices: ['easy to spot', 'extremely heavy', 'hard to catch or find', 'brightly colored'],
    answer: 2,
    explain: 'Something elusive keeps slipping away and is very hard to catch or pin down.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-042',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FICKLE',
    choices: ['wonderfully loyal', 'extremely calm', 'deeply serious', 'constantly changing'],
    answer: 3,
    explain: 'Someone fickle changes their mind or loyalty all the time, so you cannot count on them.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-043',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GORGE',
    choices: ['a wide field', 'a deep canyon', 'a tall hill', 'a small pond'],
    answer: 1,
    explain: 'A gorge is a narrow valley with steep rocky walls, usually carved by a river.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-044',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HESITATE',
    choices: ['hurry', 'shout', 'pause', 'agree'],
    answer: 2,
    explain: 'To hesitate is to stop for a moment because you are unsure what to do.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-045',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EMULATE',
    choices: ['try to copy and equal', 'completely ignore', 'harshly criticize', 'quickly forget'],
    answer: 0,
    explain: 'To emulate someone is to imitate them because you admire them and want to match their success.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-046',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FOND',
    choices: ['affectionate', 'jealous', 'bored', 'strict'],
    answer: 0,
    explain: 'To be fond of something means you like it a lot. Affectionate describes that warm liking.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-047',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRADUAL',
    choices: ['sudden', 'steep', 'slow and steady', 'uneven'],
    answer: 2,
    explain: 'A gradual change happens little by little over time instead of all at once.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-048',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HOARD',
    choices: ['spend', 'stockpile', 'borrow', 'share'],
    answer: 1,
    explain: 'To hoard is to pile up and hide away far more than you need. Sharing is the opposite.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-049',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ENVY',
    choices: ['jealousy', 'sadness', 'pride', 'fear'],
    answer: 0,
    explain: 'Envy is the uncomfortable feeling of wanting what someone else has. Jealousy is the everyday word for it.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-050',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FORBID',
    choices: ['allow', 'ignore', 'prohibit', 'delay'],
    answer: 2,
    explain: 'To forbid something is to order that it must not be done. Allow is its opposite.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-051',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GLIB',
    choices: ['deeply honest', 'smoothly persuasive but insincere', 'extremely nervous', 'painfully shy'],
    answer: 1,
    explain: 'A glib answer sounds smooth and quick but is often insincere or shallow.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-052',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HAPLESS',
    choices: ['extremely lucky', 'deeply confident', 'unlucky and unfortunate', 'wildly successful'],
    answer: 2,
    explain: 'A hapless character keeps having bad luck through no real fault of their own.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-053',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ERECT',
    choices: ['destroy', 'decorate', 'build', 'lean'],
    answer: 2,
    explain: 'To erect something is to put it up or construct it, as in erecting a tent.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-054',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FORSAKE',
    choices: ['abandon', 'rescue', 'remember', 'follow'],
    answer: 0,
    explain: 'To forsake someone is to leave them behind and stop helping them.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-055',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GAUDY',
    choices: ['plain and simple', 'quietly elegant', 'softly colored', 'showy and tasteless'],
    answer: 3,
    explain: 'Gaudy describes something so bright and flashy that it looks tasteless.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-056',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HORIZON',
    choices: ['a mountain top', 'a deep valley', 'a wide road', 'where sky meets land'],
    answer: 3,
    explain: 'The horizon is the faraway line where the earth or sea seems to touch the sky.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-057',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ESSENTIAL',
    choices: ['necessary', 'optional', 'expensive', 'unusual'],
    answer: 0,
    explain: 'Something essential is needed and cannot be left out. Optional means you may skip it.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-058',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FORTUNATE',
    choices: ['wealthy', 'careful', 'lucky', 'cheerful'],
    answer: 2,
    explain: 'Fortunate means good things happened to you by chance. Wealthy is tempting, but it means rich, not lucky.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-059',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRATITUDE',
    choices: ['patience', 'thankfulness', 'courage', 'sorrow'],
    answer: 1,
    explain: 'Gratitude is the feeling of being thankful for something you were given.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-060',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HOSTILE',
    choices: ['nervous', 'crowded', 'tired', 'unfriendly'],
    answer: 3,
    explain: 'Hostile describes someone who behaves like an enemy toward you.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-061',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EVADE',
    choices: ['confront', 'announce', 'avoid', 'repeat'],
    answer: 2,
    explain: 'To evade a question or a person is to dodge them instead of dealing with them. Confront is the opposite.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-062',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FRAGILE',
    choices: ['flexible', 'worthless', 'ancient', 'easily broken'],
    answer: 3,
    explain: 'Fragile things break from the smallest bump, like a thin glass. Flexible things bend instead of breaking.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-063',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRAZE',
    choices: ['feed on grass', 'sleep outdoors', 'run in circles', 'dig a hole'],
    answer: 0,
    explain: 'When cattle graze, they move slowly across a field eating the grass.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-064',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HUDDLE',
    choices: ['spread out', 'crowd together', 'march ahead', 'stand alone'],
    answer: 1,
    explain: 'To huddle is to press close together, often to stay warm or to talk quietly.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-065',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EVIDENT',
    choices: ['hidden', 'doubtful', 'obvious', 'careless'],
    answer: 2,
    explain: 'Something evident is easy to see or understand. Doubtful means uncertain, which is nearly the opposite.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-066',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FRAIL',
    choices: ['weak', 'plump', 'tall', 'stiff'],
    answer: 0,
    explain: 'Frail means thin and easily hurt, without much strength left.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-067',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRIEVE',
    choices: ['celebrate', 'complain', 'forgive', 'mourn'],
    answer: 3,
    explain: 'To grieve is to feel deep sadness over a loss. Complaining is much smaller than that.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-068',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HUMID',
    choices: ['freezing', 'damp', 'windy', 'cloudy'],
    answer: 1,
    explain: 'Humid air holds a lot of moisture, which makes a hot day feel sticky.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-069',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EXAMINE',
    choices: ['ignore', 'repair', 'measure', 'inspect'],
    answer: 3,
    explain: 'To examine something is to look at it closely to learn about it. Measuring is only one small part of that.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-070',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FRANK',
    choices: ['shy', 'angry', 'honest', 'clever'],
    answer: 2,
    explain: 'A frank answer is direct and truthful, even when the truth is uncomfortable.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-071',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRUFF',
    choices: ['cheerful', 'rough voiced', 'well dressed', 'forgetful'],
    answer: 1,
    explain: 'A gruff person speaks in a rough, short, unfriendly way.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-072',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HUMOROUS',
    choices: ['funny', 'serious', 'polite', 'loud'],
    answer: 0,
    explain: 'Something humorous makes people laugh. Serious is its opposite.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-073',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EXCEL',
    choices: ['fail', 'practice', 'do very well', 'give up'],
    answer: 2,
    explain: 'To excel at something is to be much better at it than most people. Practice is how you get there, not the meaning.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-074',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FRANTIC',
    choices: ['calm', 'sleepy', 'stubborn', 'wildly upset'],
    answer: 3,
    explain: 'Frantic describes someone rushing about in a panic. Calm is the opposite.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-075',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRUMBLE',
    choices: ['complain', 'shout', 'giggle', 'agree'],
    answer: 0,
    explain: 'To grumble is to mutter unhappily about something. Shouting is louder and more direct.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-076',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HINDRANCE',
    choices: ['something that blocks progress', 'something that helps quickly', 'a feeling of joy', 'a type of reward'],
    answer: 0,
    explain: 'A hindrance is an obstacle that slows down or blocks progress.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-077',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EXEMPT',
    choices: ['forced to comply', 'excused from a requirement', 'deeply confused', 'wildly excited'],
    answer: 1,
    explain: 'If you are exempt from something, you do not have to do it, unlike everyone else.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-078',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FRIGID',
    choices: ['damp', 'stormy', 'freezing', 'mild'],
    answer: 2,
    explain: 'Frigid means extremely cold, far colder than merely chilly.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-079',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRIEVOUS',
    choices: ['mildly annoying', 'quite comical', 'extremely serious', 'fairly ordinary'],
    answer: 2,
    explain: 'A grievous injury or mistake is very serious and causes great harm or sorrow.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-080',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EXHAUST',
    choices: ['annoy', 'tire out', 'fill up', 'clean off'],
    answer: 1,
    explain: 'To exhaust someone is to use up all their energy until they are completely worn out.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-081',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FRONTIER',
    choices: ['a city center', 'a mountain peak', 'a far border', 'a busy harbor'],
    answer: 2,
    explain: 'A frontier is the outer edge of settled land, the far border where the unknown begins.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-082',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EXTRAVAGANT',
    choices: ['extremely careful with money', 'plain and modest', 'quietly reserved', 'spending far more than needed'],
    answer: 3,
    explain: 'Extravagant spending goes far beyond what is reasonable or necessary.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-083',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FORMIDABLE',
    choices: ['impressively powerful', 'easily defeated', 'quite ordinary', 'remarkably gentle'],
    answer: 0,
    explain: 'A formidable opponent is so strong or skilled that they inspire fear or deep respect.',
    difficulty: 3,
  },
  {
    id: 'vc-eh-084',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EXASPERATE',
    choices: ['calm completely', 'irritate intensely', 'quietly amuse', 'gently persuade'],
    answer: 1,
    explain: 'To exasperate someone is to annoy them so much that they lose patience.',
    difficulty: 2,
  },
  {
    id: 'vc-eh-085',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'EXQUISITE',
    choices: ['fairly plain', 'somewhat rough', 'extremely beautiful and delicate', 'oddly shaped'],
    answer: 2,
    explain: 'Exquisite describes something so beautifully made that it stands out as delicate and fine.',
    difficulty: 2,
  },
];
