import type { Question } from '../types';

export const VOCAB_NR: Question[] = [
  {
    id: 'vc-nr-001',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NARRATE',
    choices: ['hear', 'tell', 'argue', 'forget'],
    answer: 1,
    explain: 'To narrate is to tell a story out loud or in writing. The narrator does the telling, not the listening.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-002',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NEGLECT',
    choices: ['polish', 'ignore', 'guard', 'repair'],
    answer: 1,
    explain: 'To neglect something is to fail to take care of it. When you ignore a plant for weeks, you neglect it.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-003',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NEUTRAL',
    choices: ['strongly loyal', 'deeply upset', 'taking no side', 'clearly wrong'],
    answer: 2,
    explain: 'A neutral person does not favor either side in an argument or a fight.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-004',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NIMBLE',
    choices: ['clumsy', 'quick', 'strong', 'quiet'],
    answer: 1,
    explain: 'Nimble means able to move lightly and easily. A nimble squirrel jumps branch to branch without slipping.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-005',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NOBLE',
    choices: ['wealthy', 'clever', 'honorable', 'ancient'],
    answer: 2,
    explain: 'Noble describes a person of fine character who does what is right. It is about goodness, not money.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-006',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NOTION',
    choices: ['habit', 'idea', 'rule', 'reward'],
    answer: 1,
    explain: 'A notion is a thought or belief you hold in your mind, which is exactly what an idea is.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-007',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NOURISH',
    choices: ['clean', 'warm', 'carry', 'feed'],
    answer: 3,
    explain: 'To nourish is to give the food something needs to grow strong. Feeding is how you nourish a body.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-008',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NUDGE',
    choices: ['push gently', 'shout loudly', 'pull hard', 'stare at'],
    answer: 0,
    explain: 'To nudge is to give a small, soft push, often with an elbow. It is gentle, never forceful.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-009',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NUISANCE',
    choices: ['bargain', 'blessing', 'bother', 'beginner'],
    answer: 2,
    explain: 'A nuisance is something annoying that keeps causing trouble, so it is a bother.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-010',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NUMEROUS',
    choices: ['many', 'silent', 'narrow', 'recent'],
    answer: 0,
    explain: 'Numerous means there is a large number of something. Many says the same thing.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-011',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OATH',
    choices: ['question', 'warning', 'mistake', 'solemn promise'],
    answer: 3,
    explain: 'An oath is a serious vow made in front of others, like swearing in court to tell the truth.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-012',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OBEDIENT',
    choices: ['stubborn', 'cheerful', 'well behaved', 'forgetful'],
    answer: 2,
    explain: 'An obedient person or pet does what they are told, which is what being well behaved means.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-013',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OBLIGE',
    choices: ['require', 'refuse', 'forget', 'delay'],
    answer: 0,
    explain: 'To oblige someone is to make them do something. If rain obliges you to stay inside, it requires you to.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-014',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OBSCURE',
    choices: ['popular', 'famous', 'bright', 'unclear'],
    answer: 3,
    explain: 'Obscure means hard to see or hard to understand. Something obscure is not clear at all.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-015',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OBSERVE',
    choices: ['hide', 'watch', 'shout', 'build'],
    answer: 1,
    explain: 'To observe is to look at something carefully. Watching closely is observing.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-016',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OBTAIN',
    choices: ['get', 'lose', 'lend', 'break'],
    answer: 0,
    explain: 'To obtain something is to come to have it. In plain words, you get it.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-017',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OBVIOUS',
    choices: ['hard to find', 'deeply hidden', 'plain to see', 'oddly shaped'],
    answer: 2,
    explain: 'Something obvious is so clear that anyone would notice it right away.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-018',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OCCUPY',
    choices: ['empty', 'sell', 'clean', 'fill'],
    answer: 3,
    explain: 'To occupy a space is to take it up or live in it. Boxes that occupy a closet fill it.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-019',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ODOR',
    choices: ['sound', 'smell', 'shape', 'shadow'],
    answer: 1,
    explain: 'An odor is a smell, especially a strong one you notice in the air.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-020',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OFFEND',
    choices: ['insult', 'impress', 'invite', 'ignore'],
    answer: 0,
    explain: 'To offend someone is to hurt their feelings by what you say or do, so insulting them offends them.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-021',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OMIT',
    choices: ['add in', 'write down', 'leave out', 'look over'],
    answer: 2,
    explain: 'To omit something is to not include it. If you omit a name from a list, you leave it out.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-022',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OPPONENT',
    choices: ['teammate', 'enemy', 'coach', 'fan'],
    answer: 1,
    explain: 'An opponent is whoever you play or argue against. They stand on the other side, like an enemy in a contest.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-023',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OPPOSE',
    choices: ['support', 'join', 'allow', 'resist'],
    answer: 3,
    explain: 'To oppose something is to be against it and try to stop it. Resisting is acting against it.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-024',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OPTIMISTIC',
    choices: ['hopeful', 'gloomy', 'careless', 'curious'],
    answer: 0,
    explain: 'An optimistic person expects good things to happen, so they have a hopeful outlook.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-025',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ORDEAL',
    choices: ['holiday', 'hardship', 'habit', 'hobby'],
    answer: 1,
    explain: 'An ordeal is a very hard or painful experience you have to get through.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-026',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ORIGIN',
    choices: ['ending', 'middle', 'purpose', 'beginning'],
    answer: 3,
    explain: 'The origin of something is the place or moment where it started.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-027',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OUTCOME',
    choices: ['reason', 'plan', 'result', 'choice'],
    answer: 2,
    explain: 'The outcome is what finally happens at the end. How a game turns out is its outcome.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-028',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OVERWHELM',
    choices: ['overpower', 'encourage', 'delay', 'confuse'],
    answer: 0,
    explain: 'To overwhelm is to hit someone with far more than they can handle. A huge wave can overpower a swimmer.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-029',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PACIFY',
    choices: ['annoy', 'excite', 'scold', 'calm'],
    answer: 3,
    explain: 'To pacify someone is to bring them back to peace after they were upset.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-030',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PACT',
    choices: ['argument', 'agreement', 'accident', 'announcement'],
    answer: 1,
    explain: 'A pact is a deal two sides make and promise to keep, so it is an agreement.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-031',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PARCHED',
    choices: ['very dry', 'slightly wet', 'freshly cut', 'deeply buried'],
    answer: 0,
    explain: 'Parched means dried out by heat or thirst. Parched ground has had no rain for a long time.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-032',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PARDON',
    choices: ['punish', 'accuse', 'forgive', 'warn'],
    answer: 2,
    explain: 'To pardon someone is to excuse what they did wrong instead of punishing them.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-033',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PARTIAL',
    choices: ['perfect', 'incomplete', 'enormous', 'equal'],
    answer: 1,
    explain: 'Partial means only part of the whole. A partial answer is not finished yet.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-034',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PAUSE',
    choices: ['speed up', 'keep going', 'start over', 'stop briefly'],
    answer: 3,
    explain: 'To pause is to stop for a short moment and then continue.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-035',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PEER',
    choices: ['look closely', 'shout out', 'walk away', 'sit down'],
    answer: 0,
    explain: 'To peer is to strain your eyes at something you cannot see well, like peering into a dark room.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-036',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PERIL',
    choices: ['comfort', 'delay', 'danger', 'journey'],
    answer: 2,
    explain: 'Peril means serious danger, the kind that could get someone badly hurt.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-037',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PERMIT',
    choices: ['forbid', 'forget', 'force', 'allow'],
    answer: 3,
    explain: 'To permit something is to say yes to it. When you permit a dog inside, you allow it.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-038',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PERSIST',
    choices: ['give up', 'keep trying', 'slow down', 'start over'],
    answer: 1,
    explain: 'To persist is to keep going even when it is hard, instead of quitting.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-039',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PERSUADE',
    choices: ['convince', 'confuse', 'command', 'copy'],
    answer: 0,
    explain: 'To persuade someone is to talk them into agreeing with you, not to order them.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-040',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PESTER',
    choices: ['praise', 'help', 'annoy', 'follow'],
    answer: 2,
    explain: 'To pester is to bother someone over and over until they get irritated.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-041',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PIERCE',
    choices: ['bend over', 'stab through', 'wrap around', 'wear down'],
    answer: 1,
    explain: 'To pierce something is to make a hole by pushing sharply through it.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-042',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PLACID',
    choices: ['stormy', 'crowded', 'noisy', 'peaceful'],
    answer: 3,
    explain: 'Placid means calm and still, with nothing stirring. A placid lake has no waves.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-043',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PLEAD',
    choices: ['boast', 'order', 'beg', 'refuse'],
    answer: 2,
    explain: 'To plead is to ask for something in a desperate way, so it means to beg.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-044',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PLEDGE',
    choices: ['promise', 'guess', 'doubt', 'trade'],
    answer: 0,
    explain: 'To pledge is to give your word that you will do something, so it means to promise.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-045',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PLENTIFUL',
    choices: ['hard to find', 'nearly gone', 'very costly', 'more than enough'],
    answer: 3,
    explain: 'Plentiful means there is a large supply, so nobody has to go without.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-046',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PLUNGE',
    choices: ['float', 'dive', 'climb', 'crawl'],
    answer: 1,
    explain: 'To plunge is to drop or jump suddenly downward, the way you dive into a pool.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-047',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'POISED',
    choices: ['balanced and ready', 'tired and slow', 'angry and loud', 'lost and confused'],
    answer: 0,
    explain: 'Someone poised holds themselves steady and under control. A cat poised to leap is set and balanced.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-048',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PONDER',
    choices: ['forget about', 'laugh at', 'think about', 'write down'],
    answer: 2,
    explain: 'To ponder is to turn something over slowly and carefully in your mind before deciding.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-049',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PORTION',
    choices: ['whole', 'part', 'pile', 'plate'],
    answer: 1,
    explain: 'A portion is one piece of something bigger, so it means a part.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-050',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'POSTPONE',
    choices: ['cancel', 'hurry', 'repeat', 'delay'],
    answer: 3,
    explain: 'To postpone something is to move it to a later time. It still happens, just not yet.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-051',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PRECISE',
    choices: ['rough', 'wide', 'exact', 'strange'],
    answer: 2,
    explain: 'Precise means right down to the smallest detail, with nothing guessed.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-052',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PREDICT',
    choices: ['guess ahead of time', 'look back at', 'write down', 'ask about'],
    answer: 0,
    explain: 'To predict is to say what you think will happen before it happens.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-053',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PRESERVE',
    choices: ['throw out', 'keep safe', 'use up', 'give away'],
    answer: 1,
    explain: 'To preserve something is to guard its good condition so it lasts a long time.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-054',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PREVENT',
    choices: ['start', 'allow', 'cause', 'stop'],
    answer: 3,
    explain: 'To prevent something is to keep it from happening at all.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-055',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PREVIOUS',
    choices: ['earlier', 'final', 'current', 'future'],
    answer: 0,
    explain: 'Previous means coming before this one in time. The previous year is the year that came before.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-056',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PRIVILEGE',
    choices: ['strict rule', 'fair warning', 'special right', 'common chore'],
    answer: 2,
    explain: 'A privilege is an advantage granted to some people and not to everyone.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-057',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PROBABLE',
    choices: ['impossible', 'likely', 'certain', 'unusual'],
    answer: 1,
    explain: 'Probable means something will most likely happen, though it is not guaranteed.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-058',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PROCEED',
    choices: ['pause', 'return', 'refuse', 'continue'],
    answer: 3,
    explain: 'To proceed is to move forward or carry on with what you were doing.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-059',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PROSPER',
    choices: ['fail', 'shrink', 'thrive', 'wander'],
    answer: 2,
    explain: 'To prosper is to do very well and grow successful, the way a healthy business thrives.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-060',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PROTEST',
    choices: ['complain', 'agree', 'obey', 'ignore'],
    answer: 0,
    explain: 'To protest is to speak up strongly against something you believe is wrong.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-061',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'QUARREL',
    choices: ['agree', 'whisper', 'share', 'argue'],
    answer: 3,
    explain: 'To quarrel is to have an angry disagreement with someone.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-062',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'QUENCH',
    choices: ['start up', 'put out', 'stir up', 'build up'],
    answer: 1,
    explain: 'To quench a fire is to put it out. Quenching thirst works the same way, ending it with water.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-063',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'QUERY',
    choices: ['question', 'answer', 'command', 'reply'],
    answer: 0,
    explain: 'A query is what you ask when you want information, not what you get back.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-064',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'QUIVER',
    choices: ['stiffen', 'shout', 'tremble', 'sink'],
    answer: 2,
    explain: 'To quiver is to shake with small quick movements, the way you tremble when cold or scared.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-065',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RADIANT',
    choices: ['dull', 'damp', 'narrow', 'shining'],
    answer: 3,
    explain: 'Radiant means giving off bright light or glowing with warmth.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-066',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RAPID',
    choices: ['fast', 'loud', 'wide', 'late'],
    answer: 0,
    explain: 'Rapid means happening very quickly.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-067',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RARE',
    choices: ['ordinary', 'uncommon', 'tiny', 'ancient'],
    answer: 1,
    explain: 'Something rare is hardly ever seen or found because so little of it exists.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-068',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'REALIZE',
    choices: ['forget', 'doubt', 'understand', 'explain'],
    answer: 2,
    explain: 'To realize something is to suddenly become aware of it, so you finally understand it.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-069',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'REBEL',
    choices: ['resist authority', 'follow orders', 'ask politely', 'stay silent'],
    answer: 0,
    explain: 'To rebel is to refuse to obey the people in charge and fight against their rules.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-070',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RECALL',
    choices: ['forget', 'repeat', 'record', 'remember'],
    answer: 3,
    explain: 'To recall something is to bring it back into your mind.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-071',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RECITE',
    choices: ['read silently', 'say aloud from memory', 'write neatly', 'listen closely'],
    answer: 1,
    explain: 'To recite is to repeat out loud something you learned by heart, like a poem.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-072',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RECKLESS',
    choices: ['cautious', 'cheerful', 'careless', 'clumsy'],
    answer: 2,
    explain: 'Reckless means acting without thinking about the danger.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-073',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'REFUSE',
    choices: ['say no', 'agree', 'request', 'delay'],
    answer: 0,
    explain: 'To refuse is to turn something down when it is offered or asked of you.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-074',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'REGRET',
    choices: ['feel proud', 'feel sorry', 'feel eager', 'feel bored'],
    answer: 1,
    explain: 'To regret something is to wish you had not done it because it makes you feel bad.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-075',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RELIABLE',
    choices: ['clever', 'wealthy', 'friendly', 'trustworthy'],
    answer: 3,
    explain: 'Someone reliable can be counted on to do what they said they would do.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-076',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RELUCTANT',
    choices: ['eager', 'ready', 'unwilling', 'curious'],
    answer: 2,
    explain: 'A reluctant person does not really want to do something, even if they end up doing it.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-077',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'REMOTE',
    choices: ['far away', 'crowded', 'nearby', 'narrow'],
    answer: 0,
    explain: 'Remote means far off and hard to reach, like a cabin deep in the mountains.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-078',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RESTORE',
    choices: ['throw out', 'bring back', 'break apart', 'give up'],
    answer: 1,
    explain: 'To restore something is to return it to the way it was before, like fixing up an old car.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-079',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RETREAT',
    choices: ['charge ahead', 'stand still', 'pull back', 'spread out'],
    answer: 2,
    explain: 'To retreat is to move back and away, especially from danger or a losing fight.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-080',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'REVEAL',
    choices: ['hide', 'cover', 'deny', 'show'],
    answer: 3,
    explain: 'To reveal something is to uncover it so others can see or know it.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-081',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RIDICULE',
    choices: ['make fun of', 'praise loudly', 'look up to', 'argue with'],
    answer: 0,
    explain: 'To ridicule someone is to laugh at them in a mean way to make them look foolish.',
    difficulty: 3,
  },
  {
    id: 'vc-nr-082',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RIVAL',
    choices: ['partner', 'helper', 'competitor', 'stranger'],
    answer: 2,
    explain: 'A rival is someone trying to beat you at the very thing you want to win.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-083',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ROAM',
    choices: ['rush', 'wander', 'rest', 'return'],
    answer: 1,
    explain: 'To roam is to move around freely with no set path or destination.',
    difficulty: 1,
  },
  {
    id: 'vc-nr-084',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RUGGED',
    choices: ['smooth', 'shiny', 'soft', 'rough'],
    answer: 3,
    explain: 'Rugged means uneven and tough, like rocky ground that is hard to walk across.',
    difficulty: 2,
  },
  {
    id: 'vc-nr-085',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RUTHLESS',
    choices: ['without pity', 'full of kindness', 'easily scared', 'deeply confused'],
    answer: 0,
    explain: 'A ruthless person shows no mercy and does not care who gets hurt.',
    difficulty: 3,
  },
];
