'use client';

import { useEffect, useRef } from 'react';
import { SPEED_SCALE } from '@/lib/difficulty';
import type { GameCanvasProps } from '@/lib/games';
import { playSound } from '@/lib/sound';
import { useCanvasGame } from '@/lib/useCanvasGame';

export const LANES = 3;
export function clampLane(lane: number) { return Math.max(0, Math.min(LANES - 1, lane)); }
export function obstacleHits(playerLane: number, obstacleLane: number, y: number) { return playerLane === obstacleLane && y > 0.76 && y < 0.94; }
type Thing={lane:number;y:number;kind:'obstacle'|'house'}; type State={lane:number;things:Thing[];lives:number;score:number;deliveries:number;level:number;time:number;spawn:number;notice:string;inv:number};
function fresh():State{return{lane:1,things:[],lives:3,score:0,deliveries:0,level:1,time:0,spawn:.8,notice:'Deliver papers to the glowing houses!',inv:0};}
export default function PaperRoute({paused,input,api,restartToken,difficulty,controlsInset}:GameCanvasProps){const ref=useRef(fresh());useEffect(()=>{ref.current=fresh();},[restartToken]);const {canvasRef}=useCanvasGame({active:!paused,step:(ctx,dt,cw,ch)=>{const s=ref.current,h=Math.max(160,ch-controlsInset);s.time+=dt;s.inv=Math.max(0,s.inv-dt);const tap=input.consumeTap();if(tap==='left')s.lane=clampLane(s.lane-1);if(tap==='right')s.lane=clampLane(s.lane+1);if(input.pointerDown&&input.pointerX!==null)s.lane=clampLane(Math.floor(input.pointerX*LANES));s.spawn-=dt;if(s.spawn<=0){s.spawn=.72/(SPEED_SCALE[difficulty]*(1+s.level*.06));const lane=Math.floor((s.time*17+s.things.length*7)%LANES);s.things.push({lane,y:-.15,kind:Math.floor(s.time*5)%3===0?'house':'obstacle'});}for(const t of s.things)t.y+=dt*(.34+s.level*.025)*SPEED_SCALE[difficulty];for(const t of s.things){if(t.kind==='house'&&t.y>.72&&t.y<.77&&t.lane===s.lane){t.y=2;s.deliveries++;s.score+=10;api.addScore(10);s.notice='Delivered!';playSound('coin');if(s.deliveries%8===0){s.level++;api.requestGate(`Paper Route level ${s.level-1} delivered!`);}}if(t.kind==='obstacle'&&s.inv<=0&&obstacleHits(s.lane,t.lane,t.y)){t.y=2;s.lives--;s.inv=1;s.notice='Watch out!';playSound('wrong');if(s.lives<=0){api.died('Your route got too bumpy');ref.current=fresh();}}}s.things=s.things.filter(t=>t.y<1.15);draw(ctx,s,cw,ch,h);}});return <canvas ref={canvasRef} className="absolute inset-0 h-full w-full touch-none"/>;}
function draw(ctx:CanvasRenderingContext2D,s:State,cw:number,ch:number,h:number){ctx.fillStyle='#86d4ef';ctx.fillRect(0,0,cw,ch);ctx.fillStyle='#7dc66b';ctx.fillRect(0,h*.12,cw,h*.88);const roadX=cw*.14,roadW=cw*.72;ctx.fillStyle='#4d5264';ctx.fillRect(roadX,0,roadW,h);ctx.strokeStyle='rgba(255,245,185,.8)';ctx.lineWidth=3;ctx.setLineDash([16,14]);for(let i=1;i<LANES;i++){ctx.beginPath();ctx.moveTo(roadX+roadW*i/LANES,0);ctx.lineTo(roadX+roadW*i/LANES,h);ctx.stroke();}ctx.setLineDash([]);for(const t of s.things){const x=roadX+roadW*(t.lane+.5)/LANES,y=t.y*h;if(t.kind==='house'){ctx.fillStyle='#ffd66d';ctx.fillRect(x-22,y-18,44,34);ctx.fillStyle='#e86365';ctx.beginPath();ctx.moveTo(x-27,y-18);ctx.lineTo(x,y-40);ctx.lineTo(x+27,y-18);ctx.fill();}else{ctx.fillStyle='#ff866d';ctx.beginPath();ctx.arc(x,y,17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff1c5';ctx.fillRect(x-9,y-3,18,7);}}const px=roadX+roadW*(s.lane+.5)/LANES,py=h*.85;if(!(s.inv>0&&Math.floor(s.time*12)%2===0)){ctx.fillStyle='#5b86ee';ctx.fillRect(px-13,py-20,26,30);ctx.fillStyle='#fff0af';ctx.beginPath();ctx.arc(px,py-27,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(px+12,py-9,17,8);}ctx.fillStyle='rgba(17,40,72,.8)';ctx.roundRect(10,10,cw-20,34,12);ctx.fill();ctx.fillStyle='#fff9d0';ctx.font='800 14px system-ui';ctx.fillText(`LEVEL ${s.level}  SCORE ${s.score}`,20,32);ctx.textAlign='right';ctx.fillText('♥'.repeat(s.lives),cw-20,32);ctx.textAlign='center';ctx.font='800 17px system-ui';ctx.fillText(s.notice,cw/2,h*.09);ctx.textAlign='left';}
