'use client';

import { useEffect, useRef } from 'react';
import { SPEED_SCALE } from '@/lib/difficulty';
import type { Direction } from '@/lib/input';
import type { GameCanvasProps } from '@/lib/games';
import { playSound } from '@/lib/sound';
import { useCanvasGame } from '@/lib/useCanvasGame';

export const PYRAMID_ROWS=5; export function tileIndex(r:number,c:number){return r*(r+1)/2+c;} export function hop(r:number,c:number,d:Direction){if(d==='left')return{r:r+1,c:c};if(d==='right')return{r:r+1,c:c+1};if(d==='up')return r>0?{r:r-1,c:Math.max(0,c-1)}:null;return r>0?{r:r-1,c:Math.min(r-1,c)}:null;} export function complete(tiles:number[]){return tiles.every(v=>v>0);}
type State={r:number;c:number;tiles:number[];level:number;score:number;lives:number;time:number;bug:{r:number;c:number;clock:number};message:string}; function fresh():State{return{r:0,c:0,tiles:Array(15).fill(0),level:1,score:0,lives:3,time:0,bug:{r:4,c:2,clock:0},message:'Hop on every jewel tile!'};}
export default function PyramidHop({paused,input,api,restartToken,difficulty,controlsInset}:GameCanvasProps){const ref=useRef(fresh());useEffect(()=>{ref.current=fresh();},[restartToken]);const {canvasRef}=useCanvasGame({active:!paused,step:(ctx,dt,cw,ch)=>{const s=ref.current,h=Math.max(160,ch-controlsInset);s.time+=dt;s.bug.clock+=dt*SPEED_SCALE[difficulty];let d=input.consumeTap();if(!d&&input.consumePointerPress()&&input.pointerX!==null&&input.pointerY!==null)d=input.pointerX<.5?(input.pointerY<.5?'up':'left'):(input.pointerY<.5?'up':'right');if(d){const n=hop(s.r,s.c,d);if(n){s.r=n.r;s.c=n.c;const i=tileIndex(s.r,s.c);if(!s.tiles[i]){s.tiles[i]=1;s.score+=5;api.addScore(5);playSound('coin');}if(complete(s.tiles)){s.level++;s.tiles=Array(15).fill(0);s.r=0;s.c=0;s.message=`Pyramid ${s.level-1} complete!`;api.requestGate(`Pyramid Hop level ${s.level-1} cleared`);}}}if(s.bug.clock>1.25/Math.max(1,s.level*.16)*1/SPEED_SCALE[difficulty]){s.bug.clock=0;const opts:[number,number][]=[[s.bug.r>0?s.bug.r-1:s.bug.r,Math.max(0,s.bug.c-1)],[Math.min(4,s.bug.r+1),s.bug.c]];const n=opts[Math.floor(s.time*3)%opts.length];s.bug={r:n[0],c:Math.min(n[1],n[0]),clock:0};}if(s.r===s.bug.r&&s.c===s.bug.c){s.lives--;s.r=0;s.c=0;s.message='A dust bug bumped you!';playSound('wrong');if(s.lives<=0){api.died('The pyramid bugs caught you');ref.current=fresh();}}draw(ctx,s,cw,ch,h);}});return <canvas ref={canvasRef} className="absolute inset-0 h-full w-full touch-none"/>;}
function draw(ctx:CanvasRenderingContext2D,s:State,cw:number,ch:number,h:number){const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#433372');bg.addColorStop(1,'#f19b72');ctx.fillStyle=bg;ctx.fillRect(0,0,cw,ch);const size=Math.min(cw/7,h/8),cx=cw/2,top=h*.17;for(let r=0;r<PYRAMID_ROWS;r++)for(let c=0;c<=r;c++){const x=cx+(c-r/2)*size,y=top+r*size*.72,i=tileIndex(r,c);ctx.fillStyle=s.tiles[i]?'#6ee3c1':'#4387c8';ctx.beginPath();ctx.moveTo(x,y-size*.35);ctx.lineTo(x+size*.48,y);ctx.lineTo(x,y+size*.35);ctx.lineTo(x-size*.48,y);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.55)';ctx.stroke();if(s.r===r&&s.c===c){ctx.fillStyle='#fff3a5';ctx.beginPath();ctx.arc(x,y-size*.14,size*.18,0,Math.PI*2);ctx.fill();}if(s.bug.r===r&&s.bug.c===c){ctx.fillStyle='#572e54';ctx.beginPath();ctx.arc(x,y+size*.09,size*.15,0,Math.PI*2);ctx.fill();}}ctx.fillStyle='rgba(20,17,62,.72)';ctx.roundRect(10,10,cw-20,35,12);ctx.fill();ctx.fillStyle='#fff6cf';ctx.font='800 14px system-ui';ctx.fillText(`LEVEL ${s.level}  SCORE ${s.score}`,20,32);ctx.textAlign='right';ctx.fillText('♥'.repeat(s.lives),cw-20,32);ctx.textAlign='center';ctx.font='800 17px system-ui';ctx.fillText(s.message,cw/2,h*.1);ctx.textAlign='left';}
