import type { Question } from './types';

/**
 * ISEE Middle and Upper vocabulary generated independently from the
 * protected Lower source, while allowing appropriate headword overlap.
 */
type VocabularyEntry = readonly [word: string, meaning: string, gloss: string, pos: string];

function buildVocabularyBank(
  prefix: string,
  difficulty: 1 | 2 | 3,
  entries: readonly VocabularyEntry[],
): Question[] {
  return entries.map((entry, index) => {
    const [word, correct, gloss, pos] = entry;
    const distractors: string[] = [];
    for (let jump = 1; jump <= entries.length && distractors.length < 3; jump += 1) {
      const candidate = entries[(index + jump * 47) % entries.length];
      if (candidate[3] === pos && candidate[1] !== correct && !distractors.includes(candidate[1])) {
        distractors.push(candidate[1]);
      }
    }
    for (let jump = 1; jump <= entries.length && distractors.length < 3; jump += 1) {
      const candidate = entries[(index + jump * 53) % entries.length];
      if (candidate[1] !== correct && !distractors.includes(candidate[1])) {
        distractors.push(candidate[1]);
      }
    }
    const answer = (index % 4) as 0 | 1 | 2 | 3;
    const choices = [...distractors];
    choices.splice(answer, 0, correct);
    return {
      id: `${prefix}-${String(index + 1).padStart(3, '0')}`,
      subject: 'verbal',
      kind: 'synonym',
      topic: 'level-specific vocabulary',
      prompt: word.toUpperCase(),
      choices,
      answer,
      explain: `“${word}” means “${correct}.” In this sense: ${gloss}.`,
      difficulty,
    };
  });
}

const ISEE_MIDDLE_ENTRIES: readonly VocabularyEntry[] = [
  ["statistic", "a datum that can be represented numerically", "a datum that can be represented numerically", "n"],
  ["subordinate", "subsidiary", "an assistant subject to the authority or control of another", "n"],
  ["contraction", "compression", "the process or result of becoming smaller or pressed together", "n"],
  ["rewrite", "write differently", "write differently", "v"],
  ["revise", "make revisions in", "make revisions in", "v"],
  ["compute", "figure", "make a mathematical calculation or computation", "v"],
  ["correspond", "check", "be compatible, similar or consistent", "v"],
  ["equip", "fit", "provide with (something) usually for a specific purpose", "v"],
  ["devote", "give", "give entirely to a specific person, activity, or cause", "v"],
  ["fragment", "shard", "a broken piece of a brittle artifact", "n"],
  ["adjective", "the word class that qualifies nouns", "the word class that qualifies nouns", "n"],
  ["capitalize", "draw advantages from", "draw advantages from", "v"],
  ["classmate", "schoolmate", "an acquaintance that you go to school with", "n"],
  ["instruct", "learn", "impart skills or knowledge to", "v"],
  ["informative", "illuminating", "tending to increase knowledge or dissipate ignorance", "a"],
  ["coherent", "ordered", "marked by an orderly, logical, and aesthetically consistent relation of parts", "a"],
  ["injure", "wound", "cause injuries or bodily harm to", "v"],
  ["approximate", "be close or similar", "be close or similar", "v"],
  ["assemble", "piece", "create by putting components or members together", "v"],
  ["incidence", "the relative frequency of occurrence of something", "the relative frequency of occurrence of something", "n"],
  ["guideline", "guidepost", "a rule or principle that provides guidance to appropriate behavior", "n"],
  ["assign", "delegate", "give an assignment to (a person) to a post, or assign a task to (a person)", "v"],
  ["reside", "shack", "make one's home in a particular place or community", "v"],
  ["sensory", "sensorial", "involving or derived from the senses", "a"],
  ["illustrate", "instance", "clarify by giving an example of", "v"],
  ["confer", "consult", "have a conference in order to talk something over", "v"],
  ["possessive", "genitive", "serving to express or indicate possession", "a"],
  ["singular", "remarkable", "unusual or striking", "a"],
  ["infer", "derive", "reason by deduction", "v"],
  ["attach", "cause to be attached", "cause to be attached", "v"],
  ["vivid", "graphic", "evoking lifelike images within the mind", "a"],
  ["complement", "make complete or perfect", "make complete or perfect", "v"],
  ["definite", "precise", "precise", "a"],
  ["specify", "condition", "specify as a condition or requirement in a contract or agreement", "v"],
  ["modify", "make less severe or harsh or extreme", "make less severe or harsh or extreme", "v"],
  ["accompany", "go or travel along with", "go or travel along with", "v"],
  ["interpret", "see", "make sense of", "v"],
  ["coordinate", "organize", "bring order and organization to", "v"],
  ["automate", "make automatic or control or operate automatically", "make automatic or control or operate automatically", "v"],
  ["imply", "connote", "express or state indirectly", "v"],
  ["unify", "unite", "become one", "v"],
  ["analyze", "dissect", "make a mathematical, chemical, or grammatical analysis of", "v"],
  ["clarify", "elucidate", "make clear and (more) comprehensible", "v"],
  ["constitute", "be", "form or compose", "v"],
  ["convene", "meet formally", "meet formally", "v"],
  ["consult", "get or ask advice from", "get or ask advice from", "v"],
  ["consume", "down", "eat immoderately", "v"],
  ["consequent", "accompanying", "following or accompanying as a consequence", "a"],
  ["conclude", "reason", "decide by reasoning", "v"],
  ["catalog", "a complete list of things", "a complete list of things", "n"],
  ["verbal", "communicated in the form of words", "communicated in the form of words", "a"],
  ["negate", "contradict", "be in contradiction with", "v"],
  ["underline", "emphasize", "give extra weight to (a communication)", "v"],
  ["conjunction", "coincidence", "the temporal property of two things happening at the same time", "n"],
  ["occupy", "busy", "keep busy with", "v"],
  ["consist", "lie", "originate (in)", "v"],
  ["locate", "discover the location of", "discover the location of", "v"],
  ["tense", "strain", "become stretched or tense or taut", "v"],
  ["adapt", "accommodate", "make fit for, or change to suit a new purpose", "v"],
  ["construct", "make", "make by combining materials and parts", "v"],
  ["clause", "article", "a separate section of a legal document (as a statute or contract or will)", "n"],
  ["evident", "plain", "clearly revealed to the mind or the senses or judgment", "a"],
  ["evaluate", "value", "evaluate or estimate the nature, quality, ability, extent, or significance of", "v"],
  ["insert", "enter", "put or introduce into something", "v"],
  ["voluntary", "of your own free will or design", "of your own free will or design", "a"],
  ["abandon", "forsake, leave behind", "forsake, leave behind", "v"],
  ["paragraph", "divide into paragraphs, as of text", "divide into paragraphs, as of text", "v"],
  ["passive", "inactive", "lacking in energy or will", "a"],
  ["enhance", "raise", "increase", "v"],
  ["likewise", "similarly", "in like or similar manner", "r"],
  ["precede", "forgo", "be earlier in time", "v"],
  ["adequate", "equal", "having the requisite qualities or resources to meet a task", "a"],
  ["detect", "find", "discover or determine the existence, presence, or fact of", "v"],
  ["ignorant", "unlearned", "uneducated in general", "a"],
  ["thesis", "dissertation", "a treatise advancing a new point of view resulting from research", "n"],
  ["predicate", "make the (grammatical) predicate in a proposition", "make the (grammatical) predicate in a proposition", "v"],
  ["adjust", "set", "alter or regulate so as to achieve accuracy or conform to a standard", "v"],
  ["concentrate", "make denser, stronger, or purer", "make denser, stronger, or purer", "v"],
  ["predict", "call", "make a prediction about", "v"],
  ["exclaim", "cry", "utter aloud", "v"],
  ["publish", "print", "put into print", "v"],
  ["narrate", "provide commentary for a film, for example", "provide commentary for a film, for example", "v"],
  ["superlative", "an exaggerated expression (usually of praise)", "an exaggerated expression (usually of praise)", "n"],
  ["flexible", "capable of being changed", "capable of being changed", "a"],
  ["precise", "sharply exact or accurate or delimited", "sharply exact or accurate or delimited", "a"],
  ["abstract", "existing only in the mind", "existing only in the mind", "a"],
  ["blank", "white", "not written or printed on", "a"],
  ["lecture", "talk", "a speech that is open to the public", "n"],
  ["apostrophe", "address to an absent or imaginary person", "address to an absent or imaginary person", "n"],
  ["eliminate", "extinguish", "terminate, end, or take out", "v"],
  ["workshop", "shop", "small workplace where handcrafts or manufacturing are done", "n"],
  ["exhibit", "show an attribute, property, knowledge, or skill", "show an attribute, property, knowledge, or skill", "v"],
  ["react", "respond", "show a response or a reaction to something", "v"],
  ["resolve", "decide", "bring to an end", "v"],
  ["substitute", "exchange", "put in the place of another", "v"],
  ["compound", "deepen", "make more intense, stronger, or more marked", "v"],
  ["emphasis", "accent", "special importance or significance", "n"],
  ["insight", "clear or deep perception of a situation", "clear or deep perception of a situation", "n"],
  ["communicate", "pass", "transmit information", "v"],
  ["demonstrate", "show", "give an exhibition of to an interested audience", "v"],
  ["transit", "passage", "a journey usually by ship", "n"],
  ["highlight", "spotlight", "move into the foreground to make more visible or prominent", "v"],
  ["generate", "bring into existence", "bring into existence", "v"],
  ["essay", "an analytic or interpretive literary composition", "an analytic or interpretive literary composition", "n"],
  ["furthermore", "moreover", "in addition", "r"],
  ["usage", "use", "the act of using", "n"],
  ["neutral", "impersonal", "having no personal preference", "a"],
  ["enormous", "tremendous", "extraordinarily large in size or extent or amount or power or degree", "a"],
  ["nevertheless", "still", "despite anything to the contrary (usually following a concession)", "r"],
  ["convince", "convert", "make (someone) agree, understand, or realize the truth or validity of something", "v"],
  ["margin", "border", "the boundary line or the area immediately inside the boundary", "n"],
  ["parallel", "being everywhere equidistant and not intersecting", "being everywhere equidistant and not intersecting", "a"],
  ["globe", "ball", "an object with a spherical shape", "n"],
  ["involve", "affect", "connect closely and often incriminatingly", "v"],
  ["mature", "grow", "develop and reach maturity", "v"],
  ["submit", "subject", "refer for judgment or consideration", "v"],
  ["dialogue", "duologue", "a conversation between two persons", "n"],
  ["relax", "unwind", "become less tense, rest, or take one's ease", "v"],
  ["phrase", "a short musical passage", "a short musical passage", "n"],
  ["alcoholism", "drunkenness", "habitual intoxication", "n"],
  ["atheism", "godlessness", "the doctrine or belief that there is no God", "n"],
  ["audible", "hearable", "heard or perceptible by the ear", "a"],
  ["bathtub", "bath", "a relatively large open container that you fill with water and use to wash the body", "n"],
  ["biscuit", "cookie", "any of various small flat sweet cakes (`biscuit' is the British term)", "n"],
  ["bitterness", "resentment", "a feeling of deep and bitter anger and ill-will", "n"],
  ["blatant", "blazing", "without any attempt at concealment", "a"],
  ["candid", "frank", "characterized by directness in manner or speech", "a"],
  ["cervical", "relating to or associated with the neck", "relating to or associated with the neck", "a"],
  ["cherokee", "the Iroquoian language spoken by the Cherokee", "the Iroquoian language spoken by the Cherokee", "n"],
  ["clamp", "fasten or fix with a clamp", "fasten or fix with a clamp", "v"],
  ["competitiveness", "fight", "an aggressive willingness to compete", "n"],
  ["confederation", "alliance", "the state of being allied or confederated", "n"],
  ["confidentiality", "the state of being secret", "the state of being secret", "n"],
  ["contradiction", "opposition between two conflicting forces or ideas", "opposition between two conflicting forces or ideas", "n"],
  ["coronation", "investiture", "the ceremony of installing a new monarch", "n"],
  ["cracker", "redneck", "a poor White person in the southern United States", "n"],
  ["depiction", "picture", "a graphic or vivid verbal description", "n"],
  ["diabetic", "someone who has diabetes", "someone who has diabetes", "n"],
  ["diaspora", "the dispersion of the Jews outside Israel", "the dispersion of the Jews outside Israel", "n"],
  ["discord", "strife", "lack of agreement or harmony", "n"],
  ["divinity", "the quality of being divine", "the quality of being divine", "n"],
  ["dorsal", "abaxial", "facing away from the axis of an organ or organism", "a"],
  ["durability", "strength", "permanence by virtue of the power to resist stress or force", "n"],
  ["endeavour", "enterprise", "a purposeful or industrious undertaking (especially one that requires effort or boldness)", "n"],
  ["gadget", "convenience", "a device or control that is very useful for a particular job", "n"],
  ["genital", "venereal", "of or relating to the external sex organs", "a"],
  ["glitch", "bug", "a fault or defect in a computer program, system, or machine", "n"],
  ["greasy", "oily", "containing an unusual amount of grease or oil", "a"],
  ["hamburger", "beef that has been ground", "beef that has been ground", "n"],
  ["hideous", "repulsive", "so extremely ugly as to be terrifying", "a"],
  ["homepage", "the opening page of a web site", "the opening page of a web site", "n"],
  ["hoops", "basketball", "a game played on a court by two opposing teams of 5 players", "n"],
  ["imaginative", "inventive", "marked by independence and creativity in thought or action", "a"],
  ["imperfect", "not perfect", "not perfect", "a"],
  ["implicit", "inexplicit", "implied though not directly expressed", "a"],
  ["inlet", "recess", "an arm off of a larger body of water (often between rocky headlands)", "n"],
  ["insensitive", "not responsive to physical stimuli", "not responsive to physical stimuli", "a"],
  ["keystone", "anchor", "a central cohesive source of support and stability", "n"],
  ["kudos", "congratulations", "an expression of approval and commendation", "n"],
  ["liquidity", "fluidness", "the property of flowing easily", "n"],
  ["lutheran", "follower of Lutheranism", "follower of Lutheranism", "n"],
  ["mayhem", "havoc", "violent and needless disturbance", "n"],
  ["mould", "loose soil rich in organic matter", "loose soil rich in organic matter", "n"],
  ["neuroscience", "the scientific study of the nervous system", "the scientific study of the nervous system", "n"],
  ["oppressive", "weighing heavily on the senses or spirit", "weighing heavily on the senses or spirit", "a"],
  ["patronage", "championship", "the act of providing approval and support", "n"],
  ["pinnacle", "top", "the highest level or degree attainable", "n"],
  ["prosper", "thrive", "make steady progress", "v"],
  ["quake", "quiver", "shake with fast, tremulous movements", "v"],
  ["qualitative", "involving distinctions based on qualities", "involving distinctions based on qualities", "a"],
  ["racer", "a fast car that competes in races", "a fast car that competes in races", "n"],
  ["radial", "relating to or near the radius", "relating to or near the radius", "a"],
  ["recap", "review", "a summary at the end that repeats the substance of a longer discussion", "n"],
  ["recognizable", "easily perceived", "easily perceived", "a"],
  ["regent", "trustee", "members of a governing board", "n"],
  ["rendition", "rendering", "a performance of a musical composition or a dramatic role etc", "n"],
  ["roadside", "wayside", "edge of a way or road or path", "n"],
  ["shaky", "wobbly", "inclined to shake as from weakness or defect", "a"],
  ["slayer", "killer", "someone who causes the death of a person or animal", "n"],
  ["stalker", "someone who walks with long stiff strides", "someone who walks with long stiff strides", "n"],
  ["stature", "height", "the distance from head to foot", "n"],
  ["steward", "an attendant on an airplane", "an attendant on an airplane", "n"],
  ["stout", "stalwart", "dependable", "a"],
  ["stripper", "striptease", "a performer who provides erotic entertainment by undressing to music", "n"],
  ["stump", "cause to be perplexed or confounded", "cause to be perplexed or confounded", "v"],
  ["synagogue", "temple", "the place of worship for a Jewish congregation", "n"],
  ["tentative", "provisional", "under terms not final or fully worked out or agreed upon", "a"],
  ["topical", "of interest at the present time", "of interest at the present time", "a"],
  ["uneasy", "restless", "lacking or not affording physical or mental rest", "a"],
  ["unfold", "blossom", "develop or come to a promising stage", "v"],
  ["variance", "discrepancy", "an event that departs from expectations", "n"],
  ["wally", "a silly and inept person", "a silly and inept person", "n"],
  ["wavelength", "a shared orientation leading to mutual understanding", "a shared orientation leading to mutual understanding", "n"],
  ["advert", "ad", "a public promotion of some product or service", "n"],
  ["alias", "a name that has been assumed temporarily", "a name that has been assumed temporarily", "n"],
  ["annoy", "bother", "cause annoyance in", "v"],
  ["applaud", "clap", "clap one's hands or shout after performances to indicate approval", "v"],
  ["boredom", "tedium", "the feeling of being bored by something tedious", "n"],
  ["bowman", "archer", "a person who is expert in the use of a bow and arrow", "n"],
  ["brunch", "combination breakfast and lunch", "combination breakfast and lunch", "n"],
  ["burgundy", "a dark purplish-red to blackish-red color", "a dark purplish-red to blackish-red color", "n"],
  ["changer", "modifier", "a person who changes something", "n"],
  ["chestnut", "the brown color of chestnuts", "the brown color of chestnuts", "n"],
  ["cleaners", "shop where dry cleaning is done", "shop where dry cleaning is done", "n"],
  ["cleanup", "killing", "a very large profit", "n"],
  ["compose", "form the substance of", "form the substance of", "v"],
  ["concise", "expressing much in few words", "expressing much in few words", "a"],
  ["confinement", "labor", "concluding state of pregnancy", "n"],
  ["convergence", "intersection", "a representation of common ground between theories or phenomena", "n"],
  ["criterion", "standard", "a basis for comparison", "n"],
  ["deduction", "discount", "an amount or percentage deducted", "n"],
  ["despicable", "worthless", "morally reprehensible", "a"],
  ["detachment", "withdrawal", "avoiding emotional involvement", "n"],
  ["digestive", "any substance that promotes digestion", "any substance that promotes digestion", "n"],
  ["diminish", "fall", "decrease in size, extent, or range", "v"],
  ["disclaimer", "disavowal", "denial of any connection with or knowledge of", "n"],
  ["disconnect", "unplug", "pull the plug of (electrical appliances) and render inoperable", "v"],
  ["discriminatory", "prejudiced", "being biased or having a belief or attitude formed beforehand", "a"],
  ["disruptive", "troubled", "characterized by unrest or disorder or insubordination", "a"],
  ["enthusiast", "partisan", "an ardent and enthusiastic supporter of some person or activity", "n"],
  ["estimation", "estimate", "a document appraising the value of something (as for insurance or taxation)", "n"],
  ["excavation", "dig", "the act of digging", "n"],
  ["extremist", "a person who holds extreme views", "a person who holds extreme views", "n"],
  ["feeder", "eater", "someone who consumes food for nourishment", "n"],
  ["flashlight", "torch", "a small portable battery-powered electric lamp", "n"],
  ["garland", "adorn with bands of flowers or leaves", "adorn with bands of flowers or leaves", "v"],
  ["globalization", "growth to a global or worldwide scale", "growth to a global or worldwide scale", "n"],
  ["grail", "the object of any prolonged endeavor", "the object of any prolonged endeavor", "n"],
  ["graphical", "relating to or presented by a graph", "relating to or presented by a graph", "a"],
  ["holiness", "sanctity", "the quality of being holy", "n"],
  ["imbalance", "instability", "a lack of balance or state of disequilibrium", "n"],
  ["immoral", "base", "not adhering to ethical or moral principles", "a"],
  ["inefficient", "not producing desired results", "not producing desired results", "a"],
  ["intolerance", "impatience with annoyances", "impatience with annoyances", "n"],
  ["kappa", "the 10th letter of the Greek alphabet", "the 10th letter of the Greek alphabet", "n"],
  ["ketchup", "catsup", "thick spicy sauce made from tomatoes", "n"],
  ["leukemia", "malignant neoplasm of blood-forming tissues", "malignant neoplasm of blood-forming tissues", "n"],
  ["lineage", "line", "the descendants of one individual", "n"],
  ["manpower", "men", "the force of workers available", "n"],
  ["martyr", "sufferer", "one who suffers for the sake of principle", "n"],
  ["mitigation", "palliation", "to act in such a way as to cause an offense to seem less serious", "n"],
  ["motorway", "pike", "a broad highway designed for high-speed traffic", "n"],
  ["obscene", "lewd", "suggestive of or tending to moral looseness", "a"],
  ["octopus", "tentacles of octopus prepared as food", "tentacles of octopus prepared as food", "n"],
  ["onward", "forward", "forward in time or order or degree", "r"],
  ["ovarian", "of or involving the ovaries", "of or involving the ovaries", "a"],
  ["penal", "of or relating to punishment", "of or relating to punishment", "a"],
  ["plank", "board", "a stout length of sawn timber", "n"],
  ["plight", "predicament", "a situation from which extrication is difficult especially an unpleasant or trying one", "n"],
  ["privy", "can", "a room or building equipped with one or more toilets", "n"],
  ["propulsion", "a propelling force", "a propelling force", "n"],
  ["rejoice", "joy", "feel happiness or joy", "v"],
  ["serpent", "snake", "limbless scaly elongate reptile", "n"],
  ["sesame", "benny", "East Indian annual erect herb", "n"],
  ["siren", "delilah", "a woman who is considered to be dangerously seductive", "n"],
  ["slater", "woodlouse", "any of various small terrestrial isopods having a flat elliptical segmented body", "n"],
  ["sleeper", "slumberer", "a rester who is sleeping", "n"],
  ["smear", "vilification", "slanderous defamation", "n"],
  ["spectral", "of or relating to a spectrum", "of or relating to a spectrum", "a"],
  ["stabilize", "steady", "support or hold steady and make steadfast, with or as if with a brace", "v"],
  ["stalk", "walk stiffly", "walk stiffly", "v"],
  ["statesman", "solon", "a man who is a respected leader in national or international affairs", "n"],
  ["stink", "stench", "a distinctive odor that is offensively unpleasant", "n"],
  ["stormy", "affected or characterized by storms or commotion", "affected or characterized by storms or commotion", "a"],
  ["suffice", "do", "be sufficient", "v"],
  ["swine", "stout-bodied short-legged omnivorous animals", "stout-bodied short-legged omnivorous animals", "n"],
  ["symbolism", "a system of symbols and symbolic representations", "a system of symbols and symbolic representations", "n"],
  ["underworld", "the criminal class", "the criminal class", "n"],
  ["vigorous", "strong and active physically or mentally", "strong and active physically or mentally", "a"],
  ["admiralty", "the office of admiral", "the office of admiral", "n"],
  ["berth", "place", "a job in an organization", "n"],
  ["blackmail", "pressure", "exert pressure on someone through threats", "v"],
  ["blindness", "sightlessness", "the state of being blind or lacking sight", "n"],
  ["canary", "sneak", "someone acting as an informer or decoy for the police", "n"],
  ["ceramics", "the art of making and decorating pottery", "the art of making and decorating pottery", "n"],
  ["chilean", "a native or inhabitant of Chile", "a native or inhabitant of Chile", "n"],
  ["clumsy", "clunky", "lacking grace in movement or posture", "a"],
  ["contingency", "eventuality", "a possible event or occurrence or result", "n"],
  ["cupboard", "closet", "a small room (or recess) or cabinet used for storage space", "n"],
  ["deprivation", "want", "a state of extreme poverty", "n"],
  ["episcopal", "pontifical", "denoting or governed by or relating to a bishop or bishops", "a"],
  ["excellency", "an outstanding feature", "an outstanding feature", "n"],
  ["feasibility", "feasibleness", "the quality of being doable", "n"],
  ["frenzy", "fury", "state of violent mental agitation", "n"],
  ["indifferent", "apathetic", "marked by a lack of interest", "a"],
  ["inject", "shoot", "give an injection to", "v"],
  ["insistence", "insisting", "continual and persistent demands", "n"],
  ["invincible", "unbeatable", "incapable of being overcome or subdued", "a"],
  ["kinetic", "characterized by motion", "characterized by motion", "a"],
  ["lavender", "lilac", "of a pale purple color", "a"],
  ["lemonade", "sweetened beverage of diluted lemon juice", "sweetened beverage of diluted lemon juice", "n"],
  ["mania", "passion", "an irrational but irresistible motive for a belief or action", "n"],
  ["mythical", "fabulous", "based on or told of in traditional stories", "a"],
  ["orient", "point", "be oriented", "v"],
  ["outset", "first", "the time at which something is supposed to begin", "n"],
  ["parry", "block", "impede the movement of (an opponent or a ball)", "v"],
  ["patio", "terrace", "usually paved outdoor area adjoining a residence", "n"],
  ["peacock", "male peafowl", "male peafowl", "n"],
  ["pepsi", "Pepsi Cola is a trademarked cola", "Pepsi Cola is a trademarked cola", "n"],
  ["powerhouse", "fireball", "a highly energetic and indefatigable person", "n"],
  ["precursor", "forerunner", "a person who goes before or announces the coming of another", "n"],
  ["preferable", "preferred", "more desirable than another", "a"],
  ["preparatory", "preparative", "preceding and preparing for something", "a"],
  ["proclamation", "announcement", "a formal public statement", "n"],
  ["questionnaire", "a form containing a set of questions", "a form containing a set of questions", "n"],
  ["reclaim", "repossess", "claim back", "v"],
  ["redevelopment", "renovation", "the act of improving by renewing and restoring", "n"],
  ["reflex", "automatic", "without volition or conscious control", "a"],
  ["relocate", "become established in a new location", "become established in a new location", "v"],
  ["rematch", "replay", "something (especially a game) that is played again", "n"],
  ["renal", "nephritic", "of or relating to the kidneys", "a"],
  ["repayment", "refund", "the act of returning money received previously", "n"],
  ["riddle", "pierce with many holes", "pierce with many holes", "v"],
  ["roach", "the butt of a marijuana cigarette", "the butt of a marijuana cigarette", "n"],
  ["rubble", "dust", "the remains of something that has been destroyed or broken up", "n"],
  ["sapphire", "azure", "a light shade of blue", "n"],
  ["sectional", "sectioned", "consisting of or divided into sections", "a"],
  ["simulate", "copy", "reproduce someone's behavior or looks", "v"],
  ["sniff", "whiff", "perceive by inhaling through the nose", "v"],
  ["solvent", "dissolver", "a liquid substance capable of dissolving other substances", "n"],
  ["squid", "calamari", "squid prepared as food", "n"],
  ["sturdy", "hardy", "having rugged physical strength", "a"],
  ["swarm", "teem", "be teeming, be abuzz", "v"],
  ["tanker", "oiler", "a cargo ship designed to carry crude oil in bulk", "n"],
  ["torpedo", "gun", "a professional killer who uses a gun", "n"],
  ["trolley", "tram", "a wheeled vehicle that runs on rails and is propelled by electricity", "n"],
  ["viability", "capable of normal growth and development", "capable of normal growth and development", "n"],
  ["wolverine", "michigander", "a native or resident of Michigan", "n"],
  ["yearbook", "annual", "a reference book that is published regularly once every year", "n"],
  ["analyse", "break down into components or essential features", "break down into components or essential features", "v"],
  ["aperture", "a natural opening in something", "a natural opening in something", "n"],
  ["apprenticeship", "the position of apprentice", "the position of apprentice", "n"],
  ["aspire", "aim", "have an ambitious plan or a lofty goal", "v"],
  ["breadth", "comprehensiveness", "the capacity to understand a broad range of topics", "n"],
  ["buster", "dude", "an informal form of address for a man", "n"],
  ["cascade", "shower", "a sudden downpour (as of tears or sparks etc) likened to a rain shower", "n"],
  ["concord", "harmony", "a harmonious state of things in general and of their properties (as of colors and sounds)", "n"],
  ["connector", "connective", "an instrumentality that connects", "n"],
  ["consolidate", "unite into one", "unite into one", "v"],
  ["containment", "the act of containing", "the act of containing", "n"],
  ["crate", "a rugged box (usually made of wood)", "a rugged box (usually made of wood)", "n"],
  ["crave", "hunger", "have a craving, appetite, or great desire for", "v"],
  ["elusive", "difficult to describe", "difficult to describe", "a"],
  ["existential", "of or as conceived by existentialism", "of or as conceived by existentialism", "a"],
  ["experimentation", "the testing of an idea", "the testing of an idea", "n"],
  ["funnel", "move or pour through a funnel", "move or pour through a funnel", "v"],
  ["gloss", "rubric", "an explanation or definition of an obscure word in a text", "n"],
  ["graft", "transplant", "tissue or organ transplanted from a donor to a recipient", "n"],
  ["grumpy", "cross", "annoyed and irritable", "a"],
  ["guise", "pretext", "an artful or simulated semblance", "n"],
  ["imitation", "something copied or derived from an original", "something copied or derived from an original", "n"],
  ["immersion", "submerging", "sinking until covered completely with water", "n"],
  ["inconvenient", "not conveniently timed", "not conveniently timed", "a"],
  ["irresistible", "resistless", "impossible to resist", "a"],
  ["landslide", "an overwhelming electoral victory", "an overwhelming electoral victory", "n"],
  ["leash", "lead", "restraint consisting of a rope (or light chain) used to restrain an animal", "n"],
  ["makeover", "a complete reconstruction and renovation of something", "a complete reconstruction and renovation of something", "n"],
  ["memorandum", "memo", "a written proposal or reminder", "n"],
  ["mercer", "a dealer in textiles (especially silks)", "a dealer in textiles (especially silks)", "n"],
  ["mermaid", "half woman and half fish", "half woman and half fish", "n"],
  ["moderation", "moderateness", "quality of being moderate and avoiding extremes", "n"],
  ["moroccan", "maroc", "of or relating to or characteristic of Morocco or its people", "a"],
  ["nobility", "aristocracy", "a privileged class holding hereditary titles", "n"],
  ["notation", "note", "a comment or instruction (usually added)", "n"],
  ["onstage", "on the stage", "on the stage", "r"],
  ["ordeal", "a severe or trying experience", "a severe or trying experience", "n"],
  ["paranormal", "extrasensory", "seemingly outside normal sensory channels", "a"],
  ["piston", "plunger", "mechanical device that has a plunging or thrusting motion", "n"],
  ["puberty", "pubescence", "the time of life when sex glands become functional", "n"],
  ["reggae", "popular music originating in the West Indies", "popular music originating in the West Indies", "n"],
  ["rethink", "change one's mind", "change one's mind", "v"],
  ["reviewer", "reader", "someone who reads manuscripts and judges their suitability for publication", "n"],
  ["rodeo", "an exhibition of cowboy skills", "an exhibition of cowboy skills", "n"],
  ["shire", "a former administrative district of England", "a former administrative district of England", "n"],
  ["summons", "bidding", "a request to be present", "n"],
  ["taboo", "out", "excluded from use or mention", "a"],
  ["teaser", "a worker who teases wool", "a worker who teases wool", "n"],
  ["throttle", "accelerator", "a valve that regulates the supply of fuel to the engine", "n"],
  ["trendy", "voguish", "in accord with the latest fad", "a"],
  ["trivia", "trifle", "something of small importance", "n"],
  ["unbearable", "intolerable", "incapable of being put up with", "a"],
  ["underage", "minor", "not of legal age", "a"],
  ["vortex", "swirl", "the shape of something rotating rapidly", "n"],
  ["voucher", "verifier", "someone who vouches for another or for the correctness of a statement", "n"],
  ["abbot", "archimandrite", "the superior of an abbey of monks", "n"],
  ["ancestral", "hereditary", "inherited or inheritable by established rules (usually legal rules) of descent", "a"],
  ["antiquity", "ancientness", "extreme oldness", "n"],
  ["apocalyptic", "revelatory", "prophetic of devastation or ultimate doom", "a"],
  ["appraisal", "assessment", "the classification of someone or something with respect to its worth", "n"],
  ["autistic", "characteristic of or affected with autism", "characteristic of or affected with autism", "a"],
  ["bearer", "carrier", "someone whose employment involves carrying something", "n"],
  ["bleak", "dim", "offering little or no hope", "a"],
  ["blender", "liquidizer", "an electrically powered mixer with whirling blades that mix or chop or liquefy foods", "n"],
  ["bogus", "fake", "fraudulent", "a"],
  ["chaplain", "a clergyman ministering to some institution", "a clergyman ministering to some institution", "n"],
  ["chlorine", "cl", "a common nonmetallic element belonging to the halogens", "n"],
  ["chubby", "plump", "sufficiently fat so as to have a pleasing fullness of figure", "a"],
  ["clement", "physically mild", "physically mild", "a"],
  ["collusion", "secret agreement", "secret agreement", "n"],
  ["correctional", "concerned with or providing correction", "concerned with or providing correction", "a"],
  ["creamy", "of the color of cream", "of the color of cream", "a"],
  ["deterioration", "impairment", "a symptom of reduced quality or strength", "n"],
  ["disbelief", "skepticism", "doubt about the truth of something", "n"],
  ["discreet", "discerning", "unobtrusively perceptive and sympathetic", "a"],
  ["dizzy", "giddy", "having or causing a whirling sensation", "a"],
  ["enact", "ordain", "order by virtue of superior authority", "v"],
  ["expressive", "characterized by expression", "characterized by expression", "a"],
  ["fiddle", "violin", "bowed stringed instrument that is the highest member of the violin family", "n"],
  ["glossy", "slick", "a magazine printed on good quality paper", "n"],
  ["horrendous", "terrible", "causing fear or dread or terror", "a"],
  ["hostel", "lodge", "a hotel providing overnight lodging for travelers", "n"],
  ["hound", "dog", "someone who is morally reprehensible", "n"],
  ["illegitimate", "unlawful", "contrary to or forbidden by law", "a"],
  ["insomnia", "an inability to sleep", "an inability to sleep", "n"],
  ["interception", "the act of intercepting", "the act of intercepting", "n"],
  ["lagoon", "laguna", "a body of water cut off from a larger body by a reef of sand or coral", "n"],
  ["linguistics", "the scientific study of language", "the scientific study of language", "n"],
  ["lucifer", "phosphorus", "a planet (usually Venus) seen just before sunrise in the eastern sky", "n"],
  ["lunatic", "moonstruck", "insane and believed to be affected by the phases of the moon", "a"],
  ["lyrical", "suitable for or suggestive of singing", "suitable for or suggestive of singing", "a"],
  ["manifestation", "a clear appearance", "a clear appearance", "n"],
  ["migrate", "transmigrate", "move from one country or region to another and settle there", "v"],
  ["mildly", "to a moderate degree", "to a moderate degree", "r"],
  ["miraculous", "marvelous", "being or having the character of a miracle", "a"],
  ["mourn", "feel sadness", "feel sadness", "v"],
  ["mundane", "everyday", "found in the ordinary course of events", "a"],
  ["obsessive", "a person who has obsessions", "a person who has obsessions", "n"],
  ["overboard", "to extremes", "to extremes", "r"],
  ["pendant", "chandelier", "branched lighting fixture", "n"],
  ["petite", "tiny", "very small", "a"],
  ["pharma", "a company that makes and sells pharmaceuticals", "a company that makes and sells pharmaceuticals", "n"],
  ["pouch", "pocket", "an enclosed space", "n"],
  ["proficiency", "technique", "skillfulness in the command of fundamentals deriving from practice and familiarity", "n"],
  ["psychotic", "characteristic of or suffering from psychosis", "characteristic of or suffering from psychosis", "a"],
  ["reinforcement", "information that makes more forcible or convincing", "information that makes more forcible or convincing", "n"],
  ["relegation", "deputation", "authorizing subordinates to make certain decisions", "n"],
  ["repository", "deposit", "a facility where things can be deposited for storage or safekeeping", "n"],
  ["rumble", "rumbling", "a loud low dull continuous noise", "n"],
  ["saloon", "bar", "a room or establishment where alcoholic drinks are served over a counter", "n"],
  ["sanction", "okay", "give sanction to", "v"],
  ["shack", "hut", "small crude shelter used as a dwelling", "n"],
  ["stale", "urinate, of cattle and horses", "urinate, of cattle and horses", "v"],
  ["stereotype", "a conventional or formulaic conception or image", "a conventional or formulaic conception or image", "n"],
  ["sterile", "infertile", "incapable of reproducing", "a"],
  ["stride", "pace", "a step in walking or running", "n"],
  ["stringent", "tight", "demanding strict attention to rules and procedures", "a"],
  ["sulfur", "s", "an abundant tasteless odorless multivalent nonmetallic element", "n"],
  ["torrent", "deluge", "a heavy rain", "n"],
  ["trainee", "someone who is being trained", "someone who is being trained", "n"],
  ["trough", "gutter", "a channel along the eaves or on the roof", "n"],
  ["trunks", "shorts", "trousers that end at or above the knee", "n"],
  ["tummy", "corporation", "slang for a paunch", "n"],
  ["unjust", "unfair", "not fair", "a"],
  ["venezuelan", "a native or inhabitant of Venezuela", "a native or inhabitant of Venezuela", "n"],
  ["wager", "bet", "the act of gambling", "n"],
  ["whack", "wham", "hit hard", "v"],
  ["wichita", "the Caddoan language spoken by the Wichita", "the Caddoan language spoken by the Wichita", "n"],
  ["abolish", "do away with", "do away with", "v"],
  ["accumulate", "collect", "get or gather together", "v"],
  ["admirable", "deserving of the highest esteem or admiration", "deserving of the highest esteem or admiration", "a"],
  ["adventurous", "adventuresome", "willing to undertake or seeking out new and daring enterprises", "a"],
  ["anthology", "a collection of selected literary passages", "a collection of selected literary passages", "n"],
  ["anyhow", "anyway", "used to indicate that a statement explains or supports a previous statement", "r"],
  ["auditor", "listener", "someone who listens attentively", "n"],
  ["banter", "backchat", "light teasing repartee", "n"],
  ["bidder", "someone who makes an offer", "someone who makes an offer", "n"],
  ["blueprint", "design", "something intended as a guide for making something else", "n"],
  ["bowler", "derby", "a felt hat that is round and hard with a narrow brim", "n"],
  ["caramel", "burnt sugar", "burnt sugar", "n"],
  ["charismatic", "magnetic", "possessing an extraordinary ability to attract", "a"],
  ["concede", "confess", "admit (to a wrongdoing)", "v"],
  ["contestant", "a person who participates in competitions", "a person who participates in competitions", "n"],
  ["contradictory", "confounding", "that confounds or contradicts or confuses", "a"],
  ["convent", "a religious residence especially for nuns", "a religious residence especially for nuns", "n"],
  ["converse", "discourse", "carry on a conversation", "v"],
  ["corrosion", "erosion", "erosion by chemical action", "n"],
  ["crossroads", "hamlet", "a community of people smaller than a village", "n"],
  ["dearly", "in a sincere and heartfelt manner", "in a sincere and heartfelt manner", "r"],
  ["defiance", "rebelliousness", "intentionally contemptuous behavior or attitude", "n"],
  ["deter", "discourage", "try to prevent", "v"],
  ["diner", "a restaurant that resembles a dining car", "a restaurant that resembles a dining car", "n"],
  ["disposition", "temperament", "your usual mood", "n"],
  ["ecstasy", "transport", "a state of being carried away by overwhelming emotion", "n"],
  ["eighteenth", "coming next after the seventeenth in position", "coming next after the seventeenth in position", "a"],
  ["envoy", "emissary", "someone sent on a mission to represent the interests of someone else", "n"],
  ["expiration", "termination", "a coming to an end of a contract period", "n"],
  ["fabrication", "fiction", "a deliberately false or improbable account", "n"],
  ["fascination", "captivation", "the state of being intensely interested (as by awe or terror)", "n"],
  ["foreigner", "alien", "a person who comes from a foreign country", "n"],
  ["formulation", "preparation", "a substance prepared according to a formula", "n"],
  ["frontal", "belonging to the front part", "belonging to the front part", "a"],
  ["goalie", "goalkeeper", "the soccer or hockey player assigned to protect the goal", "n"],
  ["gravy", "boom", "a sudden happening that brings good fortune (as a sudden opportunity to make money)", "n"],
  ["hopper", "funnel-shaped receptacle", "funnel-shaped receptacle", "n"],
  ["hysterical", "characterized by or arising from psychoneurotic hysteria", "characterized by or arising from psychoneurotic hysteria", "a"],
  ["implant", "embed", "fix or set securely or deeply", "v"],
  ["incompatible", "not compatible", "not compatible", "a"],
  ["injunction", "a formal command or admonition", "a formal command or admonition", "n"],
  ["keynote", "set the keynote of", "set the keynote of", "v"],
  ["motivational", "of or relating to motivation", "of or relating to motivation", "a"],
  ["paralysis", "palsy", "loss of the ability to move a body part", "n"],
  ["pianist", "a person who plays the piano", "a person who plays the piano", "n"],
  ["placebo", "an innocuous or inert medication", "an innocuous or inert medication", "n"],
  ["postpone", "table", "hold back to a later time", "v"],
  ["repetition", "repeat", "an event that repeats", "n"],
  ["retrospective", "concerned with or related to the past", "concerned with or related to the past", "a"],
  ["righteousness", "adhering to moral principles", "adhering to moral principles", "n"],
  ["rinse", "wash off soap or remaining dirt", "wash off soap or remaining dirt", "v"],
  ["scalp", "sell illegally, as on the black market", "sell illegally, as on the black market", "v"],
  ["shutter", "a hinged blind for a window", "a hinged blind for a window", "n"],
  ["sparrow", "dunnock", "small brownish European songbird", "n"],
  ["speculate", "suppose", "to believe especially on uncertain or tentative grounds", "v"],
  ["spinach", "dark green leaves", "dark green leaves", "n"],
  ["squat", "crouch", "sit on one's heels", "v"],
  ["sublime", "empyrean", "inspiring awe", "a"],
  ["sweetness", "sweet", "the taste experience when sugar dissolves in the mouth", "n"],
  ["terrestrial", "telluric", "of or relating to or inhabiting the land as opposed to the sea or air", "a"],
  ["thorn", "irritant", "something that causes irritation and annoyance", "n"],
  ["uncover", "reveal", "make visible", "v"],
  ["unnatural", "abnormal", "not normal", "a"],
  ["unstoppable", "not capable of being stopped", "not capable of being stopped", "a"],
  ["upfront", "frank and honest", "frank and honest", "a"],
  ["wharf", "dock", "a platform built out from the shore into the water and supported by piles", "n"],
  ["wrestle", "engage in deep thought, consideration, or debate", "engage in deep thought, consideration, or debate", "v"],
  ["accelerator", "gas", "a pedal that controls the throttle valve", "n"],
  ["acrylic", "polymerized from acrylonitrile", "polymerized from acrylonitrile", "n"],
  ["anchorage", "a fee for anchoring", "a fee for anchoring", "n"],
  ["annexation", "appropriation", "incorporation by joining or uniting", "n"],
  ["ascent", "rise", "an upward slope or grade (as in a road)", "n"],
  ["ballad", "lay", "a narrative song with a recurrent refrain", "n"],
  ["betray", "reveal unintentionally", "reveal unintentionally", "v"],
  ["bigotry", "dogmatism", "the intolerance and prejudice of a bigot", "n"],
  ["bookstore", "bookshop", "a shop where books are sold", "n"],
  ["breakers", "surf", "waves breaking on the shore", "n"],
  ["broom", "a cleaning implement for sweeping", "a cleaning implement for sweeping", "n"],
  ["brute", "wolf", "a cruelly rapacious person", "n"],
  ["camouflage", "disguise by camouflaging", "disguise by camouflaging", "v"],
  ["catalan", "a native or inhabitant of Catalonia", "a native or inhabitant of Catalonia", "n"],
  ["childbirth", "childbearing", "the parturition process in human beings", "n"],
  ["compliant", "disposed or willing to comply", "disposed or willing to comply", "a"],
  ["corona", "aureole", "the outermost region of the sun's atmosphere", "n"],
  ["cultivate", "foster the growth of", "foster the growth of", "v"],
  ["cyril", "Greek missionary", "Greek missionary", "n"],
  ["dearest", "love", "a beloved person", "n"],
  ["decker", "something constructed with multiple levels", "something constructed with multiple levels", "n"],
  ["devoid", "free", "completely wanting or lacking", "a"],
  ["disparity", "inequality or difference in some respect", "inequality or difference in some respect", "n"],
  ["divert", "deviate", "turn aside", "v"],
  ["eater", "feeder", "someone who consumes food for nourishment", "n"],
  ["facade", "frontal", "the face or front of a building", "n"],
];

const ISEE_UPPER_ENTRIES: readonly VocabularyEntry[] = [
  ["industrialization", "the development of industry on an extensive scale", "the development of industry on an extensive scale", "n"],
  ["consonant", "a speech sound that is not a vowel", "a speech sound that is not a vowel", "n"],
  ["dissection", "cutting so as to separate into pieces", "cutting so as to separate into pieces", "n"],
  ["rationality", "reason", "the state of having good sense and sound judgment", "n"],
  ["subtract", "deduct", "make a subtraction", "v"],
  ["conduction", "conductivity", "the transmission of heat or electricity or sound", "n"],
  ["lexical", "of or relating to words", "of or relating to words", "a"],
  ["denominator", "the divisor of a fraction", "the divisor of a fraction", "n"],
  ["mediate", "intermediate", "act between parties with a view to reconciling differences", "v"],
  ["millimeter", "mm", "a metric unit of length equal to one thousandth of a meter", "n"],
  ["oscillation", "the process of oscillating between states", "the process of oscillating between states", "n"],
  ["encode", "convert information into code", "convert information into code", "v"],
  ["incline", "run", "have a tendency or disposition to do or be something", "v"],
  ["morphological", "structural", "pertaining to geological structure", "a"],
  ["communicative", "of or relating to communication", "of or relating to communication", "a"],
  ["connotation", "intension", "what you must know in order to determine the reference of an expression", "n"],
  ["entrant", "a commodity that enters competition with established merchandise", "a commodity that enters competition with established merchandise", "n"],
  ["cyclic", "conforming to the Carnot cycle", "conforming to the Carnot cycle", "a"],
  ["socialize", "take part in social activities", "take part in social activities", "v"],
  ["theorist", "theoretician", "someone who theorizes (especially in science or art)", "n"],
  ["circulate", "spread", "become widely known and passed on", "v"],
  ["equivalence", "equality", "a state of being essentially equal or equivalent", "n"],
  ["footnote", "footer", "a printed note placed below the text on a printed page", "n"],
  ["confine", "limit", "place limits on (extent or access)", "v"],
  ["dilute", "cut", "lessen the strength or flavor of a solution or mixture", "v"],
  ["generalize", "infer", "draw from specific cases for more general cases", "v"],
  ["kilometer", "km", "a metric unit of length equal to 1000 meters (or 0.621371 miles)", "n"],
  ["sneeze", "sneezing", "a symptom consisting of the involuntary expulsion of air from the nose", "n"],
  ["demonstrator", "protester", "someone who participates in a public display of group feeling", "n"],
  ["affirm", "support", "establish or strengthen as with new evidence or facts", "v"],
  ["correlate", "to bear a reciprocal or mutual relation", "to bear a reciprocal or mutual relation", "v"],
  ["generalization", "induction", "reasoning from detailed facts to general principles", "n"],
  ["capillary", "a tube of small internal diameter", "a tube of small internal diameter", "n"],
  ["deflection", "warp", "a twist or aberration", "n"],
  ["memorize", "learn", "commit to memory", "v"],
  ["reconstruct", "retrace", "reassemble mentally", "v"],
  ["splice", "join the ends of", "join the ends of", "v"],
  ["converge", "meet", "be adjacent or come together", "v"],
  ["precede", "forgo", "be earlier in time", "v"],
  ["inversion", "anastrophe", "the reversal of the normal order of words", "n"],
  ["volition", "will", "the capability of conscious choice and decision and intention", "n"],
  ["uplift", "intoxicate", "fill with high spirits", "v"],
  ["amplitude", "the maximum displacement of a periodic wave", "the maximum displacement of a periodic wave", "n"],
  ["degrade", "reduce the level of land, as by erosion", "reduce the level of land, as by erosion", "v"],
  ["postgraduate", "a student who continues studies after graduation", "a student who continues studies after graduation", "n"],
  ["constrain", "restrain", "hold back", "v"],
  ["unintelligible", "poorly articulated or enunciated, or drowned by noise", "poorly articulated or enunciated, or drowned by noise", "a"],
  ["denote", "be a sign or indication of", "be a sign or indication of", "v"],
  ["herbicide", "weedkiller", "a chemical agent that destroys plants or inhibits their growth", "n"],
  ["allocate", "apportion", "distribute according to a plan or set apart for a special purpose", "v"],
  ["complication", "the act or process of complicating", "the act or process of complicating", "n"],
  ["approximation", "idea", "an approximate calculation of quantity or degree or worth", "n"],
  ["precipitate", "bring about abruptly", "bring about abruptly", "v"],
  ["exponential", "of or involving exponents", "of or involving exponents", "a"],
  ["acidic", "being or containing an acid", "being or containing an acid", "a"],
  ["indifference", "unbiased impartial unconcern", "unbiased impartial unconcern", "n"],
  ["inhibit", "curb", "to put down by force or authority", "v"],
  ["syllabus", "program", "an integrated course of academic studies", "n"],
  ["biologist", "a scientist who studies living organisms", "a scientist who studies living organisms", "n"],
  ["computation", "calculation", "the procedure of calculating", "n"],
  ["contradict", "negate", "be in contradiction with", "v"],
  ["grammatical", "of or pertaining to grammar", "of or pertaining to grammar", "a"],
  ["invert", "make an inversion (in a musical composition)", "make an inversion (in a musical composition)", "v"],
  ["censor", "someone who censures or condemns", "someone who censures or condemns", "n"],
  ["infect", "communicate a disease to", "communicate a disease to", "v"],
  ["conserve", "preserve", "fruit preserved by cooking with sugar", "n"],
  ["contour", "form", "any spatial attributes (especially as defined by outline)", "n"],
  ["longitudinal", "of or relating to lines of longitude", "of or relating to lines of longitude", "a"],
  ["phonological", "of or relating to phonology", "of or relating to phonology", "a"],
  ["secrete", "release", "generate and separate from cells or bodily fluids", "v"],
  ["standardize", "cause to conform to standard or norm", "cause to conform to standard or norm", "v"],
  ["utterance", "vocalization", "the use of uttered sounds for auditory communication", "n"],
  ["deceive", "delude", "be false to", "v"],
  ["elevate", "raise", "give a promotion to or assign to a higher position", "v"],
  ["variability", "variance", "the quality of being subject to variation", "n"],
  ["chloride", "any compound containing a chlorine atom", "any compound containing a chlorine atom", "n"],
  ["classify", "class", "arrange or order by classes or categories", "v"],
  ["inhibition", "suppression", "the conscious exclusion of unacceptable thoughts or desires", "n"],
  ["scatter", "disperse", "to cause to separate and go in different directions", "v"],
  ["conceive", "conceptualize", "have the idea for", "v"],
  ["deviation", "difference", "a variation that deviates from the standard or norm", "n"],
  ["diffusion", "dissemination", "the property of being diffused or dispersed", "n"],
  ["congruent", "congruous", "corresponding in character or kind", "a"],
  ["transcribe", "write out from speech, notes, etc", "write out from speech, notes, etc", "v"],
  ["artifact", "a man-made object taken as a whole", "a man-made object taken as a whole", "n"],
  ["depict", "show", "show in, or as in, a picture", "v"],
  ["diagnose", "name", "determine or distinguish the nature of a problem or an illness through a diagnostic analysis", "v"],
  ["morphology", "studies of the rules for forming admissible words", "studies of the rules for forming admissible words", "n"],
  ["novice", "novitiate", "someone who has entered a religious order but has not taken final vows", "n"],
  ["substitution", "switch", "an event in which one thing is substituted for another", "n"],
  ["phosphate", "a salt of phosphoric acid", "a salt of phosphoric acid", "n"],
  ["replication", "reproduction", "the act of making copies", "n"],
  ["sediment", "deposit", "matter that has been deposited by some natural process", "n"],
  ["antiquity", "ancientness", "extreme oldness", "n"],
  ["linguistics", "the scientific study of language", "the scientific study of language", "n"],
  ["migrate", "transmigrate", "move from one country or region to another and settle there", "v"],
  ["stereotype", "a conventional or formulaic conception or image", "a conventional or formulaic conception or image", "n"],
  ["inject", "shoot", "give an injection to", "v"],
  ["orient", "point", "be oriented", "v"],
  ["questionnaire", "a form containing a set of questions", "a form containing a set of questions", "n"],
  ["simulate", "copy", "reproduce someone's behavior or looks", "v"],
  ["solvent", "dissolver", "a liquid substance capable of dissolving other substances", "n"],
  ["confound", "throw", "be confusing or perplexing to", "v"],
  ["contradiction", "opposition between two conflicting forces or ideas", "opposition between two conflicting forces or ideas", "n"],
  ["implicit", "inexplicit", "implied though not directly expressed", "a"],
  ["qualitative", "involving distinctions based on qualities", "involving distinctions based on qualities", "a"],
  ["variance", "discrepancy", "an event that departs from expectations", "n"],
  ["wavelength", "a shared orientation leading to mutual understanding", "a shared orientation leading to mutual understanding", "n"],
  ["convergence", "intersection", "a representation of common ground between theories or phenomena", "n"],
  ["estimation", "estimate", "a document appraising the value of something (as for insurance or taxation)", "n"],
  ["globalization", "growth to a global or worldwide scale", "growth to a global or worldwide scale", "n"],
  ["stabilize", "steady", "support or hold steady and make steadfast, with or as if with a brace", "v"],
  ["parenthesis", "aside", "a message that departs from the main subject", "n"],
  ["connector", "connective", "an instrumentality that connects", "n"],
  ["notation", "note", "a comment or instruction (usually added)", "n"],
  ["rewrite", "write differently", "write differently", "v"],
  ["turbulent", "troubled", "characterized by unrest or disorder or insubordination", "a"],
  ["accumulate", "collect", "get or gather together", "v"],
  ["contradictory", "confounding", "that confounds or contradicts or confuses", "a"],
  ["formulation", "preparation", "a substance prepared according to a formula", "n"],
  ["innate", "unlearned", "not established by conditioning or learning", "a"],
  ["ancestor", "root", "someone from whom you are descended (but usually more remote than a grandparent)", "n"],
  ["differentiation", "distinction", "a discrimination between things as different and distinct", "n"],
  ["dissolve", "become weaker", "become weaker", "v"],
  ["pragmatic", "concerned with practical matters", "concerned with practical matters", "a"],
  ["antibiotic", "of or relating to antibiotic drugs", "of or relating to antibiotic drugs", "a"],
  ["primer", "an introductory textbook", "an introductory textbook", "n"],
  ["regression", "fixation", "an abnormal state in which development has stopped prematurely", "n"],
  ["interviewer", "a person who conducts an interview", "a person who conducts an interview", "n"],
  ["nutrient", "food", "any substance that can be metabolized by an animal to give energy and build tissue", "n"],
  ["quotation", "credit", "a short note recognizing a source of information or of a quoted passage", "n"],
  ["stripe", "band", "an adornment consisting of a strip of a contrasting color or material", "n"],
  ["bilingual", "using or knowing two languages", "using or knowing two languages", "a"],
  ["initiation", "installation", "a formal entry into an organization or position or office", "n"],
  ["residual", "relating to or indicating a remainder", "relating to or indicating a remainder", "a"],
  ["characterization", "picture", "a graphic or vivid verbal description", "n"],
  ["marrow", "very tender and very nutritious tissue from marrowbones", "very tender and very nutritious tissue from marrowbones", "n"],
  ["planner", "deviser", "a person who makes plans", "n"],
  ["residue", "matter that remains after something has been removed", "matter that remains after something has been removed", "n"],
  ["syntax", "the grammatical arrangement of words in sentences", "the grammatical arrangement of words in sentences", "n"],
  ["solute", "the dissolved matter in a solution", "the dissolved matter in a solution", "n"],
  ["articulate", "joint", "provide with a joint", "v"],
  ["dialect", "accent", "the usage or vocabulary that is characteristic of a specific group of people", "n"],
  ["optimum", "optimal", "most desirable possible under a restriction expressed or implied", "a"],
  ["physiological", "of or consistent with an organism's normal functioning", "of or consistent with an organism's normal functioning", "a"],
  ["reactive", "participating readily in reactions", "participating readily in reactions", "a"],
  ["transcription", "arrangement", "the act of arranging and adapting a piece of music", "n"],
  ["portrayal", "portrait", "a word picture of a person's appearance and character", "n"],
  ["replicate", "retroflex", "bend or turn backward", "v"],
  ["headquarter", "provide with headquarters", "provide with headquarters", "v"],
  ["calculator", "computer", "an expert at calculation (or at operating calculating machines)", "n"],
  ["discrete", "distinct", "constituting a separate entity or part", "a"],
  ["induce", "cause to arise", "cause to arise", "v"],
  ["multinational", "transnational", "involving or operating in several nations or nationalities", "a"],
  ["comprehension", "inclusion", "the relation of comprising something", "n"],
  ["factorial", "of or relating to factorials", "of or relating to factorials", "a"],
  ["abdominal", "of or relating to or near the abdomen", "of or relating to or near the abdomen", "a"],
  ["adolescent", "teen", "a juvenile between the onset of puberty and maturity", "n"],
  ["dictate", "order", "issue commands or orders for", "v"],
  ["potassium", "k", "a light soft silver-white metallic element of the alkali metal group", "n"],
  ["rotate", "revolve", "turn on or around an axis or a center", "v"],
  ["similarity", "the quality of being similar", "the quality of being similar", "n"],
  ["accumulation", "accretion", "an increase by natural growth or addition", "n"],
  ["conditional", "qualified by reservations", "qualified by reservations", "a"],
  ["cortex", "pallium", "the layer of unmyelinated neurons (the grey matter) forming the cortex of the cerebrum", "n"],
  ["elastic", "flexible", "able to adjust readily to different conditions", "a"],
  ["nucleus", "karyon", "a part of the cell containing DNA and RNA and responsible for growth and reproduction", "n"],
  ["organism", "being", "a living thing that has (or can develop) the ability to act or function independently", "n"],
  ["calculus", "concretion", "a hard lump produced by the concretion of mineral salts", "n"],
  ["equilibrium", "balance", "equality of distribution", "n"],
  ["nominal", "token", "insignificantly small", "a"],
  ["adaptive", "having a capacity for adaptation", "having a capacity for adaptation", "a"],
  ["disturbance", "perturbation", "activity that is a malfunction, intrusion, or interruption", "n"],
  ["interrupt", "disrupt", "make a break in", "v"],
  ["invade", "to intrude upon, infringe, encroach on, violate", "to intrude upon, infringe, encroach on, violate", "v"],
  ["onwards", "forward", "in a forward direction", "r"],
  ["paradigm", "image", "a standard or typical example", "n"],
  ["trajectory", "flight", "the path followed by an object moving through space", "n"],
  ["assert", "maintain", "state categorically", "v"],
  ["conceptual", "being or characterized by concepts or their formation", "being or characterized by concepts or their formation", "a"],
  ["differentiate", "tell", "mark as different", "v"],
  ["empirical", "derived from experiment and observation rather than theory", "derived from experiment and observation rather than theory", "a"],
  ["peasant", "provincial", "a country person", "n"],
  ["presume", "assume", "take to be the case or to be true", "v"],
  ["coherent", "ordered", "marked by an orderly, logical, and aesthetically consistent relation of parts", "a"],
  ["displacement", "supplanting", "act of taking the place of another especially using underhanded tactics", "n"],
  ["maximize", "make as big or large as possible", "make as big or large as possible", "v"],
  ["paradox", "a statement that contradicts itself", "a statement that contradicts itself", "n"],
  ["periodic", "happening or recurring at regular intervals", "happening or recurring at regular intervals", "a"],
  ["portray", "portray in words", "portray in words", "v"],
  ["practitioner", "practician", "someone who practices a learned profession", "n"],
  ["reproduce", "make a copy or equivalent of", "make a copy or equivalent of", "v"],
  ["temporal", "not eternal", "not eternal", "a"],
  ["approximate", "be close or similar", "be close or similar", "v"],
  ["corpus", "principal", "capital as contrasted with the income derived from it", "n"],
  ["deficiency", "want", "the state of needing something that is absent or unavailable", "n"],
  ["incidence", "the relative frequency of occurrence of something", "the relative frequency of occurrence of something", "n"],
  ["mutation", "sport", "an organism that has characteristics resulting from chromosomal alteration", "n"],
  ["plausible", "apparently reasonable and valid, and truthful", "apparently reasonable and valid, and truthful", "a"],
  ["precipitation", "the process of forming a chemical precipitate", "the process of forming a chemical precipitate", "n"],
  ["substrate", "any stratum or layer lying underneath another", "any stratum or layer lying underneath another", "n"],
  ["derivative", "differential", "the result of mathematical differentiation", "n"],
  ["intervene", "interfere", "get involved, so as to alter or hinder an action, or through force or threat of force", "v"],
  ["numerical", "measured or expressed in numbers", "measured or expressed in numbers", "a"],
  ["undermine", "sabotage", "destroy property or hinder normal operations", "v"],
  ["absorption", "a process in which one substance permeates another", "a process in which one substance permeates another", "n"],
  ["accelerate", "speed", "move faster", "v"],
  ["prevalence", "the quality of prevailing generally", "the quality of prevailing generally", "n"],
  ["pronounce", "say", "speak, pronounce, or utter in a certain way", "v"],
  ["trivial", "little", "small and of little importance", "a"],
  ["molecule", "particle", "a tiny piece of anything", "n"],
  ["parcel", "package", "a wrapped container", "n"],
  ["partition", "divider", "a vertical structure that divides or separates (as a wall divides one room from another)", "n"],
  ["susceptible", "yielding readily to or capable of", "yielding readily to or capable of", "a"],
  ["transmit", "communicate", "transfer to another", "v"],
  ["defect", "an imperfection in a bodily system", "an imperfection in a bodily system", "n"],
  ["reinforce", "make stronger", "make stronger", "v"],
  ["sensory", "sensorial", "involving or derived from the senses", "a"],
  ["strand", "maroon", "leave stranded or isolated with little hope of rescue", "v"],
  ["terminology", "language", "a system of words used to name things in a particular discipline", "n"],
  ["manipulate", "influence or control shrewdly or deviously", "influence or control shrewdly or deviously", "v"],
  ["realism", "pragmatism", "the attribute of accepting the facts of life and favoring practicality and literal truth", "n"],
  ["retrieve", "find", "get or find back", "v"],
  ["dissertation", "thesis", "a treatise advancing a new point of view resulting from research", "n"],
  ["domination", "social control by dominating", "social control by dominating", "n"],
  ["emission", "emanation", "the act of emitting", "n"],
  ["fracture", "violate or abuse", "violate or abuse", "v"],
  ["overlap", "coincide partially or wholly", "coincide partially or wholly", "v"],
  ["validity", "rigor", "the quality of being valid and rigorous", "n"],
  ["backward", "back", "at or to or toward the back or rear", "r"],
  ["directive", "a pronouncement encouraging or banning some activity", "a pronouncement encouraging or banning some activity", "n"],
  ["disadvantage", "disfavor", "put at a disadvantage", "v"],
  ["friction", "clash", "a state of conflict between persons", "n"],
  ["instability", "an unstable order", "an unstable order", "n"],
  ["linguistic", "lingual", "consisting of or related to language", "a"],
  ["marginal", "fringy", "at or constituting a border or edge", "a"],
  ["predator", "vulture", "someone who attacks in search of booty", "n"],
  ["spontaneous", "happening or arising without apparent external cause", "happening or arising without apparent external cause", "a"],
  ["theorem", "a proposition deducible from basic postulates", "a proposition deducible from basic postulates", "n"],
  ["upward", "up", "spatially or metaphorically from a lower to a higher position", "r"],
  ["descendent", "going or coming down", "going or coming down", "a"],
  ["impulse", "urge", "an instinctive motive", "n"],
  ["lecturer", "reader", "a public lecturer at certain universities", "n"],
  ["philosopher", "a specialist in philosophy", "a specialist in philosophy", "n"],
  ["plantation", "grove", "garden consisting of a small cultivated wood without undergrowth", "n"],
  ["specimen", "an example regarded as typical of its class", "an example regarded as typical of its class", "n"],
  ["sponsorship", "the act of sponsoring (either officially or financially)", "the act of sponsoring (either officially or financially)", "n"],
  ["acceleration", "an increase in rate of change", "an increase in rate of change", "n"],
  ["bacterial", "relating to or caused by bacteria", "relating to or caused by bacteria", "a"],
  ["quantitative", "relating to the measurement of quantity", "relating to the measurement of quantity", "a"],
  ["resemble", "appear like", "appear like", "v"],
  ["oxidize", "oxidate", "enter into a combination with oxygen or become converted into an oxide", "v"],
  ["allocation", "allotment", "a share set aside for a specific purpose", "n"],
  ["ecology", "the environment as it relates to living organisms", "the environment as it relates to living organisms", "n"],
  ["emergence", "growth", "the gradual beginning or coming forth", "n"],
  ["initiate", "start", "bring into being", "v"],
  ["singular", "remarkable", "unusual or striking", "a"],
  ["conception", "construct", "an abstract or general idea inferred or derived from specific instances", "n"],
  ["finite", "of verbs", "of verbs", "a"],
  ["lateral", "sidelong", "situated at or extending to the side", "a"],
  ["specification", "spec", "a detailed description of design criteria for a piece of work", "n"],
  ["thickness", "indistinct articulation", "indistinct articulation", "n"],
  ["utilize", "use", "put into service", "v"],
  ["activate", "trip", "put in motion or move to act", "v"],
  ["calculation", "computing", "the procedure of calculating", "n"],
  ["insect", "small air-breathing arthropod", "small air-breathing arthropod", "n"],
  ["neural", "nervous", "of or relating to the nervous system", "a"],
  ["phenomenal", "of or relating to a phenomenon", "of or relating to a phenomenon", "a"],
  ["photographic", "relating to photography or obtained by using photography", "relating to photography or obtained by using photography", "a"],
  ["transplant", "transfer", "lift and reset in another soil or situation", "v"],
  ["algebra", "the mathematics of generalized arithmetical operations", "the mathematics of generalized arithmetical operations", "n"],
  ["comparative", "relating to or based on or involving comparison", "relating to or based on or involving comparison", "a"],
  ["complement", "make complete or perfect", "make complete or perfect", "v"],
  ["continuity", "uninterrupted connection or union", "uninterrupted connection or union", "n"],
  ["incumbent", "officeholder", "the official who holds an office", "n"],
  ["interval", "separation", "the distance between things", "n"],
  ["maternal", "characteristic of a mother", "characteristic of a mother", "a"],
  ["modification", "adjustment", "the act of making something different (as e.g. the size of a garment)", "n"],
  ["objection", "remonstrance", "the act of expressing earnest opposition or protest", "n"],
  ["occurrence", "happening", "an event that happens", "n"],
  ["pathway", "tract", "a bundle of myelinated nerve fibers following a path through the brain", "n"],
  ["scripture", "book", "the sacred writings of the Christian religions", "n"],
  ["seminar", "any meeting for an exchange of ideas", "any meeting for an exchange of ideas", "n"],
  ["textbook", "text", "a book prepared for use in schools or colleges", "n"],
  ["vegetation", "flora", "all the plant life in a particular region or period", "n"],
  ["bodily", "in bodily form", "in bodily form", "r"],
  ["compensate", "correct", "adjust for", "v"],
  ["definite", "precise", "precise", "a"],
  ["developmental", "of or relating to or constituting development", "of or relating to or constituting development", "a"],
  ["ecological", "bionomical", "of or relating to the science of ecology", "a"],
  ["fertility", "birthrate", "the ratio of live births in an area to the population of that area", "n"],
  ["metabolism", "metamorphosis", "the marked and rapid transformation of a larva into an adult that occurs in some animals", "n"],
  ["parental", "maternal", "relating to or characteristic of or befitting a parent", "a"],
  ["render", "cause to become", "cause to become", "v"],
  ["capitalist", "of or relating to capitalism or capitalists", "of or relating to capitalism or capitalists", "a"],
  ["mechanic", "machinist", "a craftsman skilled in operating machine tools", "n"],
  ["prejudice", "bias", "a partiality that prevents objective consideration of an issue or situation", "n"],
  ["projection", "a prediction made by extrapolating from past observations", "a prediction made by extrapolating from past observations", "n"],
  ["reproduction", "the process of generating offspring", "the process of generating offspring", "n"],
  ["subjective", "immanent", "of a mental act performed entirely within the mind", "a"],
  ["epidemic", "a widespread outbreak of an infectious disease", "a widespread outbreak of an infectious disease", "n"],
  ["minimize", "make small or insignificant", "make small or insignificant", "v"],
  ["primitive", "rude", "belonging to an early stage of technical development", "a"],
  ["psychologist", "a scientist trained in psychology", "a scientist trained in psychology", "n"],
  ["absorb", "become imbued", "become imbued", "v"],
  ["infectious", "infective", "caused by infection or capable of causing infection", "a"],
  ["inferior", "of or characteristic of low rank or importance", "of or characteristic of low rank or importance", "a"],
  ["respiratory", "pertaining to respiration", "pertaining to respiration", "a"],
  ["calcium", "ca", "a white metallic element that burns with a brilliant light", "n"],
  ["coordinate", "organize", "bring order and organization to", "v"],
  ["electron", "negatron", "an elementary particle with negative charge", "n"],
  ["evolutionary", "of or relating to or produced by evolution", "of or relating to or produced by evolution", "a"],
  ["infinity", "eternity", "time without end", "n"],
  ["membrane", "a thin pliable sheet of material", "a thin pliable sheet of material", "n"],
  ["pardon", "excuse", "accept an excuse for", "v"],
  ["rainfall", "rain", "water falling in drops from vapor condensed in the atmosphere", "n"],
  ["stimulus", "input", "any stimulating information or event", "n"],
  ["vocabulary", "lexicon", "a language user's knowledge of words", "n"],
  ["afterward", "after", "happening at a time subsequent to a reference time", "r"],
  ["applause", "clapping", "a demonstration of approval by clapping the hands together", "n"],
  ["critique", "review", "an essay or article that gives a critical evaluation (as of a book or play)", "n"],
  ["diagnostic", "concerned with diagnosis", "concerned with diagnosis", "a"],
  ["differential", "derivative", "the result of mathematical differentiation", "n"],
  ["discourse", "extended verbal expression in speech or writing", "extended verbal expression in speech or writing", "n"],
  ["dominance", "laterality", "superior development of one side of the body", "n"],
  ["exploit", "work", "use or manipulate to one's advantage", "v"],
  ["nationalism", "patriotism", "love of country and willingness to sacrifice for it", "n"],
  ["straightforward", "free from ambiguity", "free from ambiguity", "a"],
  ["bracket", "a category falling within certain defined limits", "a category falling within certain defined limits", "n"],
  ["synthesis", "the combination of ideas into a complex whole", "the combination of ideas into a complex whole", "n"],
  ["clarify", "elucidate", "make clear and (more) comprehensible", "v"],
  ["composer", "someone who composes music as a profession", "someone who composes music as a profession", "n"],
  ["correspondence", "communication by the exchange of letters", "communication by the exchange of letters", "n"],
  ["diagram", "a drawing intended to explain how something works", "a drawing intended to explain how something works", "n"],
  ["obscure", "vague", "not clearly understood or expressed", "a"],
  ["proposition", "suggestion", "a proposal offered for acceptance or rejection", "n"],
  ["autonomy", "liberty", "immunity from arbitrary exercise of authority: political independence", "n"],
  ["behavioral", "of or relating to behavior", "of or relating to behavior", "a"],
  ["commodity", "good", "articles of commerce", "n"],
  ["correlation", "correlativity", "a reciprocal relation between two or more things", "n"],
  ["fatigue", "tiredness", "temporary loss of strength and energy resulting from hard physical or mental work", "n"],
  ["fringe", "periphery", "the outside boundary or surface of something", "n"],
  ["instinct", "replete", "deeply filled or permeated", "a"],
  ["morality", "ethics", "motivation based on ideas of right and wrong", "n"],
  ["radius", "r", "the length of a line segment between the center and circumference of a circle or sphere", "n"],
  ["symbolic", "emblematic", "serving as a visible symbol for something abstract", "a"],
  ["economist", "an expert in the science of economics", "an expert in the science of economics", "n"],
  ["informal", "not formal", "not formal", "a"],
  ["marker", "marking", "a distinguishing symbol", "n"],
  ["problematic", "debatable", "open to doubt or debate", "a"],
  ["processor", "cpu", "the part of a computer (a microprocessor chip) that does most of the data processing", "n"],
  ["sodium", "na", "a silvery soft waxy metallic element of the alkali metal group", "n"],
  ["surplus", "excess", "a quantity much larger than is needed", "n"],
  ["systematic", "characterized by order and planning", "characterized by order and planning", "a"],
  ["unstable", "lacking stability or fixity or firmness", "lacking stability or fixity or firmness", "a"],
  ["credibility", "believability", "the quality of being believable or trustworthy", "n"],
  ["interfere", "intervene", "get involved, so as to alter or hinder an action, or through force or threat of force", "v"],
  ["selective", "tending to select", "tending to select", "a"],
  ["adverse", "untoward", "contrary to your interests or welfare", "a"],
  ["liable", "apt", "at risk of or subject to experiencing something usually unpleasant", "a"],
  ["specialty", "strength", "an asset of special worth or utility", "n"],
  ["coordination", "the skillful and effective interaction of movements", "the skillful and effective interaction of movements", "n"],
  ["elevation", "lift", "the event of something being raised upward", "n"],
  ["horizontal", "something that is oriented horizontally", "something that is oriented horizontally", "n"],
  ["mortality", "the quality or state of being mortal", "the quality or state of being mortal", "n"],
  ["particle", "atom", "a tiny piece of anything", "n"],
  ["progression", "a series with a definite pattern of advance", "a series with a definite pattern of advance", "n"],
  ["rejection", "the act of rejecting something", "the act of rejecting something", "n"],
  ["reservoir", "a large or extra supply of something", "a large or extra supply of something", "n"],
  ["sensation", "esthesis", "an unelaborated elementary awareness of stimulation", "n"],
  ["shuttle", "travel back and forth between two points", "travel back and forth between two points", "v"],
  ["transparency", "permitting the free passage of electromagnetic radiation", "permitting the free passage of electromagnetic radiation", "n"],
  ["likelihood", "likeliness", "the probability of a specified outcome", "n"],
  ["necessity", "the condition of being essential or indispensable", "the condition of being essential or indispensable", "n"],
  ["observer", "beholder", "a person who becomes aware (of things or events) through the senses", "n"],
  ["sphere", "area", "a particular environment or walk of life", "n"],
  ["verbal", "communicated in the form of words", "communicated in the form of words", "a"],
  ["airplane", "plane", "an aircraft that has a fixed wing and is powered by propellers or jets", "n"],
  ["altitude", "height", "elevation especially above sea level or above the earth's surface", "n"],
  ["competent", "properly or sufficiently qualified or capable or efficient", "properly or sufficiently qualified or capable or efficient", "a"],
  ["indicator", "a signal for attracting attention", "a signal for attracting attention", "n"],
  ["inequality", "lack of equality", "lack of equality", "n"],
  ["leisure", "time available for ease and relaxation", "time available for ease and relaxation", "n"],
  ["manuscript", "ms", "the form of a literary work submitted for publication", "n"],
  ["reliability", "dependability", "the quality of being dependable or reliable", "n"],
  ["discharge", "the sudden giving off of energy", "the sudden giving off of energy", "n"],
  ["elimination", "riddance", "the act of removing or getting rid of something", "n"],
  ["mentor", "a wise and trusted guide and advisor", "a wise and trusted guide and advisor", "n"],
  ["overhead", "located or originating from above", "located or originating from above", "a"],
  ["triangle", "trilateral", "a three-sided polygon", "n"],
  ["aggregate", "mass", "formed of separate units gathered into a mass or whole", "a"],
  ["composite", "complex", "a conceptual whole made up of complicated and related parts", "n"],
  ["illusion", "semblance", "an erroneous mental representation", "n"],
  ["motive", "need", "the psychological feature that arouses an organism to action toward a desired goal", "n"],
  ["optimal", "optimum", "most desirable possible under a restriction expressed or implied", "a"],
  ["profound", "of the greatest intensity", "of the greatest intensity", "a"],
  ["simulation", "model", "representation of something (sometimes on a smaller scale)", "n"],
  ["virtue", "virtuousness", "the quality of doing what is right and avoiding what is wrong", "n"],
  ["bargain", "dicker", "negotiate the terms of an exchange", "v"],
  ["correction", "rectification", "the act of offering an improvement to replace a mistake", "n"],
  ["execute", "action", "put in effect", "v"],
  ["messenger", "courier", "a person who carries a message", "n"],
  ["philosophical", "of or relating to philosophy or philosophers", "of or relating to philosophy or philosophers", "a"],
  ["punish", "penalize", "impose a penalty on", "v"],
  ["rhetoric", "using language effectively to please or persuade", "using language effectively to please or persuade", "n"],
  ["sensitivity", "sensitiveness", "responsiveness to external stimuli", "n"],
  ["synthetic", "not of natural origin", "not of natural origin", "a"],
  ["circulation", "movement through a circuit", "movement through a circuit", "n"],
  ["explicit", "expressed", "precisely and clearly expressed or readily observable", "a"],
  ["fraction", "the quotient of two rational numbers", "the quotient of two rational numbers", "n"],
  ["integral", "constitutional", "existing as an essential constituent or characteristic", "a"],
  ["marble", "a sculpture carved from marble", "a sculpture carved from marble", "n"],
  ["prediction", "anticipation", "the act of predicting (as by reasoning about the future)", "n"],
  ["puzzle", "get", "be a mystery or bewildering to", "v"],
  ["tricky", "slippery", "not to be trusted", "a"],
  ["viable", "feasible", "capable of being done with means at hand and circumstances as they are", "a"],
  ["configuration", "constellation", "an arrangement of parts or elements", "n"],
  ["sexuality", "gender", "the properties that distinguish organisms on the basis of their reproductive roles", "n"],
  ["atomic", "of or relating to or comprising atoms", "of or relating to or comprising atoms", "a"],
  ["sensible", "reasonable", "showing reason or sound judgment", "a"],
  ["cylinder", "a chamber within which piston moves", "a chamber within which piston moves", "n"],
  ["evident", "plain", "clearly revealed to the mind or the senses or judgment", "a"],
  ["facilitate", "ease", "make easier", "v"],
  ["fossil", "dodo", "someone whose style is out of fashion", "n"],
  ["injection", "the forceful insertion of a substance under pressure", "the forceful insertion of a substance under pressure", "n"],
  ["rehabilitation", "renewal", "the conversion of wasteland into land suitable for use of habitation or cultivation", "n"],
  ["resistant", "immune", "relating to or conferring immunity (to disease or infection)", "a"],
  ["vector", "transmitter", "any agent (person or animal or microorganism) that carries and transmits a disease", "n"],
  ["indirect", "having intervening factors or persons or influences", "having intervening factors or persons or influences", "a"],
  ["magnitude", "relative importance", "relative importance", "n"],
  ["outlet", "a place of business for retailing goods", "a place of business for retailing goods", "n"],
  ["arrears", "the state of being behind in payments", "the state of being behind in payments", "n"],
  ["assimilate", "absorb", "take up mentally", "v"],
  ["asterisk", "star", "a star-shaped character * used in printing", "n"],
  ["asymmetrical", "crooked", "irregular in shape or outline", "a"],
  ["augmentation", "the amount by which something increases", "the amount by which something increases", "n"],
  ["ayrshire", "hardy breed of dairy cattle from Ayr, Scotland", "hardy breed of dairy cattle from Ayr, Scotland", "n"],
  ["barter", "trade", "an equal exchange", "n"],
  ["bistro", "a small informal restaurant", "a small informal restaurant", "n"],
  ["bonanza", "an especially rich vein of precious ore", "an especially rich vein of precious ore", "n"],
  ["cannibal", "anthropophagus", "a person who eats human flesh", "n"],
  ["centurion", "the leader of 100 soldiers", "the leader of 100 soldiers", "n"],
  ["compendium", "collection", "a publication containing a variety of works", "n"],
  ["contentment", "happiness with one's situation in life", "happiness with one's situation in life", "n"],
  ["counterproductive", "tending to hinder the achievement of a goal", "tending to hinder the achievement of a goal", "a"],
  ["crayon", "write, draw, or trace with a crayon", "write, draw, or trace with a crayon", "v"],
  ["defenseless", "lacking protection or support", "lacking protection or support", "a"],
  ["deluge", "flood", "an overwhelming number or amount", "n"],
  ["desist", "refrain", "choose not to consume", "v"],
  ["dismissive", "showing indifference or disregard", "showing indifference or disregard", "a"],
  ["doable", "manageable", "capable of existing or taking place or proving true", "a"],
  ["doorbell", "bell", "a push button at an outer door that gives a ringing or buzzing signal when pushed", "n"],
  ["eastbound", "eastward", "moving toward the east", "a"],
  ["eucharist", "liturgy", "a Christian sacrament commemorating the Last Supper by consecrating bread and wine", "n"],
  ["expedite", "hasten", "speed up the progress of", "v"],
  ["extracellular", "located or occurring outside a cell or cells", "located or occurring outside a cell or cells", "a"],
  ["fastball", "smoke", "a pitch thrown with maximum velocity", "n"],
  ["fearsome", "terrible", "causing fear or dread or terror", "a"],
  ["fertilization", "impregnation", "creation by the physical union of male and female gametes", "n"],
  ["fervor", "fire", "feelings of great warmth and intensity", "n"],
  ["freighter", "bottom", "a cargo ship", "n"],
  ["glorify", "proclaim", "praise, glorify, or honor", "v"],
  ["holographic", "of or relating to holography or holograms", "of or relating to holography or holograms", "a"],
  ["hotspur", "a rash or impetuous person", "a rash or impetuous person", "n"],
  ["impediment", "check", "something immaterial that interferes with or delays action or progress", "n"],
  ["importation", "import", "commodities (goods or services) bought from a foreign country", "n"],
  ["inactivity", "inaction", "the state of being inactive", "n"],
  ["incendiary", "arsonist", "a criminal who illegally sets fire to property", "n"],
  ["insistent", "repetitive", "repetitive and persistent", "a"],
  ["macroeconomic", "of or relating to macroeconomics", "of or relating to macroeconomics", "a"],
  ["masquerade", "take part in a masquerade", "take part in a masquerade", "v"],
  ["materialism", "physicalism", "the philosophical theory that matter is the only reality", "n"],
  ["meager", "stingy", "deficient in amount or quality or extent", "a"],
  ["minion", "a servile or fawning dependant", "a servile or fawning dependant", "n"],
  ["motherland", "homeland", "the country where you were born", "n"],
  ["narcissism", "an exceptional interest in and admiration for yourself", "an exceptional interest in and admiration for yourself", "n"],
  ["observant", "paying close attention especially to details", "paying close attention especially to details", "a"],
  ["ostrich", "fast-running African flightless bird with two-toed feet", "fast-running African flightless bird with two-toed feet", "n"],
  ["overcast", "cloudiness", "the state of the sky when it is covered by clouds", "n"],
  ["paragon", "perfection", "an ideal instance", "n"],
  ["parochial", "insular", "narrowly restricted in outlook or scope", "a"],
  ["punter", "someone who propels a boat with a pole", "someone who propels a boat with a pole", "n"],
  ["renovate", "restitute", "restore to a previous or better condition", "v"],
  ["respiration", "breathing", "the bodily process of inhalation and exhalation", "n"],
  ["secondhand", "derived from what is primary or original", "derived from what is primary or original", "a"],
  ["shiver", "thrill", "tremble convulsively, as from fear or excitement", "v"],
  ["somber", "drab", "lacking brightness or color", "a"],
  ["splendor", "lustre", "a quality that outshines the usual", "n"],
  ["springtime", "spring", "the season of growth", "n"],
  ["standstill", "stalemate", "a situation in which no progress can be made or no advancement is possible", "n"],
  ["suffix", "postfix", "an affix that is added at the end of the word", "n"],
  ["thoracic", "pectoral", "of or relating to the chest or thorax", "a"],
  ["tremor", "shudder", "an involuntary vibration (as if from illness or fear)", "n"],
  ["twister", "cruller", "small friedcake formed into twisted strips and fried", "n"],
  ["unsatisfactory", "not giving satisfaction", "not giving satisfaction", "a"],
  ["unwritten", "based on custom rather than documentation", "based on custom rather than documentation", "a"],
  ["utilitarian", "useful", "having a useful function", "a"],
  ["wesleyan", "a follower of Wesleyanism", "a follower of Wesleyanism", "n"],
  ["willpower", "possession", "the trait of resolutely controlling your own behavior", "n"],
  ["woolly", "flocculent", "having a fluffy character or appearance", "a"],
  ["acquittal", "a judgment of not guilty", "a judgment of not guilty", "n"],
  ["acupuncture", "stylostixis", "treatment of pain or disease by inserting the tips of needles at specific points on the skin", "n"],
  ["armament", "weaponry used by military or naval force", "weaponry used by military or naval force", "n"],
  ["belligerent", "aggressive", "characteristic of an enemy or one eager to fight", "a"],
  ["botanic", "of or relating to plants or botany", "of or relating to plants or botany", "a"],
  ["boundless", "limitless", "seemingly boundless in amount, number, degree, or especially extent", "a"],
  ["brooch", "breastpin", "a decorative pin worn by women", "n"],
  ["campground", "campsite", "a site where people on holiday can pitch a tent", "n"],
  ["causeway", "provide with a causeway", "provide with a causeway", "v"],
  ["cleaver", "chopper", "a butcher's knife having a large square blade", "n"],
  ["coexist", "coexist peacefully, as of nations", "coexist peacefully, as of nations", "v"],
  ["coinage", "specie", "coins collectively", "n"],
  ["consummate", "fulfill sexually", "fulfill sexually", "v"],
  ["convene", "meet formally", "meet formally", "v"],
  ["decadent", "effete", "marked by excessive self-indulgence and moral decay", "a"],
  ["derivation", "deriving", "an explanation of the historical origins of a word or phrase", "n"],
  ["detectable", "noticeable", "capable of being detected", "a"],
  ["dredge", "cover before cooking", "cover before cooking", "v"],
  ["emulation", "ambition to equal or excel", "ambition to equal or excel", "n"],
  ["evasive", "deliberately vague or ambiguous", "deliberately vague or ambiguous", "a"],
  ["extinguish", "put an end to", "put an end to", "v"],
  ["federalist", "an advocate of federalism", "an advocate of federalism", "n"],
  ["fervent", "fiery", "characterized by intense emotion", "a"],
  ["fruitless", "vain", "unproductive of success", "a"],
  ["garnish", "any decoration added as a trimming or adornment", "any decoration added as a trimming or adornment", "n"],
  ["genealogical", "of or relating to genealogy", "of or relating to genealogy", "a"],
  ["headway", "clearance", "vertical space available to allow easy passage under something", "n"],
  ["hearsay", "rumor", "gossip (usually a mixture of truth and untruth) passed around by word of mouth", "n"],
  ["hideout", "den", "a hiding place", "n"],
  ["idyllic", "excellent and delightful in all respects", "excellent and delightful in all respects", "a"],
  ["impossibility", "impossibleness", "incapability of existing or occurring", "n"],
  ["impotent", "lacking power or ability", "lacking power or ability", "a"],
  ["inconsiderate", "without proper consideration or reflection", "without proper consideration or reflection", "a"],
  ["insatiable", "impossible to satisfy", "impossible to satisfy", "a"],
  ["instalment", "episode", "a part of a broadcast serial", "n"],
  ["instinctive", "natural", "unthinking", "a"],
  ["interpretive", "that provides interpretation", "that provides interpretation", "a"],
  ["intrepid", "brave", "invulnerable to fear or intimidation", "a"],
  ["magnate", "power", "a very wealthy or powerful businessman", "n"],
  ["merciless", "unmerciful", "having or showing no mercy", "a"],
  ["monochrome", "a black-and-white photograph or slide", "a black-and-white photograph or slide", "n"],
  ["mortuary", "morgue", "a building (or room) where dead bodies are kept before burial or cremation", "n"],
  ["nationalistic", "chauvinistic", "fanatically patriotic", "a"],
  ["nervousness", "jitteriness", "the anxious feeling you have when you have the jitters", "n"],
  ["obstetrics", "ob", "the branch of medicine dealing with childbirth and care of the mother", "n"],
  ["obtuse", "of an angle", "of an angle", "a"],
  ["particulate", "composed of distinct particles", "composed of distinct particles", "a"],
  ["polygon", "a closed plane figure bounded by straight sides", "a closed plane figure bounded by straight sides", "n"],
  ["proportionate", "being in due proportion", "being in due proportion", "a"],
  ["radiance", "glow", "the amount of electromagnetic radiation leaving or arriving at a point on a surface", "n"],
];

export const ISEE_MIDDLE_VOCABULARY = buildVocabularyBank(
  'im-vc',
  2,
  ISEE_MIDDLE_ENTRIES,
);

export const ISEE_UPPER_VOCABULARY = buildVocabularyBank(
  'iu-vc',
  3,
  ISEE_UPPER_ENTRIES,
);
