import type { Question } from './types';

export const MATH_QUESTIONS: Question[] = [
  {
    id: 'ma-001',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 347 + 285?',
    choices: ['522', '622', '632', '732'],
    answer: 2,
    explain: '7 + 5 = 12, so write 2 and carry 1. 4 + 8 + 1 = 13, carry 1. 3 + 2 + 1 = 6, giving 632.',
    difficulty: 1,
  },
  {
    id: 'ma-002',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Which fraction is equal to 2/5?',
    choices: ['4/10', '2/10', '5/10', '2/7'],
    answer: 0,
    explain: 'Multiply the top and bottom of 2/5 by 2 to get 4/10.',
    difficulty: 1,
  },
  {
    id: 'ma-003',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'In the number 43.827, which digit is in the hundredths place?',
    choices: ['8', '2', '7', '3'],
    answer: 1,
    explain: 'After the decimal point the places go tenths (8), hundredths (2), thousandths (7).',
    difficulty: 1,
  },
  {
    id: 'ma-004',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 25% of 80?',
    choices: ['16', '25', '32', '20'],
    answer: 3,
    explain: '25% is the same as 1/4, and 80 / 4 = 20.',
    difficulty: 1,
  },
  {
    id: 'ma-005',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'A rectangle is 8 cm long and 5 cm wide. What is its perimeter?',
    choices: ['26 cm', '40 cm', '13 cm', '16 cm'],
    answer: 0,
    explain: 'Perimeter adds all four sides: 8 + 5 + 8 + 5 = 26 cm.',
    difficulty: 1,
  },
  {
    id: 'ma-006',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 4 + 3 x 5?',
    choices: ['12', '15', '19', '35'],
    answer: 2,
    explain: 'Multiply before adding: 3 x 5 = 15, then 4 + 15 = 19.',
    difficulty: 1,
  },
  {
    id: 'ma-007',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'If n + 7 = 15, what is the value of n?',
    choices: ['7', '8', '9', '22'],
    answer: 1,
    explain: 'Take 7 away from both sides: 15 - 7 = 8, so n = 8.',
    difficulty: 1,
  },
  {
    id: 'ma-008',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 46 x 3?',
    choices: ['128', '1218', '148', '138'],
    answer: 3,
    explain: '3 x 6 = 18, so write 8 and carry 1. 3 x 4 = 12, plus the 1 is 13, giving 138.',
    difficulty: 1,
  },
  {
    id: 'ma-009',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 1/4 + 1/2?',
    choices: ['2/6', '1/6', '3/4', '2/3'],
    answer: 2,
    explain: 'Rewrite 1/2 as 2/4. Then 1/4 + 2/4 = 3/4.',
    difficulty: 1,
  },
  {
    id: 'ma-010',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Movie tickets cost $8 each. Maya spent $56 on tickets. How many did she buy?',
    choices: ['7', '6', '8', '9'],
    answer: 0,
    explain: 'Divide the total by the price: 56 / 8 = 7 tickets.',
    difficulty: 1,
  },
  {
    id: 'ma-011',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'How many inches are in 5 feet?',
    choices: ['50', '55', '72', '60'],
    answer: 3,
    explain: '1 foot = 12 inches, so 5 x 12 = 60 inches.',
    difficulty: 1,
  },
  {
    id: 'ma-012',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'In the number 3,742, what is the value of the digit 7?',
    choices: ['7', '700', '70', '7,000'],
    answer: 1,
    explain: 'The 7 sits in the hundreds place, so it is worth 700.',
    difficulty: 1,
  },
  {
    id: 'ma-013',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is the mode of this list: 2, 5, 3, 5, 7, 5, 8?',
    choices: ['5', '3', '7', '35'],
    answer: 0,
    explain: 'The mode is the number that appears most often. 5 appears three times.',
    difficulty: 1,
  },
  {
    id: 'ma-014',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is the name of a shape with 5 straight sides?',
    choices: ['Quadrilateral', 'Hexagon', 'Pentagon', 'Octagon'],
    answer: 2,
    explain: 'Penta means five, so a five-sided shape is a pentagon.',
    difficulty: 1,
  },
  {
    id: 'ma-015',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Write 0.75 as a percent.',
    choices: ['7.5%', '0.75%', '750%', '75%'],
    answer: 3,
    explain: 'Move the decimal point two places to the right: 0.75 = 75%.',
    difficulty: 1,
  },
  {
    id: 'ma-016',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 804 - 267?',
    choices: ['647', '537', '543', '637'],
    answer: 1,
    explain: 'Borrowing twice gives 537. Check it: 537 + 267 = 804.',
    difficulty: 2,
  },
  {
    id: 'ma-017',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 2/3 + 1/6?',
    choices: ['3/9', '1/2', '5/6', '5/9'],
    answer: 2,
    explain: 'Rewrite 2/3 as 4/6. Then 4/6 + 1/6 = 5/6.',
    difficulty: 2,
  },
  {
    id: 'ma-018',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 3.6 + 0.45?',
    choices: ['4.05', '8.1', '4.5', '4.15'],
    answer: 0,
    explain: 'Line up the decimal points: 3.60 + 0.45 = 4.05.',
    difficulty: 2,
  },
  {
    id: 'ma-019',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 10% of 350?',
    choices: ['3.5', '350', '30', '35'],
    answer: 3,
    explain: 'Finding 10% means dividing by 10, so 350 / 10 = 35.',
    difficulty: 2,
  },
  {
    id: 'ma-020',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is the area of a rectangle that is 12 inches by 7 inches?',
    choices: ['38 sq in', '84 sq in', '19 sq in', '74 sq in'],
    answer: 1,
    explain: 'Area = length x width = 12 x 7 = 84 square inches.',
    difficulty: 2,
  },
  {
    id: 'ma-021',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 20 - 2 x 6 + 3?',
    choices: ['111', '5', '11', '21'],
    answer: 2,
    explain: 'Multiply first: 2 x 6 = 12. Then work left to right: 20 - 12 + 3 = 11.',
    difficulty: 2,
  },
  {
    id: 'ma-022',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'If 4n = 36, what is the value of n?',
    choices: ['9', '32', '40', '8'],
    answer: 0,
    explain: 'Divide both sides by 4: 36 / 4 = 9, so n = 9.',
    difficulty: 2,
  },
  {
    id: 'ma-023',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 156 divided by 12?',
    choices: ['12', '14', '16', '13'],
    answer: 3,
    explain: '12 x 13 = 156, so 156 / 12 = 13.',
    difficulty: 2,
  },
  {
    id: 'ma-024',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Which of these fractions is the largest?',
    choices: ['2/3', '3/4', '5/8', '1/2'],
    answer: 1,
    explain: 'As decimals: 2/3 = 0.67, 3/4 = 0.75, 5/8 = 0.625, 1/2 = 0.5. So 3/4 is largest.',
    difficulty: 2,
  },
  {
    id: 'ma-025',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Which decimal is the largest?',
    choices: ['0.5', '0.45', '0.409', '0.049'],
    answer: 0,
    explain: 'Compare the tenths place first. 0.5 has 5 tenths, more than 4 tenths or 0 tenths.',
    difficulty: 2,
  },
  {
    id: 'ma-026',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Three notebooks cost $2.25 each. What is the total cost?',
    choices: ['$6.25', '$6.65', '$6.75', '$7.75'],
    answer: 2,
    explain: '3 x $2 = $6 and 3 x $0.25 = $0.75, so the total is $6.75.',
    difficulty: 2,
  },
  {
    id: 'ma-027',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'How many cups are in 3 quarts?',
    choices: ['6', '12', '9', '24'],
    answer: 1,
    explain: '1 quart = 4 cups, so 3 x 4 = 12 cups.',
    difficulty: 2,
  },
  {
    id: 'ma-028',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'A triangle has a base of 10 cm and a height of 6 cm. What is its area?',
    choices: ['60 sq cm', '16 sq cm', '32 sq cm', '30 sq cm'],
    answer: 3,
    explain: 'Area of a triangle = 1/2 x base x height = 1/2 x 10 x 6 = 30 square cm.',
    difficulty: 2,
  },
  {
    id: 'ma-029',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Round 4,687 to the nearest hundred.',
    choices: ['4,700', '4,600', '4,690', '5,000'],
    answer: 0,
    explain: 'The tens digit is 8, which is 5 or more, so the hundreds round up to 4,700.',
    difficulty: 2,
  },
  {
    id: 'ma-030',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is the mean of 4, 8, 6, 10, and 7?',
    choices: ['6', '8', '7', '35'],
    answer: 2,
    explain: 'Add them: 4 + 8 + 6 + 10 + 7 = 35. Then divide by 5 numbers: 35 / 5 = 7.',
    difficulty: 2,
  },
  {
    id: 'ma-031',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 1,000 - 458?',
    choices: ['552', '542', '642', '458'],
    answer: 1,
    explain: '1,000 - 458 = 542. Check it: 542 + 458 = 1,000.',
    difficulty: 2,
  },
  {
    id: 'ma-032',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 5/6 - 1/3?',
    choices: ['4/3', '2/3', '5/18', '1/2'],
    answer: 3,
    explain: 'Rewrite 1/3 as 2/6. Then 5/6 - 2/6 = 3/6, which simplifies to 1/2.',
    difficulty: 2,
  },
  {
    id: 'ma-033',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 0.37 x 100?',
    choices: ['3.7', '0.0037', '37', '370'],
    answer: 2,
    explain: 'Multiplying by 100 moves the decimal point two places right, so 0.37 becomes 37.',
    difficulty: 2,
  },
  {
    id: 'ma-034',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Write 3/5 as a percent.',
    choices: ['60%', '35%', '30%', '65%'],
    answer: 0,
    explain: '3/5 is the same as 6/10, which is 0.6, and 0.6 = 60%.',
    difficulty: 2,
  },
  {
    id: 'ma-035',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Two angles of a triangle measure 55 degrees and 65 degrees. What is the third angle?',
    choices: ['50 degrees', '60 degrees', '70 degrees', '120 degrees'],
    answer: 1,
    explain: 'The three angles of a triangle add to 180 degrees. 180 - 55 - 65 = 60 degrees.',
    difficulty: 2,
  },
  {
    id: 'ma-036',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Ben pays for a $13.40 item with a $20 bill. How much change does he get?',
    choices: ['$7.60', '$6.40', '$7.40', '$6.60'],
    answer: 3,
    explain: '$20.00 - $13.40 = $6.60.',
    difficulty: 2,
  },
  {
    id: 'ma-037',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'How many minutes are in 2 1/2 hours?',
    choices: ['120', '125', '150', '250'],
    answer: 2,
    explain: '2 hours = 120 minutes, and half an hour is 30 more, so 120 + 30 = 150 minutes.',
    difficulty: 2,
  },
  {
    id: 'ma-038',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Two angles together form a straight line. One measures 130 degrees. What is the other?',
    choices: ['50 degrees', '60 degrees', '230 degrees', '40 degrees'],
    answer: 0,
    explain: 'Angles on a straight line add to 180 degrees, so 180 - 130 = 50 degrees.',
    difficulty: 2,
  },
  {
    id: 'ma-039',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Simplify 18/24 to lowest terms.',
    choices: ['1/2', '3/4', '2/3', '5/6'],
    answer: 1,
    explain: 'Divide the top and bottom by 6: 18 / 6 = 3 and 24 / 6 = 4, so 18/24 = 3/4.',
    difficulty: 2,
  },
  {
    id: 'ma-040',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 3/8 + 1/4?',
    choices: ['4/12', '7/8', '1/2', '5/8'],
    answer: 3,
    explain: 'Rewrite 1/4 as 2/8. Then 3/8 + 2/8 = 5/8.',
    difficulty: 2,
  },
  {
    id: 'ma-041',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 24 x 15?',
    choices: ['360', '340', '240', '380'],
    answer: 0,
    explain: '24 x 10 = 240 and 24 x 5 = 120. Add them: 240 + 120 = 360.',
    difficulty: 3,
  },
  {
    id: 'ma-042',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 2 1/2 - 3/4?',
    choices: ['1 1/4', '2 1/4', '1 3/4', '1 1/2'],
    answer: 2,
    explain: 'Write 2 1/2 as 2 2/4, then borrow: 1 6/4 - 3/4 = 1 3/4.',
    difficulty: 3,
  },
  {
    id: 'ma-043',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 5.2 - 1.75?',
    choices: ['3.55', '4.45', '3.35', '3.45'],
    answer: 3,
    explain: 'Write 5.2 as 5.20 so the places line up. Then 5.20 - 1.75 = 3.45.',
    difficulty: 3,
  },
  {
    id: 'ma-044',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Write 0.08 as a fraction in lowest terms.',
    choices: ['1/8', '2/25', '8/10', '1/80'],
    answer: 1,
    explain: '0.08 means 8 hundredths, or 8/100. Divide top and bottom by 4 to get 2/25.',
    difficulty: 3,
  },
  {
    id: 'ma-045',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 15% of 60?',
    choices: ['6', '7.5', '9', '15'],
    answer: 2,
    explain: '10% of 60 is 6 and 5% of 60 is 3, so 15% is 6 + 3 = 9.',
    difficulty: 3,
  },
  {
    id: 'ma-046',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'A bus leaves at 9:15 am and arrives at 11:05 am. How long is the trip?',
    choices: ['1 hour 50 minutes', '1 hour 10 minutes', '2 hours 50 minutes', '1 hour 55 minutes'],
    answer: 0,
    explain: 'From 9:15 to 11:15 is 2 hours, but the bus arrives 10 minutes sooner: 1 hour 50 minutes.',
    difficulty: 3,
  },
  {
    id: 'ma-047',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'A ribbon is 2 meters long. Jo cuts off 45 cm. How much ribbon is left?',
    choices: ['145 cm', '155 cm', '55 cm', '165 cm'],
    answer: 1,
    explain: '2 meters = 200 cm, and 200 - 45 = 155 cm.',
    difficulty: 3,
  },
  {
    id: 'ma-048',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'A square has a perimeter of 36 cm. What is its area?',
    choices: ['36 sq cm', '144 sq cm', '324 sq cm', '81 sq cm'],
    answer: 3,
    explain: 'Each side is 36 / 4 = 9 cm, so the area is 9 x 9 = 81 square cm.',
    difficulty: 3,
  },
  {
    id: 'ma-049',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 5^2 - 3 x 4?',
    choices: ['-2', '88', '13', '28'],
    answer: 2,
    explain: '5^2 = 25 and 3 x 4 = 12. Then 25 - 12 = 13.',
    difficulty: 3,
  },
  {
    id: 'ma-050',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is 6 x (7 - 2) / 3?',
    choices: ['10', '14', '40', '12'],
    answer: 0,
    explain: 'Parentheses first: 7 - 2 = 5. Then 6 x 5 = 30, and 30 / 3 = 10.',
    difficulty: 3,
  },
  {
    id: 'ma-051',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'What is the median of 3, 9, 5, 12, and 7?',
    choices: ['5', '9', '36', '7'],
    answer: 3,
    explain: 'Put them in order: 3, 5, 7, 9, 12. The middle number is 7.',
    difficulty: 3,
  },
  {
    id: 'ma-052',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'If 3n + 2 = 20, what is the value of n?',
    choices: ['7', '6', '18', '9'],
    answer: 1,
    explain: 'Subtract 2 from both sides: 3n = 18. Then divide by 3 to get n = 6.',
    difficulty: 3,
  },
  {
    id: 'ma-053',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'Round 12.68 to the nearest tenth.',
    choices: ['12.7', '12.6', '13.0', '12.68'],
    answer: 0,
    explain: 'The hundredths digit is 8, which is 5 or more, so the tenths round up to 12.7.',
    difficulty: 3,
  },
  {
    id: 'ma-054',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'How many meters is 250 cm?',
    choices: ['25 m', '0.25 m', '2.5 m', '250 m'],
    answer: 2,
    explain: '100 cm makes 1 meter, so 250 / 100 = 2.5 meters.',
    difficulty: 3,
  },
  {
    id: 'ma-055',
    subject: 'math',
    kind: 'math_achievement',
    prompt: 'A movie starts at 6:45 pm and lasts 1 hour 40 minutes. What time does it end?',
    choices: ['8:15 pm', '8:25 pm', '7:25 pm', '8:05 pm'],
    answer: 1,
    explain: '6:45 plus 1 hour is 7:45. Then 7:45 plus 40 minutes is 8:25 pm.',
    difficulty: 3,
  },
];
