import type { Question } from './types';

export const QUANTITATIVE_QUESTIONS: Question[] = [
  {
    id: 'qr-001',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What number comes next in the pattern? 3, 6, 9, 12, ___',
    choices: ['13', '14', '15', '16'],
    answer: 2,
    explain: 'The pattern adds 3 each time. 12 + 3 = 15.',
    difficulty: 1,
  },
  {
    id: 'qr-002',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What number comes next in the pattern? 2, 4, 8, 16, ___',
    choices: ['32', '20', '24', '18'],
    answer: 0,
    explain: 'Each number doubles instead of adding. 16 x 2 = 32.',
    difficulty: 1,
  },
  {
    id: 'qr-003',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'The sum 19 + 42 is closest to which number?',
    choices: ['50', '60', '70', '80'],
    answer: 1,
    explain: 'Round to 20 + 40 = 60. The exact sum, 61, is closest to 60.',
    difficulty: 1,
  },
  {
    id: 'qr-004',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A bag holds 3 red, 4 blue, and 5 green marbles. What is the probability of drawing a red marble?',
    choices: ['1/3', '1/2', '1/4', '3/4'],
    answer: 2,
    explain: 'There are 3 red out of 12 total marbles. 3/12 simplifies to 1/4.',
    difficulty: 1,
  },
  {
    id: 'qr-005',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'If [box] + 7 = 15, what number is in the box?',
    choices: ['8', '9', '22', '7'],
    answer: 0,
    explain: 'Undo the addition: 15 - 7 = 8.',
    difficulty: 1,
  },
  {
    id: 'qr-006',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'How many centimeters are in 2 meters?',
    choices: ['20', '200', '2,000', '20,000'],
    answer: 1,
    explain: 'One meter is 100 centimeters, so 2 x 100 = 200.',
    difficulty: 1,
  },
  {
    id: 'qr-007',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A store sold 12 red, 8 blue, and 4 green shirts. How many more red shirts than green shirts were sold?',
    choices: ['4', '6', '8', '16'],
    answer: 2,
    explain: 'Compare only red and green: 12 - 4 = 8.',
    difficulty: 1,
  },
  {
    id: 'qr-008',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A square has sides of 5 inches. What is its perimeter, in inches?',
    choices: ['10', '15', '25', '20'],
    answer: 3,
    explain: 'Perimeter adds all four sides: 5 x 4 = 20. The 25 would be the area.',
    difficulty: 1,
  },
  {
    id: 'qr-009',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which number is closest to 100?',
    choices: ['89', '97', '104', '112'],
    answer: 1,
    explain: '97 is only 3 away from 100, while 104 is 4 away.',
    difficulty: 1,
  },
  {
    id: 'qr-010',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'There are 4 boxes with 6 pencils in each box. How many pencils are there in all?',
    choices: ['24', '10', '18', '30'],
    answer: 0,
    explain: 'Equal groups means multiply: 4 x 6 = 24.',
    difficulty: 1,
  },
  {
    id: 'qr-011',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What is half of 46?',
    choices: ['21', '23', '24', '32'],
    answer: 1,
    explain: 'Half of 40 is 20 and half of 6 is 3, so half of 46 is 23.',
    difficulty: 1,
  },
  {
    id: 'qr-012',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A spinner has 4 equal sections, and exactly one is red. What is the probability of landing on red?',
    choices: ['1/2', '1/3', '3/4', '1/4'],
    answer: 3,
    explain: 'One winning section out of 4 equal sections is 1/4.',
    difficulty: 1,
  },
  {
    id: 'qr-013',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What is 348 rounded to the nearest hundred?',
    choices: ['300', '350', '400', '340'],
    answer: 0,
    explain: '348 sits between 300 and 400, and 48 is less than 50, so it rounds down to 300.',
    difficulty: 1,
  },
  {
    id: 'qr-014',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which capital letter can be folded down the middle so both halves match?',
    choices: ['R', 'F', 'A', 'J'],
    answer: 2,
    explain: 'A has a vertical line of symmetry. R, F, and J do not match when folded.',
    difficulty: 1,
  },
  {
    id: 'qr-015',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which unit is best for measuring the length of a pencil?',
    choices: ['miles', 'inches', 'gallons', 'pounds'],
    answer: 1,
    explain: 'Inches measure short lengths. Gallons measure volume and pounds measure weight.',
    difficulty: 1,
  },
  {
    id: 'qr-016',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What number comes next in the pattern? 1, 4, 9, 16, ___',
    choices: ['20', '24', '25', '36'],
    answer: 2,
    explain: 'These are square numbers: 1, 2^2, 3^2, 4^2. Next is 5^2 = 25.',
    difficulty: 2,
  },
  {
    id: 'qr-017',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What number comes next in the pattern? 2, 5, 11, 23, ___',
    choices: ['35', '44', '46', '47'],
    answer: 3,
    explain: 'Each step doubles and adds 1. 23 x 2 + 1 = 47.',
    difficulty: 2,
  },
  {
    id: 'qr-018',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Three pencils cost 45 cents. At the same rate, how much do 5 pencils cost?',
    choices: ['75 cents', '60 cents', '70 cents', '90 cents'],
    answer: 0,
    explain: 'One pencil costs 45 / 3 = 15 cents, so 5 pencils cost 5 x 15 = 75 cents.',
    difficulty: 2,
  },
  {
    id: 'qr-019',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A bag holds 4 red marbles and 6 blue marbles. What is the probability of drawing a marble that is NOT red?',
    choices: ['2/5', '3/5', '1/2', '2/3'],
    answer: 1,
    explain: 'Not red means blue: 6 out of 10 marbles, and 6/10 simplifies to 3/5.',
    difficulty: 2,
  },
  {
    id: 'qr-020',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A rectangle is 4 cm wide and 7 cm long. What is its area in square centimeters?',
    choices: ['11', '22', '28', '47'],
    answer: 2,
    explain: 'Area multiplies the sides: 4 x 7 = 28. The 22 is the perimeter.',
    difficulty: 2,
  },
  {
    id: 'qr-021',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which is the best estimate of 48 x 21?',
    choices: ['1,000', '100', '500', '10,000'],
    answer: 0,
    explain: 'Round to 50 x 20 = 1,000. The exact answer is 1,008.',
    difficulty: 2,
  },
  {
    id: 'qr-022',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A class voted for lunch: 9 chose pizza, 6 chose tacos, 5 chose burgers. What fraction of the class chose pizza?',
    choices: ['9/11', '1/3', '1/2', '9/20'],
    answer: 3,
    explain: 'The whole class is 9 + 6 + 5 = 20 students, so pizza is 9/20.',
    difficulty: 2,
  },
  {
    id: 'qr-023',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'If 5 x [box] = 45, what number is in the box?',
    choices: ['5', '9', '40', '50'],
    answer: 1,
    explain: 'Undo the multiplication: 45 / 5 = 9.',
    difficulty: 2,
  },
  {
    id: 'qr-024',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A car travels 120 miles in 3 hours. At the same speed, how far does it travel in 5 hours?',
    choices: ['150 miles', '180 miles', '200 miles', '240 miles'],
    answer: 2,
    explain: 'The speed is 120 / 3 = 40 miles per hour, so 5 x 40 = 200 miles.',
    difficulty: 2,
  },
  {
    id: 'qr-025',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which is the best estimate of 297 + 604?',
    choices: ['900', '800', '1,100', '700'],
    answer: 0,
    explain: 'Round to 300 + 600 = 900. The exact sum is 901.',
    difficulty: 2,
  },
  {
    id: 'qr-026',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What is the value of 3 x (4 + 2)?',
    choices: ['9', '14', '20', '18'],
    answer: 3,
    explain: 'Do the parentheses first: 4 + 2 = 6, then 3 x 6 = 18.',
    difficulty: 2,
  },
  {
    id: 'qr-027',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A fair coin is flipped twice. What is the probability that both flips land heads?',
    choices: ['1/2', '1/3', '1/4', '1/8'],
    answer: 2,
    explain: 'The four equally likely results are HH, HT, TH, TT. Only one is HH, so 1/4.',
    difficulty: 2,
  },
  {
    id: 'qr-028',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A rectangle has a perimeter of 20 inches and a length of 6 inches. What is its width?',
    choices: ['2 inches', '4 inches', '8 inches', '14 inches'],
    answer: 1,
    explain: 'Half the perimeter is one length plus one width: 10 - 6 = 4 inches.',
    difficulty: 2,
  },
  {
    id: 'qr-029',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which fraction is closest to 1/2?',
    choices: ['4/9', '1/4', '2/3', '5/6'],
    answer: 0,
    explain: 'Half of 9 is 4.5, so 4/9 is just under 1/2. The others are much farther away.',
    difficulty: 2,
  },
  {
    id: 'qr-030',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A shirt costs $18. It is on sale for 1/3 off. What is the sale price?',
    choices: ['$6', '$15', '$54', '$12'],
    answer: 3,
    explain: '1/3 of 18 is 6, and that discount comes off: 18 - 6 = 12.',
    difficulty: 2,
  },
  {
    id: 'qr-031',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What number comes next in the pattern? 100, 91, 82, 73, ___',
    choices: ['63', '64', '65', '72'],
    answer: 1,
    explain: 'Each step subtracts 9. 73 - 9 = 64.',
    difficulty: 2,
  },
  {
    id: 'qr-032',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which number is a multiple of both 3 and 4?',
    choices: ['9', '16', '24', '30'],
    answer: 2,
    explain: '24 = 3 x 8 and 24 = 4 x 6. 30 is a multiple of 3 but not of 4.',
    difficulty: 2,
  },
  {
    id: 'qr-033',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A rope is 3 feet 5 inches long. How many inches long is the rope?',
    choices: ['41', '35', '38', '45'],
    answer: 0,
    explain: '3 feet is 3 x 12 = 36 inches, and 36 + 5 = 41.',
    difficulty: 2,
  },
  {
    id: 'qr-034',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Ana has twice as many stickers as Ben. Together they have 18 stickers. How many does Ben have?',
    choices: ['9', '12', '8', '6'],
    answer: 3,
    explain: 'Ben is 1 share and Ana is 2 shares, so 3 shares equal 18 and one share is 6.',
    difficulty: 2,
  },
  {
    id: 'qr-035',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A movie starts at 6:45 pm and lasts 1 hour 40 minutes. What time does it end?',
    choices: ['8:05 pm', '8:15 pm', '8:25 pm', '7:25 pm'],
    answer: 2,
    explain: 'Add the hour first: 6:45 becomes 7:45. Then 40 more minutes gives 8:25 pm.',
    difficulty: 2,
  },
  {
    id: 'qr-036',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Rainfall was 4 in Monday, 0 in Tuesday, 3 in Wednesday, and 5 in Thursday. What is the average rainfall per day?',
    choices: ['2 in', '3 in', '4 in', '12 in'],
    answer: 1,
    explain: 'The total is 12 inches over 4 days, and 12 / 4 = 3.',
    difficulty: 2,
  },
  {
    id: 'qr-037',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which of these has the same value as 1/4?',
    choices: ['0.14', '2/5', '3/8', '25/100'],
    answer: 3,
    explain: '25/100 simplifies to 1/4. 3/8 is a bit more than 1/4 and 0.14 is less.',
    difficulty: 2,
  },
  {
    id: 'qr-038',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A box holds 8 crayons. What is the smallest number of boxes needed to hold 30 crayons?',
    choices: ['4', '3', '8', '30'],
    answer: 0,
    explain: 'Three boxes hold only 24 crayons, so a fourth box is needed for the last 6.',
    difficulty: 2,
  },
  {
    id: 'qr-039',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'The perimeter of a square is 36 cm. How long is one side?',
    choices: ['4 cm', '6 cm', '9 cm', '18 cm'],
    answer: 2,
    explain: 'A square has 4 equal sides, so 36 / 4 = 9 cm.',
    difficulty: 2,
  },
  {
    id: 'qr-040',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A bag holds 5 red, 5 blue, and 10 yellow marbles. One marble is drawn without looking. Which color is most likely?',
    choices: ['red', 'yellow', 'blue', 'all are equally likely'],
    answer: 1,
    explain: 'Yellow has 10 marbles, more than red or blue with 5 each.',
    difficulty: 2,
  },
  {
    id: 'qr-041',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What number comes next in the pattern? 1, 1, 2, 3, 5, 8, ___',
    choices: ['10', '11', '16', '13'],
    answer: 3,
    explain: 'Each number is the sum of the two before it. 5 + 8 = 13.',
    difficulty: 3,
  },
  {
    id: 'qr-042',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'If ([box] x 3) - 4 = 14, what number is in the box?',
    choices: ['6', '5', '18', '10'],
    answer: 0,
    explain: 'Undo in reverse: 14 + 4 = 18, then 18 / 3 = 6.',
    difficulty: 3,
  },
  {
    id: 'qr-043',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A spinner has 8 equal sections numbered 1 to 8. What is the probability of spinning an even number greater than 4?',
    choices: ['1/2', '1/4', '3/8', '1/8'],
    answer: 1,
    explain: 'Only 6 and 8 are even and greater than 4, so 2/8 = 1/4.',
    difficulty: 3,
  },
  {
    id: 'qr-044',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A recipe for 12 muffins uses 2 cups of flour. How many cups are needed for 30 muffins?',
    choices: ['3 cups', '4 cups', '5 cups', '6 cups'],
    answer: 2,
    explain: 'One cup makes 6 muffins, so 30 / 6 = 5 cups.',
    difficulty: 3,
  },
  {
    id: 'qr-045',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A rectangle has an area of 24 square inches and one side is 4 inches. What is its perimeter?',
    choices: ['10 inches', '12 inches', '24 inches', '20 inches'],
    answer: 3,
    explain: 'The other side is 24 / 4 = 6 inches, so the perimeter is 4 + 6 + 4 + 6 = 20.',
    difficulty: 3,
  },
  {
    id: 'qr-046',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What is 1/2 of 1/3?',
    choices: ['1/6', '1/5', '2/3', '5/6'],
    answer: 0,
    explain: 'Half of a third is a sixth: 1/2 x 1/3 = 1/6.',
    difficulty: 3,
  },
  {
    id: 'qr-047',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which fraction is the greatest?',
    choices: ['3/5', '5/8', '1/2', '7/16'],
    answer: 1,
    explain: '5/8 = 0.625, which beats 3/5 = 0.6, 1/2 = 0.5, and 7/16 = 0.4375.',
    difficulty: 3,
  },
  {
    id: 'qr-048',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A faucet drips 3 drops every 2 seconds. How many drops fall in 1 minute?',
    choices: ['30', '60', '90', '120'],
    answer: 2,
    explain: 'One minute holds 60 / 2 = 30 two-second periods, and 30 x 3 = 90 drops.',
    difficulty: 3,
  },
  {
    id: 'qr-049',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Which number rounds to 500 when rounded to the nearest hundred?',
    choices: ['449', '551', '390', '462'],
    answer: 3,
    explain: '462 is closer to 500 than to 400. 449 rounds to 400 and 551 rounds to 600.',
    difficulty: 3,
  },
  {
    id: 'qr-050',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'In a class of 24 students, 1/3 walk and 1/4 bike. The rest ride the bus. How many ride the bus?',
    choices: ['10', '14', '8', '18'],
    answer: 0,
    explain: '8 walk and 6 bike, which is 14 students, so 24 - 14 = 10 ride the bus.',
    difficulty: 3,
  },
  {
    id: 'qr-051',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'How many lines of symmetry does a rectangle that is not a square have?',
    choices: ['0', '1', '2', '4'],
    answer: 2,
    explain: 'It folds evenly across its width and across its length only, giving 2 lines.',
    difficulty: 3,
  },
  {
    id: 'qr-052',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A store has 4 shelves with 19 boxes on each shelf. Which is the best estimate of the total?',
    choices: ['40', '80', '100', '400'],
    answer: 1,
    explain: 'Round 19 to 20: 4 x 20 = 80. The exact total is 76.',
    difficulty: 3,
  },
  {
    id: 'qr-053',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'Two pens cost the same as 3 pencils. A pencil costs 20 cents. How much do 2 pens cost?',
    choices: ['30 cents', '40 cents', '50 cents', '60 cents'],
    answer: 3,
    explain: 'Three pencils cost 3 x 20 = 60 cents, and 2 pens cost the same amount.',
    difficulty: 3,
  },
  {
    id: 'qr-054',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'What is the 10th number in the pattern 5, 10, 15, 20, ...?',
    choices: ['50', '45', '55', '100'],
    answer: 0,
    explain: 'Each term is 5 times its position, so the 10th term is 10 x 5 = 50.',
    difficulty: 3,
  },
  {
    id: 'qr-055',
    subject: 'quantitative',
    kind: 'quant_reasoning',
    prompt: 'A bag holds 2 red and 3 blue marbles. One red marble is taken out. What is the probability the next marble drawn is blue?',
    choices: ['3/5', '1/2', '2/3', '3/4'],
    answer: 3,
    explain: 'After removing a red, 4 marbles remain and 3 are blue, so 3/4.',
    difficulty: 3,
  },
];
