import type { Question } from './types';

export const VERBAL_QUESTIONS: Question[] = [
  // ---------- Synonyms (vb-001 .. vb-040) ----------
  {
    id: 'vb-001',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'ABUNDANT',
    choices: ['costly', 'narrow', 'plentiful', 'hidden'],
    answer: 2,
    explain: 'Abundant means there is a lot of something. Plentiful means the same thing.',
    difficulty: 1,
  },
  {
    id: 'vb-002',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CAUTIOUS',
    choices: ['careful', 'bold', 'cheerful', 'hasty'],
    answer: 0,
    explain: 'Cautious means acting carefully so you do not get hurt. Bold and hasty are the opposite.',
    difficulty: 1,
  },
  {
    id: 'vb-003',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'BRITTLE',
    choices: ['bendable', 'spotless', 'heavy', 'easily broken'],
    answer: 3,
    explain: 'Brittle things snap instead of bending, so they are easily broken.',
    difficulty: 2,
  },
  {
    id: 'vb-004',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GENEROUS',
    choices: ['strict', 'clever', 'polite', 'willing to give'],
    answer: 3,
    explain: 'Generous means happy to share or give things away. Polite is close, but it is not the same idea.',
    difficulty: 1,
  },
  {
    id: 'vb-005',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'SUMMIT',
    choices: ['deep valley', 'highest point', 'narrow trail', 'rocky ledge'],
    answer: 1,
    explain: 'The summit is the very top of a mountain, which is its highest point.',
    difficulty: 2,
  },
  {
    id: 'vb-006',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'VACANT',
    choices: ['crowded', 'locked', 'empty', 'noisy'],
    answer: 2,
    explain: 'Vacant means nobody is using it, so it is empty. A locked room can still be full.',
    difficulty: 1,
  },
  {
    id: 'vb-007',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'TRANQUIL',
    choices: ['peaceful', 'stormy', 'chilly', 'crowded'],
    answer: 0,
    explain: 'Tranquil means calm and quiet, so peaceful is the match.',
    difficulty: 2,
  },
  {
    id: 'vb-008',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'WEARY',
    choices: ['worried', 'very tired', 'hungry', 'angry'],
    answer: 1,
    explain: 'Weary means worn out from working or traveling, so it means very tired.',
    difficulty: 1,
  },
  {
    id: 'vb-009',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'STURDY',
    choices: ['shiny', 'flimsy', 'hollow', 'strongly built'],
    answer: 3,
    explain: 'Sturdy things are solid and hard to break, so they are strongly built. Flimsy is the opposite.',
    difficulty: 1,
  },
  {
    id: 'vb-010',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'MIMIC',
    choices: ['insult', 'invent', 'copy', 'ignore'],
    answer: 2,
    explain: 'To mimic someone is to act or sound just like them, which means to copy them.',
    difficulty: 2,
  },
  {
    id: 'vb-011',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'VORACIOUS',
    choices: ['having a huge appetite', 'having very little interest', 'feeling extremely full', 'feeling deeply tired'],
    answer: 0,
    explain: 'A voracious reader devours book after book, unable to get enough. Voracious describes an appetite that is never satisfied.',
    difficulty: 3,
  },
  {
    id: 'vb-012',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FEEBLE',
    choices: ['gentle', 'silent', 'weak', 'elderly'],
    answer: 2,
    explain: 'Feeble means having almost no strength, so it means weak. Older people can be feeble, but the word itself means weak.',
    difficulty: 2,
  },
  {
    id: 'vb-013',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HOIST',
    choices: ['drag', 'lift up', 'tie down', 'throw away'],
    answer: 1,
    explain: 'To hoist something is to raise it, often with a rope or crane, so it means to lift up.',
    difficulty: 2,
  },
  {
    id: 'vb-014',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DROWSY',
    choices: ['lazy', 'dizzy', 'gloomy', 'sleepy'],
    answer: 3,
    explain: 'Drowsy means almost falling asleep, so sleepy is the match. Lazy is about not wanting to work.',
    difficulty: 1,
  },
  {
    id: 'vb-015',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'AMPLE',
    choices: ['more than enough', 'barely enough', 'oddly shaped', 'freshly made'],
    answer: 0,
    explain: 'Ample means there is plenty of something, which is more than enough.',
    difficulty: 3,
  },
  {
    id: 'vb-016',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DISMAL',
    choices: ['damp', 'gloomy', 'distant', 'dusty'],
    answer: 1,
    explain: 'Dismal means dark and sad, so gloomy is the match. A damp room is not always gloomy.',
    difficulty: 2,
  },
  {
    id: 'vb-017',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'JAGGED',
    choices: ['very thin', 'brightly colored', 'smooth and round', 'sharp and uneven'],
    answer: 3,
    explain: 'Jagged edges stick out in rough points, so they are sharp and uneven.',
    difficulty: 2,
  },
  {
    id: 'vb-018',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'KEEN',
    choices: ['eager', 'careless', 'puzzled', 'gentle'],
    answer: 0,
    explain: 'Someone who is keen really wants to do something, so eager is the match.',
    difficulty: 2,
  },
  {
    id: 'vb-019',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'MEAGER',
    choices: ['evenly shared', 'freshly cooked', 'very small in amount', 'carefully saved'],
    answer: 2,
    explain: 'A meager amount is far less than you need, so it means very small in amount.',
    difficulty: 3,
  },
  {
    id: 'vb-020',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'NOVICE',
    choices: ['expert', 'beginner', 'teacher', 'helper'],
    answer: 1,
    explain: 'A novice is someone brand new at something, which is a beginner. Expert is the opposite.',
    difficulty: 2,
  },
  {
    id: 'vb-021',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'OBSTACLE',
    choices: ['a short rest', 'a helpful clue', 'something in the way', 'a loud noise'],
    answer: 2,
    explain: 'An obstacle blocks your path, so it is something in the way.',
    difficulty: 2,
  },
  {
    id: 'vb-022',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'PECULIAR',
    choices: ['private', 'perfect', 'playful', 'strange'],
    answer: 3,
    explain: 'Peculiar means odd or unusual, so strange is the match.',
    difficulty: 2,
  },
  {
    id: 'vb-023',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'QUAINT',
    choices: ['newly built', 'charmingly old-fashioned', 'badly damaged', 'very large'],
    answer: 1,
    explain: 'Quaint describes something old-fashioned in a pleasant way, like a tiny village cottage.',
    difficulty: 3,
  },
  {
    id: 'vb-024',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'RIGID',
    choices: ['stiff', 'hollow', 'rough', 'sticky'],
    answer: 0,
    explain: 'Rigid things will not bend at all, so they are stiff.',
    difficulty: 2,
  },
  {
    id: 'vb-025',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'SCARCE',
    choices: ['costly', 'useful', 'hard to find', 'well hidden'],
    answer: 2,
    explain: 'Scarce means there is very little of something, so it is hard to find. Something hidden may still be common.',
    difficulty: 2,
  },
  {
    id: 'vb-026',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'TIMID',
    choices: ['shy', 'tiny', 'careless', 'stubborn'],
    answer: 0,
    explain: 'Timid means easily frightened and not bold, so shy is the match. Timid has nothing to do with size.',
    difficulty: 1,
  },
  {
    id: 'vb-027',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'URGENT',
    choices: ['unusual', 'yearly', 'helpful', 'needing quick action'],
    answer: 3,
    explain: 'Something urgent must be handled right away, so it needs quick action.',
    difficulty: 1,
  },
  {
    id: 'vb-028',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'VIVID',
    choices: ['faded', 'bright and clear', 'very quick', 'slightly damp'],
    answer: 1,
    explain: 'Vivid colors and vivid memories stand out strongly, so vivid means bright and clear. Faded is the opposite.',
    difficulty: 2,
  },
  {
    id: 'vb-029',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'FERTILE',
    choices: ['flat', 'frozen', 'good for growing', 'freshly plowed'],
    answer: 2,
    explain: 'Fertile soil grows plants easily, so it is good for growing. Plowed soil is not always fertile.',
    difficulty: 3,
  },
  {
    id: 'vb-030',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'LINGER',
    choices: ['hurry off', 'argue loudly', 'forget quickly', 'stay longer'],
    answer: 3,
    explain: 'To linger is to hang around after it is time to go, so it means to stay longer.',
    difficulty: 2,
  },
  {
    id: 'vb-031',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'CONCEAL',
    choices: ['collect', 'hide', 'discover', 'repair'],
    answer: 1,
    explain: 'To conceal something is to keep it out of sight, so it means to hide. Discover is the opposite.',
    difficulty: 3,
  },
  {
    id: 'vb-032',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'AUSPICIOUS',
    choices: ['promising future success', 'promising future trouble', 'remarkably plain', 'extremely rare'],
    answer: 0,
    explain: 'An auspicious beginning is a favorable sign that good things are likely to follow.',
    difficulty: 3,
  },
  {
    id: 'vb-033',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'BLUNDER',
    choices: ['a long delay', 'a rude remark', 'a lucky break', 'a clumsy mistake'],
    answer: 3,
    explain: 'A blunder is a careless, silly error, so it is a clumsy mistake.',
    difficulty: 3,
  },
  {
    id: 'vb-034',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'DEVOUR',
    choices: ['share', 'serve', 'eat hungrily', 'cook slowly'],
    answer: 2,
    explain: 'To devour food is to gobble it right up, so it means to eat hungrily.',
    difficulty: 2,
  },
  {
    id: 'vb-035',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'BARREN',
    choices: ['empty of life', 'thickly wooded', 'partly shaded', 'newly planted'],
    answer: 0,
    explain: 'Barren land grows almost nothing, so it is empty of life.',
    difficulty: 3,
  },
  {
    id: 'vb-036',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'GRIM',
    choices: ['grimy', 'harsh and gloomy', 'greedy', 'tightly held'],
    answer: 1,
    explain: 'Grim means serious and unpleasant, so harsh and gloomy fits. Grimy just means dirty.',
    difficulty: 3,
  },
  {
    id: 'vb-037',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'HUMBLE',
    choices: ['helpful', 'wealthy', 'not boastful', 'unfriendly'],
    answer: 2,
    explain: 'A humble person does not brag about themselves, so humble means not boastful.',
    difficulty: 3,
  },
  {
    id: 'vb-038',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'BLIGHT',
    choices: ['a thing that spoils or destroys', 'a source of great joy', 'a moment of triumph', 'a sign of good luck'],
    answer: 0,
    explain: 'A blight is something that spoils or ruins, like a disease that destroys a field of crops.',
    difficulty: 3,
  },
  {
    id: 'vb-039',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'SOOTHE',
    choices: ['scold', 'calm', 'clean', 'stretch'],
    answer: 1,
    explain: 'To soothe someone is to make them feel better and less upset, so it means to calm.',
    difficulty: 2,
  },
  {
    id: 'vb-040',
    subject: 'verbal',
    kind: 'synonym',
    prompt: 'STERN',
    choices: ['strict', 'sturdy', 'generous', 'talkative'],
    answer: 0,
    explain: 'A stern teacher is serious and firm about the rules, so stern means strict. Sturdy only sounds similar.',
    difficulty: 3,
  },

  // ---------- Sentence completion (vb-041 .. vb-070) ----------
  {
    id: 'vb-041',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The desert was so ------ that only a few tough plants could survive there.',
    choices: ['humid', 'dry', 'fertile', 'shallow'],
    answer: 1,
    explain: 'A desert gets almost no rain, so it is dry. Dryness is what makes plants struggle to live.',
    difficulty: 1,
  },
  {
    id: 'vb-042',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Marco was so ------ after hiking all day that he fell asleep before dinner.',
    choices: ['curious', 'cheerful', 'nervous', 'weary'],
    answer: 3,
    explain: 'Weary means very tired. Hiking all day and falling asleep early both point to being worn out.',
    difficulty: 1,
  },
  {
    id: 'vb-043',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Because the ladder was old and ------, Dad refused to let anyone climb it.',
    choices: ['unsteady', 'sturdy', 'narrow', 'wooden'],
    answer: 0,
    explain: 'Unsteady means shaky and unsafe. Dad would only stop people from climbing if the ladder was not safe, and sturdy would be safe.',
    difficulty: 1,
  },
  {
    id: 'vb-044',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The kitten was ------ at first, but after a week it climbed right into my lap.',
    choices: ['playful', 'loud', 'timid', 'clumsy'],
    answer: 2,
    explain: 'Timid means shy and easily scared. The word but shows the kitten changed from shy to friendly.',
    difficulty: 1,
  },
  {
    id: 'vb-045',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Rain had been ------ all summer, so the town asked families to use less water.',
    choices: ['steady', 'scarce', 'heavy', 'sudden'],
    answer: 1,
    explain: 'Scarce means there is very little of something. Saving water only makes sense if rain was in short supply.',
    difficulty: 2,
  },
  {
    id: 'vb-046',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The lake was perfectly ------ at dawn, without a single ripple on the water.',
    choices: ['tranquil', 'choppy', 'murky', 'shallow'],
    answer: 0,
    explain: 'Tranquil means calm and still, which matches water that has no ripples at all.',
    difficulty: 2,
  },
  {
    id: 'vb-047',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Mrs. Ortiz is very ------ with her time, spending every Saturday tutoring students for free.',
    choices: ['careful', 'private', 'patient', 'generous'],
    answer: 3,
    explain: 'Generous means giving freely. Giving up every Saturday without being paid is a generous act.',
    difficulty: 2,
  },
  {
    id: 'vb-048',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The old dishes were so ------ that even a light tap could crack them.',
    choices: ['heavy', 'shiny', 'brittle', 'worn'],
    answer: 2,
    explain: 'Brittle means something breaks or snaps easily. A light tap cracking a dish shows it was brittle.',
    difficulty: 2,
  },
  {
    id: 'vb-049',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The apple tree gave such an ------ crop that we handed baskets of fruit to our neighbors.',
    choices: ['abundant', 'uneven', 'early', 'unusual'],
    answer: 0,
    explain: 'Abundant means a very large amount. Having enough extra to give away shows the crop was huge.',
    difficulty: 1,
  },
  {
    id: 'vb-050',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'A parrot can ------ human speech so well that visitors think someone is talking in the next room.',
    choices: ['ignore', 'mimic', 'teach', 'invent'],
    answer: 1,
    explain: 'To mimic is to copy exactly. The parrot is copying the sound of a person talking.',
    difficulty: 1,
  },
  {
    id: 'vb-051',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'After weeks of climbing, the team finally reached the ------ of the mountain and raised their flag.',
    choices: ['base', 'slope', 'trail', 'summit'],
    answer: 3,
    explain: 'The summit is the highest point of a mountain, which is where climbers finish and celebrate.',
    difficulty: 2,
  },
  {
    id: 'vb-052',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The apartment above ours has been ------ since the Reyes family moved out in March.',
    choices: ['noisy', 'crowded', 'vacant', 'remodeled'],
    answer: 2,
    explain: 'Vacant means empty, with nobody living there. The family moved out, so no one is in it.',
    difficulty: 2,
  },
  {
    id: 'vb-053',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The message was so ------ that the principal interrupted class to read it aloud right away.',
    choices: ['pleasant', 'urgent', 'confusing', 'lengthy'],
    answer: 1,
    explain: 'Urgent means it must be handled immediately. Interrupting class shows the news could not wait.',
    difficulty: 2,
  },
  {
    id: 'vb-054',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Ben is a ------ at chess, so his older sister explained the rules before their first game.',
    choices: ['novice', 'champion', 'coach', 'judge'],
    answer: 0,
    explain: 'A novice is a beginner. Ben needed the rules explained, so he is brand new to chess.',
    difficulty: 1,
  },
  {
    id: 'vb-055',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The hikers took ------ steps across the icy bridge, testing each board before trusting it.',
    choices: ['hurried', 'clumsy', 'cautious', 'confident'],
    answer: 2,
    explain: 'Cautious means careful to avoid danger. Testing each board first is exactly what a careful person does.',
    difficulty: 2,
  },
  {
    id: 'vb-056',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The cabin looked ------ from the outside, but inside it was warm and full of laughter.',
    choices: ['spacious', 'sturdy', 'crowded', 'dismal'],
    answer: 3,
    explain: 'Dismal means gloomy and depressing. The word but tells you the outside felt the opposite of warm and cheerful.',
    difficulty: 3,
  },
  {
    id: 'vb-057',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Warm afternoons in the quiet library always made Nina feel ------, and soon her eyes began to close.',
    choices: ['drowsy', 'restless', 'curious', 'irritable'],
    answer: 0,
    explain: 'Drowsy means sleepy. Her eyes closing is the clue that she was ready to doze off.',
    difficulty: 2,
  },
  {
    id: 'vb-058',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The rocks along the shore were sharp and ------, so we wore shoes to protect our feet.',
    choices: ['slippery', 'jagged', 'shifting', 'porous'],
    answer: 1,
    explain: 'Jagged means having rough, pointed edges. Sharp edges are why shoes were needed, and slippery rocks would not cut you.',
    difficulty: 3,
  },
  {
    id: 'vb-059',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'A fallen tree was the only ------ between us and the campsite, so we climbed over it and kept going.',
    choices: ['reward', 'shortcut', 'obstacle', 'warning'],
    answer: 2,
    explain: 'An obstacle is something that blocks your way. They had to climb over the tree to get past it.',
    difficulty: 2,
  },
  {
    id: 'vb-060',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The soil in the valley is so ------ that farmers there harvest two crops every year.',
    choices: ['rocky', 'shallow', 'frozen', 'fertile'],
    answer: 3,
    explain: 'Fertile soil grows plants very well, which is why two harvests a year are possible.',
    difficulty: 3,
  },
  {
    id: 'vb-061',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Although the evening meal was ------, the campers shared it without a single complaint.',
    choices: ['delicious', 'meager', 'spicy', 'filling'],
    answer: 1,
    explain: 'Meager means a very small amount. Although signals a problem, and sharing without complaining fits having too little food.',
    difficulty: 3,
  },
  {
    id: 'vb-062',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'My little brother tried to ------ the broken vase behind the curtain, but Mom spotted it right away.',
    choices: ['conceal', 'repair', 'discover', 'deliver'],
    answer: 0,
    explain: 'To conceal something is to hide it. Tucking the vase behind a curtain so Mom would not see it is hiding.',
    difficulty: 2,
  },
  {
    id: 'vb-063',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Visitors love the ------ little shops on Main Street, with their painted signs and creaky wooden floors.',
    choices: ['modern', 'enormous', 'crowded', 'quaint'],
    answer: 3,
    explain: 'Quaint means charming in an old-fashioned way. Painted signs and creaky wooden floors sound pleasantly old.',
    difficulty: 3,
  },
  {
    id: 'vb-064',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The workers used a crane to ------ the heavy steel beam to the top of the building.',
    choices: ['lower', 'fasten', 'hoist', 'measure'],
    answer: 2,
    explain: 'To hoist is to lift something heavy upward, which is what a crane does. Lower means the opposite direction.',
    difficulty: 2,
  },
  {
    id: 'vb-065',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Even after the storm knocked down two fences, the old oak still stood ------ in the yard.',
    choices: ['sturdy', 'fragile', 'hollow', 'crooked'],
    answer: 0,
    explain: 'Sturdy means strong and solid. The oak survived a storm strong enough to break fences.',
    difficulty: 2,
  },
  {
    id: 'vb-066',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The coach was ------ about being on time and made anyone who arrived late run an extra lap.',
    choices: ['casual', 'stern', 'anxious', 'cheerful'],
    answer: 1,
    explain: 'Stern means serious and firm about rules. Adding a punishment for lateness shows the coach would not bend.',
    difficulty: 3,
  },
  {
    id: 'vb-067',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'Rosa gave such a ------ description of the parade that I could almost hear the drums.',
    choices: ['brief', 'doubtful', 'vivid', 'polite'],
    answer: 2,
    explain: 'Vivid means so clear that you can picture it in your mind. Almost hearing the drums shows how clear it was.',
    difficulty: 2,
  },
  {
    id: 'vb-068',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The plastic ruler was ------ enough to bend into a circle without snapping.',
    choices: ['rigid', 'brittle', 'jagged', 'flexible'],
    answer: 3,
    explain: 'Flexible means able to bend without breaking. Rigid would not bend at all, and brittle would snap.',
    difficulty: 3,
  },
  {
    id: 'vb-069',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'We had ------ time before the bus came, so we even stopped to buy snacks on the way.',
    choices: ['ample', 'little', 'borrowed', 'exact'],
    answer: 0,
    explain: 'Ample means more than enough. Having extra time to stop for snacks shows they were not rushed.',
    difficulty: 1,
  },
  {
    id: 'vb-070',
    subject: 'verbal',
    kind: 'sentence_completion',
    prompt: 'The guests did not want to leave and ------ by the door, still telling stories.',
    choices: ['hurried', 'vanished', 'lingered', 'argued'],
    answer: 2,
    explain: 'To linger is to stay longer than you need to. They kept standing by the door instead of going home.',
    difficulty: 3,
  },
];
